### ISSUE TITLE
Avoid Confusion

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#10]
To avoid any confusion like I and @viveksb007  ended up working on the same code SensorList.py, I am hence telling I am starting to port MCP4728, NRF24L01, RadioLink (Peripherals) into the Android app. If you are working on same do let me know @viveksb007

**Comment by viveksb007** [comment]
@akarshan96 go ahead. I was starting to porting SPI(). Open separate issue for each class. and close each issue with PR.

**Comment by wavicles** [comment]
@akarshan96 @viveksb007  Good idea. open separate issue for each class and close after PR is merged. Lets share the work.
