### ISSUE TITLE
Hamburger icon to go other screens

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1031]
**Actual Behaviour**

User have to press on phone back button to go back to previous screen 

**Expected Behaviour**

There should be a hamburger icon to let user to go back to Instruments

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/11439477/41336079-b3ed6d7a-6f1d-11e8-9739-01fce2ced48c.png)

**Would you like to work on the issue?**

GSoC or interns

**Comment by Avjeet** [comment]
I will work on this issue.

**Comment by Avjeet** [comment]
@cweitat some activites dont have the app bar so how could I put this icon in them?

**Comment by cweitat** [comment]
@Avjeet I understand, so please discuss with @CloudyPadmal and the rest to see what is the best way to implement this; either to all or some activities.

**Comment by Avjeet** [comment]
@cweitat 👍 ok will do

**Comment by Avjeet** [comment]
@cweitat I have added the hamburger icon in activities which have app bar but there is one problem as I am thinking of adding those list of instruments in navigation panel as shown in image below. So should I include all the instrument or just those in which hamburger icon is there.
![image](https://user-images.githubusercontent.com/20573611/42553197-7ef3cef2-84fd-11e8-962f-ff80481c24cf.png)

**Comment by cweitat** [comment]
Leave this open for now until we find a way to a way to access the menu from every instrument

**Comment by Smit2010** [comment]
I would like to work on this. Can I take this issue?

**Comment by Smit2010** [comment]
The basic idea is to open the navigation drawer from every instrument activity right?
If yes, then I would like to work on this issue. Can I take this up?
@cweitat @CloudyPadmal

**Comment by Smit2010** [comment]
What exactly are you expecting with this issue? Implementing a back button to navigate back to instrument activity or implementing a navigation menu same as in MainActivity?
@cweitat @Avjeet @CloudyPadmal

**Comment by mariobehling** [comment]
In the meantime the implementation in most instruments was done differently with an back arrow. Therefore everyone please follow the same implementation in all instruments. Thanks.
