### ISSUE TITLE
No I/O takes place in Logic Analyzer instrument

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1033]
**Actual Behaviour**

Only placeholder data is used to plot the graph 

**Expected Behaviour**

There should be plot of the data that is generated by user

**Steps to reproduce it**

Observe Logic Analyzer instrument

**Would you like to work on the issue?**

Yes

**Comment by harsh-2711** [comment]
@CloudyPadmal I started fetching data from Logic Analyzer and I used (a * 0xff) | ((b * 0xff) << 8) to combine two bytes to form an integer. Is this correct ? The data plotted after modifying the fetched data is as shown

[la_final.zip](https://github.com/fossasia/pslab-android/files/2100407/la_final.zip)

**Comment by CloudyPadmal** [comment]
@harsh-2711 yes how you combine two bytes is correct. I cannot view the video as it shows as no read or write access.

**Comment by harsh-2711** [comment]
@CloudyPadmal  Go to properties -> permissions -> Give both permissions. Same problem existed for me but it is default by GitHub I guess

**Comment by CloudyPadmal** [comment]
@harsh-2711 this looks nice! Can you make a PR for this one?
