### ISSUE TITLE
Only single pin is working for I/O in Logic Analyzer

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1045]
**Actual Behaviour**

Only ID1 pin is working for doing plotting the data in Logic Analyzer Instrument for Single Channel Mode

**Expected Behaviour**

All the six pins should work

**Steps to reproduce it**

Download apk provided in PR #1044 and try to use any pin other than ID1 

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Fixed in #1137
