### ISSUE TITLE
convert the dialog guide of multimeter into bottonsheet guide

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#1074]
**Actual Behaviour**

Currentlty the multimeter is having dialog guide, that can only be used once.

**Expected Behaviour**

Guide should be viewable anytime so it can be implemented using bottomsheet.

**Steps to reproduce it**

Multimeter Activity->convert the dialog into bottomsheet

**Would you like to work on the issue?**

Yes

**Comment by abhinavraj23** [comment]
@Avjeet You have not opened a PR for this and you have already made a PR for bottomsheet of wave generator, I have almost done this , please let me make the PR
