### ISSUE TITLE
Less data points are set for digital pins in Wave Generator

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1078]
**Actual Behaviour**

Less data points are given the set property i.e. frequency and duty cycle in digital pins SQR1, SQR2, SQR3 and SQR4 as a result of which most of the data fetched in logic analyzer instrument remains zero

**Expected Behaviour**

Frequency and duty cycle should be set uniformly

**Steps to reproduce it**

Go to Wave Generator -> Set frequency and duty cycle for any digital pin -> Open Logic Analyzer -> Analyze

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

@Avjeet would I like to work or should I continue on it as this bug should be fixed as soon as possible and if you are busy then I can take it.

**Comment by Avjeet** [comment]
I am currently working on square wave production itself , I can take it.

**Comment by harsh-2711** [comment]
Great!!

**Comment by cweitat** [comment]
progress?

**Comment by Avjeet** [comment]
oh the PR #1184 has been made

**Comment by cweitat** [comment]
alright thanks 👍
