### ISSUE TITLE
Guides are not zoomable and so can't be viewed perfectly

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1079]
**Actual Behaviour**

All the instruments guide aren't zoomable and so some schematics and texts aren't visible completely

**Expected Behaviour**

The guide should be zoomable

**Steps to reproduce it**

Go to any instrument and go through the guide displayed

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by Avjeet** [comment]
@harsh-2711 if you are busy can i take up this.

**Comment by harsh-2711** [comment]
@Avjeet  I am almost done with this issue. Soon I will make a PR
