### ISSUE TITLE
Implement Pressure sensor in Instruments with updated UI

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#1094]
**Actual Behaviour**
Barometer should have a new activity as an instrument and the UI needs to be changed accordingly

**Expected Behaviour**
Update the UI of the barometer and make it functional in the instrument section.

**Steps to reproduce it**
None

**LogCat for the issue**
None

**Screenshots of the issue**
![barometer-altimeter](https://user-images.githubusercontent.com/34381723/41637123-f317750c-746f-11e8-824a-18bffdc58d17.png)
![barometer-pressure-tracker](https://user-images.githubusercontent.com/34381723/41637124-f355606a-746f-11e8-81ff-634e3555dd54.png)

**Would you like to work on the issue?**
Yes

**Comment by CloudyPadmal** [comment]
Yes this looks great. Try your best to reuse the libraries we have.

**Comment by yatri1609** [comment]
@CloudyPadmal Ya I'll be using the meter which has been used in the Lux Meter for the meter to show pressure.
