### ISSUE TITLE
Lux meter documentation

### ISSUE THREAD

**Issue by Vikum94** [fossasia/pslab-android#1116]
**Actual Behaviour**

No documentation us available for lux meter and how to use light sensors with lux meter

**Expected Behaviour**

Proper documentation of the instrument

**Steps to reproduce it**

> Not applicable

**LogCat for the issue**

> None

**Screenshots of the issue**

None

**Would you like to work on the issue?**

None

**Comment by CloudyPadmal** [comment]
`Would you like to work on the issue?` ?
