### ISSUE TITLE
Voltage measuring issues at SEN , CAP and AN8 pins

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#1141]
**Actual Behaviour**

Voltage measurement at SEN CAP and AN8 shows wrong value in multimeter.

**Expected Behaviour**

Voltage measurement should be accurate.

**Steps to reproduce it**

Change in the science lab codes

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@abhinavraj23 please note that SEN and CAP pins are not used to measure voltages. SEN pin will show 3.3V all the time if no resistor is connected. Only AN8 pin should take into consideration.

**Comment by abhinavraj23** [comment]
@CloudyPadmal But still voltage across them can be measured using the getVoltage just there is some bugs in it which I will fix :+1:

**Comment by CloudyPadmal** [comment]
OK let's see your fix first. FYI we measure resistance using a voltage divider technique by measuring voltage at SEN pin internally. We don't recommend using SEN or CAP pins to measure voltage of an external source.

**Comment by abhinavraj23** [comment]
@CloudyPadmal I was performing the experiment where I connected the PV1 pin to the SEN pin and using the multimeter I tried to measure the voltage, so it was working fine except for a bug of getting multiplied by a factor of two.

**Comment by CloudyPadmal** [comment]
I kinda suspect when you change those settings, it will affect resistance measurement. I'm not sure. Let's see.

**Comment by abhinavraj23** [comment]
@CloudyPadmal I am constantly doing work on the capacitance issue but that is just not happening, no matter how much I try, so I also need other tasks to work because I can't just spend all my time on just one issue, which I have tried a lot to solve but still have problems.

**Comment by abhinavraj23** [comment]
@CloudyPadmal Yes I can continue my work on that issue and side by side work on other issues as well so that i can be more productive.If I just work on the capacitor issue which i don't even know how much time it will take then it will not make sense.

**Comment by CloudyPadmal** [comment]
OK do whatever pleases you!
