### ISSUE TITLE
Multimeter UI lines confusing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#1163]
The multimeter central UI lines (horizontal and vertical) of the device give an impression of a separation that does not reflect the device actually and could confuse the user.
![image1](https://user-images.githubusercontent.com/1583873/42122349-ab4bca1a-7c40-11e8-800f-fbbe1df2b3b9.png)

Multimeters often have another UI, where the lines to indicate an area are separated and differently drawn. Please implement this similarly.

![220px-yx360trf sanwa](https://user-images.githubusercontent.com/1583873/42122387-52c02462-7c41-11e8-9659-9482a281ed0e.JPG)

**Comment by abhinavraj23** [comment]
![newui_mul](https://user-images.githubusercontent.com/32960257/42242596-0a3a9c7a-7f2c-11e8-8241-0351af7cc25e.png)
@CloudyPadmal @harsh-2711 @Vikum94 @Avjeet Have a look at this UI , I was thinking we could implement a UI based on it

**Comment by abhinavraj23** [comment]
If you guys feel any change is required or you have a better idea then please do comment :+1:

**Comment by CloudyPadmal** [comment]
Hello @abhinavraj23 , what is the knob design you have in mind?

**Comment by abhinavraj23** [comment]
@CloudyPadmal I have changed the knob design it is available in my PR #1115
