### ISSUE TITLE
Add units to capacitance measurement

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#1164]
**Actual Behaviour**

Currently the capacitors values are shown in the form of power of e (scientific form) 

**Expected Behaviour**

The capacitors should be shown with units such as pico farad or nano farad etc

**Steps to reproduce it**

Go to MultimeterAcitivity and change it.

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Also chop off the decimals to two places

**Comment by abhinavraj23** [comment]
Sure @CloudyPadmal :+1:
