### ISSUE TITLE
Size of Carousel Picker not proper for smaller screens

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1166]
**Actual Behaviour**

The size of the Carousel Picker in Logic Analyzer instrument decreases very much on small screen mobiles

**Expected Behaviour**

The size should remain uniform on all screens

**Steps to reproduce it**

Go to Logic Analyzer -> Observe Carousel Picker on different screen size mobiles

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@harsh-2711 I have a suggestion. What if we remove the "SELECT" option from that and have only the numerical values with 1 channel as default? Is it difficult to implement?

**Comment by harsh-2711** [comment]
No. It's not. @CloudyPadmal I will remove it.

**Comment by CloudyPadmal** [comment]
@harsh-2711 great!
