### ISSUE TITLE
SI units in Resistance measurement

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1173]
**Actual Behaviour**

In multimeter resistance, units are in words.

**Expected Behaviour**

They need to be in proper symbols. Greek letter Ohm instead of word "Ohms"

**Steps to reproduce it**

Measure resistance in multimeter

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@abhinavraj23

**Comment by abhinavraj23** [comment]
Sure @CloudyPadmal I will do it :+1:
