### ISSUE TITLE
Multimeter shows value for capacitance even if no capacitor is connected 

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#1188]
**Actual Behaviour**

Multimeter shows value for capacitance even if no capacitor is connected 

**Expected Behaviour**

Should should a null value

**Steps to reproduce it**
Go to scienceLab class and debiug it

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@abhinavraj23 this is not a valid task. Even if no capacitor is connected, there is track capacitance between PCB traces and PSLab is showing this. It will be different from device to device. There can never be a null value for capacitance.
