### ISSUE TITLE
Power Source UI Enhancement 

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-android#1193]
**Actual Behaviour**

The two buttons for fine tuning is above the textbox and is blocked when user "touches" any of the button.

**Expected Behaviour**

buttons should be placed below the textbox or anywhere whereby a user's touch will not block the user's view of the textbox of the respective control.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/11439405/42389686-b083377e-8173-11e8-94e9-aa78e1e9667e.png)

**Comment by thedevelopersanjeev** [comment]
I would like to work on this issue.

**Comment by cweitat** [comment]
@thedevelopersanjeev  please go ahead and show us what you have

**Comment by cweitat** [comment]
Some examples of design improvement is to change the font family to the one that is used throughout the app.

**Comment by woshikie** [comment]
Regarding font family, please also discuss with other developers on gitter

**Comment by thedevelopersanjeev** [comment]
Please review my changes @woshikie  @cweitat @CloudyPadmal
