### ISSUE TITLE
Reduction of main application icon sizes in landscape mode

### ISSUE THREAD

**Issue by jithinbp** [fossasia/pslab-android#120]
I tried out the app on a Xiaomi Redmi 3S, and the auto-detection is working great.
I would like to suggest a slight tweak regarding the grid icon sizes in landscape mode. They look needlessly massive on the 5" 720p display. A three column format might feel better than the two column one currently used
![screenshot_2017-05-16-19-54-44-742_org fossasia pslab](https://cloud.githubusercontent.com/assets/6078658/26139145/2554608e-3aec-11e7-9df8-47e6e1522b19.png)
![screenshot_2017-05-16-19-54-59-037_org fossasia pslab](https://cloud.githubusercontent.com/assets/6078658/26139146/255d0a86-3aec-11e7-81e7-8c6f6327c1a9.png)

**Comment by viveksb007** [comment]
@CloudyPadmal could you have a look at this too?

**Comment by CloudyPadmal** [comment]
Oh this looks terrible! Sure @viveksb007 ! I'll get into this!! 👍
