### ISSUE TITLE
Adding FAQs to the Help and Feedback section 

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#1201]
**Actual Behaviour**
Currently Help and Feedback section doesn't have anything.

**Expected Behaviour**
We can include some FAQs and our official e-mail id so that of the doubts are not solved through those FAQs one can contact through it.

**Steps to reproduce it**
Click on Help and Feedback from the side menu

**LogCat for the issue**
N/A

**Screenshots of the issue**
![screenshot_2018-07-09-10-57-14-568_org fossasia pslab](https://user-images.githubusercontent.com/34381723/42432434-220170e6-8368-11e8-9f17-4a0498c59fec.png)

**Would you like to work on the issue?**
Yes

**Comment by yatri1609** [comment]
@CloudyPadmal Can I work on this issue?

**Comment by cweitat** [comment]
Before implementing, find out the following:
1. Check and finalise what to include in the list of FAQs
2. Have a template for FAQs and answers
3. Structure and flow of the help section (e.g. simple few questions with accordion?)

**Comment by CloudyPadmal** [comment]
Yes you can @yatri1609 . Before getting started, please create a Google Doc and collect the data as @cweitat mentioned and share it in Gitter channel.

**Comment by yatri1609** [comment]
Surely @cweitat @CloudyPadmal

**Comment by cweitat** [comment]
#1213

**Comment by cweitat** [comment]
#1213

**Comment by cweitat** [comment]
fossasia/pslab-android#1213

**Comment by CloudyPadmal** [comment]
@yatri1609 I have added a comment. @abhinavraj23 @Avjeet @harsh-2711 @Vikum94 please review the doc and add your input

**Comment by yatri1609** [comment]
Yes @cweitat I'll start working on the layout
