### ISSUE TITLE
csv file not being created if permission is not given expilicitly

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#1202]
**Actual Behaviour**

For data loggingthe sensor activities are using csv looger which requires storage permission explicity if the storage permission is not there the file doe not get created. 

**Expected Behaviour**

Add permission dialog box to check if permission is given to the app for storing CSV file and if not request permission for the same from the app only.

**Steps to reproduce it**

CSVLogger-> check for persmission

**Would you like to work on the issue?**

Yes

**Comment by woshikie** [comment]
Does user have access to the CSV file? Else can we make do without writing to storage?

**Comment by Avjeet** [comment]
if we explicitly provide the permission for storage then only the file is being created else the file is not getting created

**Comment by Avjeet** [comment]
I am including the request for permission inside the app itself

**Comment by woshikie** [comment]
does the user have a choice of selecting if a "dump" file should be created?
