### ISSUE TITLE
Oscilloscope displaying incorrect readings

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-android#1203]
**Actual Behaviour**

Readings on the Oscilloscope is displaying incorrect readings

**Expected Behaviour**

The correct readings should be displayed 
- V+ = ~8v
- VR+ = ~6v
- V- = ~-8v
- VR- = ~-6v)

**Steps to reproduce it with Screenshots**

- Connect V+ to CH1
![image](https://user-images.githubusercontent.com/11439405/42466928-9c8ecf9e-83da-11e8-924f-71d3c4be94ac.png)
- Connect VR+ to CH1
![image](https://user-images.githubusercontent.com/11439405/42466939-a60620c2-83da-11e8-997f-20cf7ffbeacb.png)
- Connect V- to CH1
![image](https://user-images.githubusercontent.com/11439405/42466956-b918983e-83da-11e8-8c1a-ff67117a838d.png)
- Connect VR- to CH1
![image](https://user-images.githubusercontent.com/11439405/42466965-c0acc598-83da-11e8-873b-501d80295201.png)

**Comment by cweitat** [comment]
@Vikum94 please fix this asap

**Comment by woshikie** [comment]
@Vikum94 can we have a status report?
