### ISSUE TITLE
Build different apks for dev and master branches

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1206]
**Actual Behaviour**

In the APK branch, there is only one APK when the development branch is merged into master branch. This makes it harder to test development in development branch.

**Expected Behaviour**

Make different names for app releases in apk branch, e.g. app-dev-release-unsigned.apk and app-master-release-unsigned.apk

**Steps to reproduce it**

> Not applicable

**LogCat for the issue**

> Not applicable

**Screenshots of the issue**

> Not applicable

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please don't overwrite Readme and apk's of Master branch when merging dev branch (and the other way around).
