### ISSUE TITLE
Convert Help & Feedback section to FAQ

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1213]
**Actual Behaviour**
Currently help and feedback section sits together

**Expected Behaviour**
Feedback section should be removed from this section and renamed to FAQs

**Would you like to work on the issue?**
@yatri1609

**Comment by cweitat** [comment]
#1201

**Comment by cweitat** [comment]
#1214

**Comment by yatri1609** [comment]
Ya surely I would like to work on this ! Thanks @cweitat

**Comment by cweitat** [comment]
@CloudyPadmal help me to assign this issue. I can't seem to assign it to her

**Comment by CloudyPadmal** [comment]
@cweitat there seems to be an issue in assigning. @yatri1609 are you a member of https://github.com/fossasia ? When I try to add you to PSLab-Developers team, it says you are not a member of the organization. Can you please check and make a request if you are not to be a member?

**Comment by yatri1609** [comment]
@CloudyPadmal Ya I'll make a request to be a member

**Comment by cweitat** [comment]
@yatri1609 have you requested?

**Comment by yatri1609** [comment]
@cweitat Actually I'm not getting the join option when I open the FOSSASIA account on GitHub.
