### ISSUE TITLE
Merge Feedback section into Report Issues and rename

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1214]
**Actual Behaviour**
Report issues currently only shows form to report issue

**Expected Behaviour**
A dropdown for user to select to report issue or give feedback
Forms to report issue or give feedback should change accordingly
Report Issues should be renamed to "Feedback & Bugs"

**Would you like to work on the issue?**
@abhinavraj23

**Comment by cweitat** [comment]
Also try to change the form background to PSLab's red

**Comment by cweitat** [comment]
#1213

**Comment by abhinavraj23** [comment]
Sure @cweitat I will do it :+1:
