### ISSUE TITLE
only oscillscope open from wave generator

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#1227]
**Actual Behaviour**

Currently only oscillscope opens from wave generator on clicking view button

**Expected Behaviour**

The user should be able to other instruments like logic analyzer or multimeter on pressing view button.

**Steps to reproduce it**

Ideas required for this.

**Would you like to work on the issue?**

Yes

**Comment by Avjeet** [comment]
@CloudyPadmal @cweitat For selecting other instruments on pressing view button should I create a dialog box with the list of instruments or should I create carousel picker inside the button similar to one in the logic analyzer.

**Comment by cweitat** [comment]
What's the purpose of implementing this? Does the wave generator affects the values from other instruments other than the oscilloscope? If not, what is the purpose of this?

If you are saying to implement this for #1031, I still can consider.

**Comment by Avjeet** [comment]
@cweitat Yeah the need is that currently to produce waves from wave generator user need to press view which open only oscilloscope and sometimes user need to open logic analyzer or may be multimete so I added a simple dialog with carousel picker so the user can choose the instrument he /she wants to open.
Without it first the user has to exit the wave generator and then open some other instrument.

**Comment by Avjeet** [comment]
@woshikie yes we can but Ithink there is no need as Power source as app bar which can have hamburger icon to open any instrument from the navigation panel.

**Comment by CloudyPadmal** [comment]
Thinking about this, the usage of wave generator is not to generate waves and view it from logic analyzer or oscilloscope but to output it to a design or an experiment done by a user. If a user need to view the output from wave generator they can explicitly browse to those viewing instruments and see.

**Comment by Avjeet** [comment]
@CloudyPadmal I know that and this Dialog box only prompts the user to open any other instrument if user just wants to proudce waves and not view it simply cancel the dialog box or press anywhere on the screen the dialog box will cancel but waves will still be produced

**Comment by cweitat** [comment]
Does Wave Generator affects the value for multimeter and logic analyzer as well? If yes then okay we can keep the dialog, else remove the instruments from the dialog box that has no effect.
