### ISSUE TITLE
Include app version in drawer menu

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1231]
**Actual Behaviour**
Currently, no app version is shown anywhere in the app.

**Expected Behaviour**
Show app version in the drawer menu below the last item in small and gray text.
This is to allow users to report for bugs and developers to track issues.

**Would you like to work on the issue?**
@yatri1609

**Comment by yatri1609** [comment]
Yes @cweitat I would like to take this issue up.

**Comment by cweitat** [comment]
@yatri1609 go ahead. will add you the assignees list once you are a member

**Comment by cweitat** [comment]
@yatri1609 any progress?

**Comment by yatri1609** [comment]
@cweitat I'm almost done will be sending a PR by tonight
