### ISSUE TITLE
Adding bottomsheet for the Barometer 

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#1245]
**Actual Behaviour**
Right now there is no bottomsheet for the Barometer instrument

**Expected Behaviour**
Bottomsheet guide and the schematic must be present for the barometer

**Steps to reproduce it**
Open Barometer and the slide up the bottomsheet

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes, but I would require @CloudyPadmal help for the schematic of the connections due to lack of device.

**Comment by yatri1609** [comment]
@CloudyPadmal Can you help me with the schematics?

**Comment by CloudyPadmal** [comment]
@yatri1609 BMP180 sensor would be suitable for this.

![BMP180](https://user-images.githubusercontent.com/14261304/43813611-0b6b142a-9ae4-11e8-8e29-b815f396b980.jpeg)

Refer to Lux meter instrument guide and connect SCL, SDA, VCC and GND pins accordingly

**Comment by yatri1609** [comment]
Ohk thanks !
