### ISSUE TITLE
Get app version number from build.gradle and set automatically

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1264]
**Actual Behaviour**
Currently devs need to update the app version manually from strings.xml

**Expected Behaviour**
To auto retrieve app version number and display in drawer menu
https://stackoverflow.com/questions/4616095/how-to-get-the-build-version-number-of-your-android-application

**Comment by yatri1609** [comment]
@cweitat Is this fine?
<img src = "https://user-images.githubusercontent.com/34381723/43032663-541438cc-8cda-11e8-822d-346f0600d55a.png" width = "300">
