### ISSUE TITLE
[Multimeter] Wrong Voltage Reading 

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-android#1266]
**Actual Behaviour**

Voltage Reading is reading twice the expected amount
Example
- VDD reads ~7v
- VR+ reads ~12v
- V+ reads ~ 18v

**Expected Behaviour**

- VDD should read ~3.3v
- VR+ should read ~6v
- V+ should read ~ 10v

**Steps to reproduce it**

Measure Voltage using Multimeter

**Would you like to work on the issue?**

@abhinavraj23, can you work on this?

**Comment by abhinavraj23** [comment]
@cweitat In which pins are these problems occurring?

**Comment by woshikie** [comment]
@abhinavraj23 CH1/2/3
