### ISSUE TITLE
[Wave Generator] PWM not generated

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-android#1267]
**Actual Behaviour**

https://github.com/fossasia/pslab-android/pull/1184#issuecomment-405326248

**Expected Behaviour**

User should be able to generate PWM with Wave Generator

**Steps to reproduce it**

Generate PWM with Wave Generator

**Screenshots of the issue**

https://github.com/fossasia/pslab-android/pull/1184#issuecomment-405326248

**Comment by cweitat** [comment]
@harsh-2711 @abhinavraj23 @Avjeet @CloudyPadmal @yatri1609 who can take this up?

**Comment by Avjeet** [comment]
@cweitat I can and I need someone with the latest PSLab device to test the waves.

**Comment by woshikie** [comment]
@Avjeet i have some v4s with me, I can test for you

**Comment by CloudyPadmal** [comment]
Fixed in #1837
