### ISSUE TITLE
Lux meter graph unstable

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1269]
**Actual Behaviour**
Currently the chart goes up and down. 

**Expected Behaviour**
The line chart should be plotted smoothly.

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/11439477/43034581-2c2846b2-8d09-11e8-8ed6-1e4952a6adaa.png" width="300" />

**Comment by harsh-2711** [comment]
@cweitat This issue is solved under PR #1234. I think changes will be reflected in the next app release.

**Comment by CloudyPadmal** [comment]
Fixed in #1234
