### ISSUE TITLE
Maps not showing anything

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1270]
**Actual Behaviour**
The maps at lux meter is showing a blank grid

**Expected Behaviour**
Maps should show up

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/11439477/43034685-5a858f68-8d0b-11e8-81a3-dad69a1b44b6.png" width="300" />

**Comment by CloudyPadmal** [comment]
Hi @cweitat , can you verify that if write permission to storage hasn't been given to app?

**Comment by cweitat** [comment]
@CloudyPadmal ah just gave the access. Can there be a prompt to ask user for storage permission when map is open?

**Comment by CloudyPadmal** [comment]
Yes @cweitat that needs to be implemented. I will send a PR right away! :D
