### ISSUE TITLE
No guide to see which axis is parallel to ground in Compass instrument

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1273]
**Actual Behaviour**

There is no guide to see which axis is parallel to the ground and thus selecting proper radio button becomes difficult for a new user

**Expected Behaviour**

There should be a guide with a screenshot showing all the three axis in the mobile

**Steps to reproduce it**

Download apk from PR #1271 -> Open `Compass` instrument -> Analyse

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by cweitat** [comment]
I was thinking to display just mini SVG using the corner of the existing space at bottom right hand corner of the compass, beside the bearings.
Something like this
![image](https://user-images.githubusercontent.com/11439477/43036718-b0a973f8-8d30-11e8-83c9-f04ff3fd014c.png)

Maybe your idea is better. You can show
