### ISSUE TITLE
Magnetic field indicators not working in Compass instrument

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1274]
**Actual Behaviour**

Magnetic Field indicators of all the three directions aren't working

**Expected Behaviour**

The indicators should work with exact accuracy

**Steps to reproduce it**

Download apk from PR #1271 -> Open `Compass` instrument -> Analyse

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by hrprt96** [comment]
anyone working on this issue?

**Comment by imrajat7** [comment]
@harsh-2711 Can I work on this issue?
