### ISSUE TITLE
[Multimeter] Incorrect Voltage SEN

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-android#1278]
**Actual Behaviour**

Voltage across SEN always reads 3.30 V, unless connected to GND, which then reads 0v

**Expected Behaviour**

Correct voltage should be read

**Steps to reproduce it**

Measure voltage across SEN

**Screenshots of the issue**
<img height="512px" src="https://user-images.githubusercontent.com/11439405/43037591-4f143432-8d41-11e8-83c9-aa57489d7ad5.png" />

**Comment by abhinavraj23** [comment]
@woshikie I think that is the property of SEN pin, it should show 3.30 , can you please confirm on it @CloudyPadmal .

**Comment by CloudyPadmal** [comment]
SEN pin is dedicated for resistance measurement and would not recommend to use it as a voltage measurement pin. It is pulled up to measure resistance across the pin and GND using a voltage divider method. Voltage at 3.3V is intended.
