### ISSUE TITLE
[Multimeter] Add readable Voltage range

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-android#1279]
**Actual Behaviour**

Users are not informed that only CH1 and CH2 can read a free range of voltage (from presumably ± ∞V).
CH3, SEN, CAP, AN8 can only read from 0V to 3.30V

**Expected Behaviour**

Users should be informed on the voltage range readable for all the pins

**Comment by abhinavraj23** [comment]
@woshikie Shall I add this information in the bottomsheet ?

**Comment by woshikie** [comment]
@abhinavraj23 do you think it will look nice?

**Comment by abhinavraj23** [comment]
@woshikie Yes I think we can put the information about range in the bottom-sheet :+1: , what do you think ?

**Comment by woshikie** [comment]
wouldn't there be too much information if you put it there?

**Comment by cweitat** [comment]
@abhinavraj23 just add the information to the bottom sheet. preferably near the top so is viewable
