### ISSUE TITLE
lux is always running 

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#1304]
**Actual Behaviour**

Currenlty lux meter is always fetching data from sensors and keeps running continously

**Expected Behaviour**

The lux meter should have play pause functionality so that the user can start fetching the lux data whenever it wants.

**Steps to reproduce it**

LuxMeterFragmentData -> create functionality to start sensor fetching on the play button click

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
May be we can combine this and #1303 ?

**Comment by Avjeet** [comment]
@CloudyPadmal In this issue I created the functionality so that the user can control the working of lux meter (i.e., start plotting graph and meter) like phyfox.
