### ISSUE TITLE
Release PSLab Android app in Fdroid

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1308]
**Actual Behaviour**

Package name changes to `pslab.org` #1209 was merged. Future fdroid deployments would not be possible with the older package name. 

**Expected Behaviour**

Have to make a request to Fdroid community to remove the current app and submit a new merge request with new package name

**Steps to reproduce it**

> Not applicable

**LogCat for the issue**

> Not applicable

**Screenshots of the issue**

> Not applicable

**Would you like to work on the issue?**

Yes. Similar changes need to be done at Google Play. 
CC: @mariobehling

**Comment by mariobehling** [comment]
Ok, Playstore is done. What about Fdroid? If not possible with older name, please submit new one.

**Comment by CloudyPadmal** [comment]
New app is released and the old one removed.
