### ISSUE TITLE
Screen not inactive when bottomsheet is opened

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1329]
**Actual Behaviour**

The screen that is visible behind the bottom sheet remains active.

**Expected Behaviour**

The screen behind bottomsheet should become inactive. Else the bottom sheet should close if the screen outside it is clicked.

**Steps to reproduce it**

Go to any instrument -> Open Bottom Sheet Guide -> Click on any button visible behind the bottom sheet

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by Avjeet** [comment]
@harsh-2711 yeah it is supposed to be inactive that is why I made the background darker in the first place👍

**Comment by abhinavraj23** [comment]
@Avjeet The issue states that the screen is not inactive

**Comment by CloudyPadmal** [comment]
By inactive screen do you mean freeze all the functions like real time plotting in oscilloscope etc?

**Comment by harsh-2711** [comment]
@CloudyPadmal Yes

**Comment by cweitat** [comment]
Don't think is good to stop all recording if user pulls up the bottom sheet by accident

**Comment by harsh-2711** [comment]
@cweitat Then I can implement the functionality to close the bottom sheet guide as soon as the user clicks outside the bottom sheet layout. Is it fine?

**Comment by cweitat** [comment]
@harsh-2711 sounds fine to me
