### ISSUE TITLE
Implement the barometer

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#1331]
**Actual Behaviour**

Currently the barometer can just be used with built in sensor available in very less devices

**Expected Behaviour**

The barometer should work with external sensors as well.

**Steps to reproduce it**

Go to instruments->barometer

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by yatri1609** [comment]
I don't know but @CloudyPadmal told me that it was working fine with external sensor too. @CloudyPadmal can you please confirm this?

**Comment by cweitat** [comment]
#1364
