### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by IzzySoft** [fossasia/pslab-android#1338]
**Actual Behaviour**

Two contradicting licenses are mentioned.

**Expected Behaviour**

A clear license.

**Steps to reproduce it**

Check the [LICENSE file](https://github.com/fossasia/pslab-android/blob/development/LICENSE) against the `README.md`

**LogCat for the issue**

n/a

**Screenshots of the issue**

n/a

**Would you like to work on the issue?**

I'd just like to know what license is the correct one: Apache-2.0 or GPL-3.0-only. While on it, and as background: Someone opened an [MR to include your app with F-Droid](https://gitlab.com/fdroid/fdroiddata/merge_requests/3531). That OK with you? I couldn't find a corresponding issue in your tracker here, so I thought to mention it.

PS: I just noticed you never increase `versionCode`. That's quite a show-stopper, as Android tells versions apart by this – and only versions with a higher `versionCode` as the one currently installed count as updates. Would you consider increasing that with each new version – at least starting with the very next? Only criterium is the new number must be higher (oh, and numeric/integer). How much is up to you – so you can just increase it by 1 for each new version, or "map" the `versionName` to an integer like `21002` for `v2.10.2`.

**Comment by CloudyPadmal** [comment]
Hi @IzzySoft ! Let me make the license change in the merge request in GitLab to Apache-2.0.

About the versions, we recently changed the whole package name from the old one. So I reset it to 1 and going to increment from there at each release. :)

**Comment by IzzySoft** [comment]
Ah! I see, package name changed. OK, then my fears concerning `versionCode` are unwarranted :wink: Now if you just mark the two comments at Gitlab as "resolved", some of the devs can take over for merging.

I'll leave this issue here open as the Readme [still states GPLv3](https://github.com/fossasia/pslab-android/blob/development/README.md#license). I'd suggest you close it once that line was fixed. Thanks for your fast reaction!

**Comment by CloudyPadmal** [comment]
Sure @IzzySoft ! Thank you very much for the review! :)

**Comment by IzzySoft** [comment]
My pleasure! Thanks for sharing your app and contributing to F-Droid!
