### ISSUE TITLE
Adjusting/Removal of gauge

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1349]
**Actual Behaviour**
Currently in barometer and lux meter we are having two different design meters. Main aim of app is to display and plot data. The meter currently, other than providing a nicer design, has no use function.

Max Lux is shouldn't be capped at 10000. Refer to this doc: [Maximum Readings](https://www.noao.edu/education/QLTkit/ACTIVITY_Documents/Safety/LightLevels_outdoor+indoor.pdf)
This also applies to barometer. Every sensor also have different Min and Max so it will be tedious to identify the range for each.
 The meter design across the app is inconsistent is also as well. Removal of meters also unclutter the screen.

**Expected Behaviour**
Removal of meter and display readings individually. A simple example text in bold such as "Current Reading: 13.1 Lux" at the top of the graph is prominent enough. 

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/11439477/43919410-5f755548-9c48-11e8-8fce-b5707b0101e9.png" width="500px"/>

**Comment by cweitat** [comment]
Opened to suggestions on how to proceed

**Comment by cweitat** [comment]
@Avjeet @abhinavraj23 @CloudyPadmal @harsh-2711 @yatri1609

**Comment by yatri1609** [comment]
@cweitat If we remove the meter, the UI will be similar to that it was before. Meters were added just to enhance the UI of the app.

**Comment by yatri1609** [comment]
@cweitat I think we should define a particular layout for all the sensors in common so that the app looks consistent and more appealing to the users.

**Comment by cweitat** [comment]
@yatri1609 was thinking of bar gauge compared to circle guage

**Comment by yatri1609** [comment]
@cweitat Maybe we can try that out, but the vertical bar gauge will take up more space I guess. What kind of bar gauge are you thinking of as I don't think I'm getting the same picture in my head as you have. If you have any picture can you share it?

**Comment by cweitat** [comment]
@yatri1609 horizontal, not vertical. Something like the image below but slight design change to fit the app and also probably removal of intervals in the middle and one colour throughout the bar.
![image](https://user-images.githubusercontent.com/11439477/43936207-29eb328e-9c8a-11e8-9c63-50d5e54d44fd.png)

**Comment by yatri1609** [comment]
Ohk I think we can do that @cweitat

**Comment by TheShivamGambhir** [comment]
@cweitat Can we just display the readings on the tip of the needle or on circumference of barometer, this will retain both the functionalities of an attractive ui plus is analogous of folding the horizontal barometer to a circular one.

**Comment by yatri1609** [comment]
@cweitat let's see what looks best but I guess gauge at the tool looks best

**Comment by yatri1609** [comment]
@cweitat I was thinking that rather than adding a horizontal gauge why dont we make a uniform meter gauge for all the sensors either like that of Barometer or that of LuxMeter? That will make the app uniform and also keep the UI attractive.

**Comment by yatri1609** [comment]
What do you all think about this ? @abhinavraj23 @Avjeet @harsh-2711 @CloudyPadmal

**Comment by yatri1609** [comment]
@cweitat what do you suggest about making the meter gauge same for all the UI ?

**Comment by cweitat** [comment]
@yatri1609 yes please change to the same meter gauge and remove the max number

**Comment by yatri1609** [comment]
@cweitat I would go with the Barometer type gauge is it fine?

**Comment by cweitat** [comment]
@yatri1609 yes but please remove the Min and Max because it varies between the devices

**Comment by yatri1609** [comment]
@cweitat yes I'll do that

**Comment by CloudyPadmal** [comment]
We have now standardized to use blue color gauge as the sensor meter
