### ISSUE TITLE
Accelerometer is always running

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1351]
**Actual Behaviour**

The accelerometer is running although the Activity is in the Paused state

**Expected Behaviour**

It should stop working when it is in Paused state and should again start working when resumed

**Steps to reproduce it**

Go to Accelerometer instrument -> Analyze

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
The instruments should - always - run. Pause is only relevant for "Record".
