### ISSUE TITLE
Samsung J7 devices are not supported

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1366]
**Actual Behaviour**

Mr. Cheng reported that the app is shown as incompatible with J7 models and when I checked with Google Play profile it says J7s are partially supported. Digging more into the issue there could be a problem in Manifest requirements or package size.

**Expected Behaviour**

App should try to support as much as possible devices.

**Steps to reproduce it**

Install using a J7

**LogCat for the issue**

> Unsupported
This device model is not supported in your app's APK manifest and hence users of this device model cannot install your app. 

**Screenshots of the issue**
![j7](https://user-images.githubusercontent.com/14261304/44016938-6a5cecba-9ef4-11e8-9381-4fce8b8aa8c1.png)

**Would you like to work on the issue?**
Yes

**Comment by abhinavraj23** [comment]
@CloudyPadmal I have a samsung J7 mobile but it works fine!

**Comment by CloudyPadmal** [comment]
Is it the supported version? There is no install button shown in other J7s!

**Comment by cweitat** [comment]
There's many types of J7 and depending on country and the year it came out. Would be good if @CloudyPadmal know what is the variant.

**Comment by ho-dor** [comment]
@CloudyPadmal,@abhinavraj23 , it is shown incompatible with my J8 2018 device as well

**Comment by CloudyPadmal** [comment]
With the new release [v2.0.8](https://github.com/fossasia/pslab-android/releases/tag/v2.0.8), compatible devices expanded from 4794 to 6829 supporting J7 and multiple other devices.

![Compatibility](https://user-images.githubusercontent.com/14261304/50321452-f62b2780-04f6-11e9-9c8d-32c20090dfbc.png)
