### ISSUE TITLE
No recording data functionality in Compass instrument

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1371]
**Actual Behaviour**

There is no data recording functionality in Compass instrument

**Expected Behaviour**

There should be a toolbar with data recording functionality

**Steps to reproduce it**

Analyze Compass instrument

**LogCat for the issue**

N/A

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

**Comment by Smit2010** [comment]
Is this issue still open? If not i would like to contribute.

**Comment by CloudyPadmal** [comment]
@Smit2010 yes you can work on this one.
