### ISSUE TITLE
[Multimeter] Readings are not shown continuously

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-android#1373]
**Actual Behaviour**

User has to tap on "read" to get readings

**Expected Behaviour**

Reading should be updated continuously

**Steps to reproduce it**

Enter multimeter

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/11439405/44296347-cc1aec00-a2ef-11e8-8d31-c1c52f6da291.png" height="256px">

**Comment by cweitat** [comment]
To implement continuous reading and a hold button like in the multimeter.
One way was to replace the read button with hold.

**Comment by Smit2010** [comment]
@cweitat @woshikie @abhinavraj23  I would like to work on this issue.

**Comment by abhinavraj23** [comment]
Yes @Smit2010 you can go forward with it. If you have any doubt or want to test the feature with the device then do let me know :+1:

**Comment by neel1998** [comment]
@CloudyPadmal  i think this can be closed now

**Comment by CloudyPadmal** [comment]
Fixed in #1767
