### ISSUE TITLE
Complete methods in Analog Section of Sciencelab.java

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#138]
List of methods that needs to be ported in Analog Section: 

- [ ] get_voltage
- [ ] voltmeter_autorange
- [ ] __autoSelectRange__ 
- [ ] __autoRangeScope__
- [ ] fetch_buffer
- [ ] clear_buffer
- [ ] fill_buffer
- [ ] start_streaming
- [ ] stop_streaming

Complete required methods list of Sciencelab is [here](https://docs.google.com/document/d/18fuJf2mbeZ-6EVktOpIjqVdnwt8QbIRY3cP0sD5ARBU/edit?usp=sharing). Needs to be ported from [sciencelab.py](https://github.com/fossasia/pslab-python/blob/development/PSL/sciencelab.py).

**Comment by asitava1998** [comment]
@viveksb007  I can do this part.
