### ISSUE TITLE
Improving the Splash screen

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#1383]
**Actual Behaviour**
Currently, the splash screen is having only the app icon.

**Expected Behaviour**
To improvise the design, the splash screen must have the name of the app or any animation to make it look better

**Steps to reproduce it**
Open the app.

**LogCat for the issue**
N/A

**Screenshots of the issue**
<img src = "https://user-images.githubusercontent.com/34381723/44444763-13f58800-a5fc-11e8-82d8-cc22de4e68df.png" width = 300>

**Would you like to work on the issue?**
Yes

**Comment by yatri1609** [comment]
@CloudyPadmal Can I go ahead with this ?

**Comment by cweitat** [comment]
@yatri1609 please add text PSLab below the icon with Roboto text.
