### ISSUE TITLE
Add in-built mic as option to use in Oscilloscope

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#1387]
Instead of an external device the oscilloscope should also be able to use the inbuilt mic of an Android phone as well as a plugged in mic. Please implement this option in instrument settings in a burger menu on the top right of the auto-hiding top bar (similar to Luxmeter).

**Comment by riyasingh1004** [comment]
Hi, I would like to work on this issue. I would like some guidance as well.

**Comment by ho-dor** [comment]
@CloudyPadmal @neel1998 we can achieve this using the MediaRecorder API in android ?

**Comment by CloudyPadmal** [comment]
@ho-dor do you like to work on it?

**Comment by ho-dor** [comment]
yes

**Comment by neel1998** [comment]
@ho-dor  do you have the board?

**Comment by ho-dor** [comment]
Why is the board needed for this ?

**Comment by neel1998** [comment]
What exactly are we suppose to do after we get the audio input?

**Comment by ho-dor** [comment]
From what I understand , I think audio waves on the oscilloscope chart

**Comment by neel1998** [comment]
Okay

**Comment by neel1998** [comment]
@CloudyPadmal @mariobehling  this is already working fine and i think can be closed
