### ISSUE TITLE
Wave Generator - Setting Sine Wave Channel to 3.1 kHz results in an output of 6.3 kHz

### ISSUE THREAD

**Issue by geekyjoyce72** [fossasia/pslab-android#1388]
**Actual Behaviour**

When the frequency of the Sine Wave Channel is set to 3.1 kHz, the actual measured output frequency on an external scope and frequency counter is ~6.5 kHz (not constant)

**Expected Behaviour**

The frequency output should be exactly that of the user's setting.

**Steps to reproduce it**

1. Use waveform generator application
2. Set sine channel to a specific frequency
3. Click view button
4. Measure output of sine wave with external oscilloscope and frequency counter

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable, refer to video in zip archive

[PSLab_WaveGen_Issue.zip](https://github.com/fossasia/pslab-android/files/2337368/PSLab_WaveGen_Issue.zip)

**Would you like to work on the issue?**

Unsure. Need time to understand PSLab more

**Comment by cweitat** [comment]
@CloudyPadmal please have a look at this.

**Comment by nsurampu** [comment]
If no one's working on this, I would like to go ahead and give this a try.

**Comment by ho-dor** [comment]
@neel1998 I am working on this. Thanks.

**Comment by ho-dor** [comment]
@neel1998 @CloudyPadmal @mariobehling @cweitat can you confirm this issue still exists ? On my device, it is working fine . 3.1 khz shows 3.1 khz wave

**Comment by neel1998** [comment]
I don't have an actual oscilloscope so can't confirm the generated wave frequency

**Comment by geekyjoyce72** [comment]
@ho-dor is this a app or firmware related thing? I'm not exactly sure how the app and firmware works at the moment, sorry

If anyone around (in Singapore that is) can pass me a device, I can measure the signal with my scope and frequency counter to veirfy

**Comment by cweitat** [comment]
@geekyjoyce72 I think i passed you a device previously? Or I remembered wrongly.

**Comment by geekyjoyce72** [comment]
@cweitat you had requested me to return you the device at the start of the year or end last year I think, so I have no devices on hand to test with

**Comment by cweitat** [comment]
@geekyjoyce72 follow up with you on Gitter

**Comment by geekyjoyce72** [comment]
Hi @ho-dor, I can confirm that this issue has been fixed.

Attached is the respective measurement on a digital oscilloscope
![IMG_20190701_225748](https://user-images.githubusercontent.com/13187059/60446533-1ed56c00-9c54-11e9-82ea-6d7227eaef69.jpg)
