### ISSUE TITLE
Add template for Issue and PR

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#139]
Add template for issue and PR as other projects like [susi_android](https://github.com/fossasia/susi_android/tree/development/.github),etc this gives a format to raise issues and submit a PR.

**Comment by CloudyPadmal** [comment]
Shall we create a format like the one in Susi? They all share the same format it seems! What do you think?

**Comment by viveksb007** [comment]
Our project isn't in that stage where we can use the same format. We can delay this for now.

**Comment by CloudyPadmal** [comment]
:+1:

**Comment by viveksb007** [comment]
@CloudyPadmal I think we should add this template as we have started working with UI and screenshots for describing the Issue and screenshot for showing the changes in PR would be great.
I am adding susi_android template. Is that okay with you?

**Comment by CloudyPadmal** [comment]
@viveksb007 yes that would be great! I checked their template and it will suit us well! :+1: :100:
