### ISSUE TITLE
Improve F-Droid listing

### ISSUE THREAD

**Issue by mueller-ma** [fossasia/pslab-android#1394]
I've seen this app on F-Droid, but it lacks screenshots, changelog and a translatable description there. It's pretty easy for you to add these information. Please have a look at [this example](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android) or at the [F-Droid docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) or [fastlane docs](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots).
After you have commited these files to your repo and tagged a new version, you need to remove the `Description` and `Summary` from the metadata file in the [F-Droid Data repo](https://gitlab.com/fdroid/fdroiddata).

**Comment by neel1998** [comment]
@ho-dor you can take this up if you want

**Comment by ho-dor** [comment]
@CloudyPadmal I read about how to do this . So , in the fastlane metadata folder , I have to create a fdroid folder and in that add desc and images ? Correct me if I am wrong.
