### ISSUE TITLE
Update splash screen 

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#1398]
**Actual Behaviour**
Currently there is no animation to the splash screen which doesn't look much attractive, and also add the hard-coded values to dimen file

**Expected Behaviour**
Add an animation to both logo and text of the splash screen and add hard-coded values to dimen.xml file

**Steps to reproduce it**
Open the app

**LogCat for the issue**
N/A

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
Yes

**Comment by hrprt96** [comment]
yes

**Comment by anujji1999** [comment]
Hello,
I am a beginner here.
Can I work on this issue?

**Comment by ho-dor** [comment]
can I work on this @yatri1609 ?

**Comment by anujji1999** [comment]
Is anyone working on it?
Or shall i start?

**Comment by ho-dor** [comment]
Sorry @anujji1999, I am working on it as nobody replied for 4 days.

**Comment by anujji1999** [comment]
Ok

**Comment by ho-dor** [comment]
I have solved this issue but I am having trouble in creating a PR on the development branch . When I am trying to create a PR, I am getting an error "There is nothing to compare.master and development branches are completely different commit histories".I forked the pslab-android repo and then made the change to it in my system and them pushed the changes to my forked repo master branch and now I am trying to create a PR to the development branch of fossasia repo. Can somebody please help @yatri1609, @wavicles @mariobehling @lorenzgerber @cweitat @woshikie @jithinbp.

**Comment by imrajat7** [comment]
@ho-dor you should commit your changes in the development branch of the forked repository and then after that PR to the project's development branch.

**Comment by ho-dor** [comment]
Thank You @imrajat7
