### ISSUE TITLE
Fourier Transform in Oscilloscope

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1415]
**Actual Behaviour**

Fourier transform analysis in PSLab oscilloscope is not working

**Expected Behaviour**

Frequency analysis of input signals need to be displayed correctly in the Fourier Transform section in oscilloscop

**Steps to reproduce it**

Check out Fourier transform analysis in oscilloscope with a sine wave or any kind of signal fed into oscilloscope channels

**LogCat for the issue**

> Not applicable

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

**Comment by neel1998** [comment]
Can someone guide me how can I start working on this issue. Thanks

**Comment by neel1998** [comment]
@CloudyPadmal  can you please elaborate on this issue and guide me how to go about it

**Comment by CloudyPadmal** [comment]
Hi, first go through the source code related to FFT in PSLab python repo and Android repos. If you're not familiar with Fourier Transform, I suggest you do some research on what it is and how to calculate FFT from a signal. It'll be helpful. Once all that is done, we have to implement Fourier Transform in Oscilloscope instrument.
