### ISSUE TITLE
App crashes while opening configurations in Accelerometer and Multimeter Activity

### ISSUE THREAD

**Issue by imrajat7** [fossasia/pslab-android#1416]
**Actual Behaviour**

In Accelerometer and Multimeter Activity the app get crashes on opening Configurations.

**Expected Behaviour**

On clicking it should open configurations of the respective activities.

**Steps to reproduce it**

1. Check logs to find the reason for the crash.
2. Make changes in the respective file code to fix it.

**LogCat for the issue**

![logcat](https://user-images.githubusercontent.com/42169801/47256317-c1b9d180-d49b-11e8-80c3-4ea1eeaf38d2.png)

**Screenshots of the issue**

![error1](https://user-images.githubusercontent.com/42169801/47256277-faa57680-d49a-11e8-9191-b830eca00656.png)
![error2](https://user-images.githubusercontent.com/42169801/47256279-fda06700-d49a-11e8-8621-7d100a8490b5.png)

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Fixed in #1419
