### ISSUE TITLE
Issue with the multimeter and the accelerometer. 

### ISSUE THREAD

**Issue by Circinusss** [fossasia/pslab-android#1431]
In the multimeter section when we try to access the settings of the multimeter the app crashes unexpectedly. This happens frequently not just a few times and is noticed across devices.
Also, the dial of the multimeter is not responsive, it takes 3-4 touches on the dial to rotate the dial.

A similar problem is noticed in the case of the accelerometer. Even when we try to access the settings of the accelerometer the app crashes the same way as in the case of the multimeter.

Besides these issues, the app is responsive and fluent no other issues noticed.

Below are the screenshots of the issue faced.
![screenshot_20181103-110605_li](https://user-images.githubusercontent.com/44549551/47948662-ebbec980-df5a-11e8-87d3-70504e1f0fd1.jpg)
![screenshot_20181103-111212_li](https://user-images.githubusercontent.com/44549551/47948663-ebbec980-df5a-11e8-8c16-0cb445a7f00c.jpg)

Hope the developer fix these soon.🙂

**Comment by imrajat7** [comment]
@Circinusss issues you mentioned above are already fixed.

**Comment by cweitat** [comment]
Issue has been fixed in latest release.
