### ISSUE TITLE
Delete redundant experiment resources

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1436]
**Actual Behaviour**

Application doesn't directly implement experiments similar to desktop app. All the resources are still in the source code

**Expected Behaviour**

These files need to be removed to make apk file size smaller.

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

**Comment by Mirnal1409** [comment]
Can I work on this

**Comment by CloudyPadmal** [comment]
Yes go ahead!

**Comment by CloudyPadmal** [comment]
@Mirnal1409 How is the progress with this issue?

**Comment by ananyaarun** [comment]
@CloudyPadmal , can i work on this issue ?

**Comment by cweitat** [comment]
@ananyaarun yes

**Comment by ho-dor** [comment]
@ananyaarun are you working on this ?

**Comment by ananyaarun** [comment]
@ho-dor , presently no anyone can take this up.

**Comment by harsh-2711** [comment]
@CloudyPadmal Can I start working on this issue? Its been up for long

**Comment by CloudyPadmal** [comment]
Yes @harsh-2711 :+1:
