### ISSUE TITLE
Many bugs in App

### ISSUE THREAD

**Issue by FelenAmvrosiy** [fossasia/pslab-android#1439]
**Actual Behaviour**

Many app crashes

**Expected Behaviour**

Many app crashes

**Steps to reproduce it**

Go to Accelerometer/Settings, Lux Meter/ View Map, Power Source , Multimeter/Settings, Oscilloscope/Timebase and Trigger/(Changing a value of trigger)

**Comment by cweitat** [comment]
This is because you don't have the device attached. 
Solution is to detect the user's activities and gives a toast to inform that the device is not connected.

**Comment by CloudyPadmal** [comment]
I tested these crash events mentioned in steps to reproduce and with the latest release on Play store doesn't seem to be crashing anything. Can you update the app to latest version and see if the crashes still persist in your device? Thanks! :+1:
