### ISSUE TITLE
Naming convention for Views & Widgets

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#144]
Since, each developer is working on different section of PSLab. It is important that a naming convention is followed to maintain uniformity in the code. For example one possible convention can be                                    
(viewtype)_(activity/fragment name)_(no. in the file).xml   like button_activity_oscilloscope.xml.

**Comment by viveksb007** [comment]
Yeah that okay, I have been using like this only for example spinner in logic analyser its something like **spinner_channel_select_la1**

**Comment by asitava1998** [comment]
I was thinking of adding a few points regarding the same in the README in the code practices & close the issue.

**Comment by viveksb007** [comment]
Yeah we can add a point for this, but its more of a code style. 
We can create CodeStyle.md in docs or add a code-style section in README.md itself. Create 2-3 points under code-style section in README.md for now.
We will move it under CodeStyle.md in docs when README.md is quite long.
