### ISSUE TITLE
"Like us on Facebook" not responding on AboutUs fragment if the Facebook app is not installed.

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1450]
**Actual Behaviour**

When I am clicking on Like us on Facebook, nothing is happening.

**Expected Behaviour**

When we click on "Like us on Facebook" under Connect with us, the Facebook page should open in the browser if fb app is not installed.

**Steps to reproduce it**

Click on About Us from the navigation bar and go under Connect with us and click on "Like us on Facebook" 

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Not Applicable

**Would you like to work on the issue?**

Yes. I will work on this issue.

**Comment by ho-dor** [comment]
The [https://github.com/medyo/android-about-page](url) is used to create this about page. And I can't make any changes in AboutPage.java class. So, what else can be the problem here if not in the class? Any suggestion?

**Comment by CloudyPadmal** [comment]
In my Sony device, this is working fine. Could you please check if your phone has data or connected to internet first?

**Comment by imrajat7** [comment]
working fine in my device also @ho-dor

**Comment by ho-dor** [comment]
@CloudyPadmal  all the other links are working fine but just this Facebook one is not in my Samsung J8 device

**Comment by cweitat** [comment]
Working fine for me Android 8.0 LGV20.

@ho-dor what do you see?

**Comment by ho-dor** [comment]
[https://youtu.be/bGGzMeMDe74](url)  take a look @CloudyPadmal @cweitat @imrajat7

**Comment by cweitat** [comment]
Do you have the facebook app installed?

**Comment by ho-dor** [comment]
No. But it should then open in the browser like the Twitter button is behaving

**Comment by cweitat** [comment]
So the issue should be updated to  **facebook link does not respond if fb app isn't installed**.

**Comment by ho-dor** [comment]
ok.

**Comment by cweitat** [comment]
So now you can proceed working on the issue.

**Comment by ho-dor** [comment]
But this is a issue in the external library that is used for this about page. So i will have to re-write the AboutPage class on my own and make changes in FB part  or is there any alternate way ?

**Comment by CloudyPadmal** [comment]
Mine it asks for a list of apps: FB, Chorme and Duck Duck Go. I'm not sure what's causing this issue with @ho-dor 's device

**Comment by ho-dor** [comment]
@CloudyPadmal this could be happening due to the same reason as to why the app is incompatible with Samsung J8 device.

**Comment by ho-dor** [comment]
I tried creating the AboutUs manually but the issue remained the same but the app is working on all the other devices that I have other than the Samsung J8. So, the issue is surely not there with the app or the code. That is why I am closing this issue. @CloudyPadmal @cweitat

**Comment by CloudyPadmal** [comment]
Thank you for your effort @ho-dor :+1:
