### ISSUE TITLE
PSLab Crash upon viewing logged Lux meter data

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1452]
**Actual Behaviour**
App crash whenever try to open

**Expected Behaviour**
Show the other page with the recorded data. or don't save the data.

**Steps to reproduce it**
Press record and quit the instrument without stopping. Return back to Lux meter and show the logged data
Upon clicking the chosen data set, it crashes.

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/11439477/49530907-20c09200-f8f4-11e8-8789-4d764a8bbb83.jpg" width="400px"/>

**Comment by CloudyPadmal** [comment]
Hi @cweitat ! I've tried this. Is this sequence right in the screen recording?
[LuxMeter.mp4.zip](https://github.com/fossasia/pslab-android/files/2649970/LuxMeter.mp4.zip)

**Comment by cweitat** [comment]
@CloudyPadmal  The first sequence is correct. 1s to 12s.

**Comment by cweitat** [comment]
I just send a feedback with the system log.
