### ISSUE TITLE
Recorded data of Lux meter does not equal to Playback

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1453]
**Actual Behaviour**

Playback data is shorter than the recorded one

**Expected Behaviour**

Both should be the same

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/11439477/49531330-0cc96000-f8f5-11e8-8aa7-d5f249883825.jpg" width="400px"/>

<img src="https://user-images.githubusercontent.com/11439477/49531334-0f2bba00-f8f5-11e8-9608-a3c453f470c2.jpg" width="400px"/>

**Comment by CloudyPadmal** [comment]
Recording is only done between the record button is pressed and the stop button is pressed. The graph view will keep on displaying sensor values.

**Comment by cweitat** [comment]
the 2nd image, which is the screenshot, shows that it is still recording. The stop button was pressed right after the screenshot was made. So the time should even be longer than the 4.8s. 

Playback which is the 1st image is less than 4.8s

**Comment by CloudyPadmal** [comment]
Record button was first pressed after 2s? Compare the slopes.

**Comment by cweitat** [comment]
both are reflecting the correct data at the time. slopes is also correct. 3s to 3.6s is upslope.

**Comment by cweitat** [comment]
@CloudyPadmal okay I got what you mean now. Thanks!
