### ISSUE TITLE
Unable to close guide on the Logic Analyzer

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1454]
**Actual Behaviour**

Currently I cant close the guide, I need to quit the app.

**Expected Behaviour**

Able to close the guide

**Steps to reproduce it**

Go to Logic Analyzer

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/11439477/49531709-ce807080-f8f5-11e8-89db-ba18c40acd34.jpg" />

**Comment by CloudyPadmal** [comment]
Does sliding down from red bar or clicking outside the guide are work?

**Comment by cweitat** [comment]
Nope. When the guide was slide up the background turns translucent. Clicking outside the guide made the buttons usable and not translucent anymore like the screenshot above. 

The guide can only be slide down after I had turn the channel selection.

Sliding up is also quite difficult.

**Comment by ho-dor** [comment]
can I work on this @cweitat ?

**Comment by ho-dor** [comment]
@cweitat  @CloudyPadmal  Similar issues are there with Barometer , Lux Meter , Sensors , Accelerometer , Compass and Power Source . The guides can't be opened from the bottom of the screen and I can confirm that issue is not just in the Samsung J8 device .

**Comment by cweitat** [comment]
@ho-dor okay you can work on this.

**Comment by harsh-2711** [comment]
@ho-dor It will happen in devices with no on-screen home panel. So, a default padding needs to be given so that the user can swipe up and down easily. You may proceed to work on this issue.
