### ISSUE TITLE
Not compatible 

### ISSUE THREAD

**Issue by ns200310** [fossasia/pslab-android#1456]
Hello contributors this app is not compatible with Android version 5.1.1 (lolipop) here are thexpected screenshots
![screenshot_2018-12-07-10-55-54](https://user-images.githubusercontent.com/33777572/49629274-bc462580-fa0e-11e8-8917-803ffefb807e.png)
![screenshot_2018-12-07-10-47-16](https://user-images.githubusercontent.com/33777572/49629278-c700ba80-fa0e-11e8-858d-51dae37cc68c.png)

**Comment by CloudyPadmal** [comment]
Hi! Is it on a tab that you're trying this?

**Comment by ns200310** [comment]
Yes

**Comment by ns200310** [comment]
It's in a Samsung Galaxy J max

**Comment by CloudyPadmal** [comment]
It's not supported because of the screen size (tab). Not related to API versioning.
