### ISSUE TITLE
Unable to open the guide from bottom of the screen of Accelerometer

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1459]
**Actual Behaviour**

When we try to re-open the guide from the bottom of the screen, it isn't opening

**Expected Behaviour**

When we slide up from the bottom of the screen, the guide should re-open

**Steps to reproduce it**

Open the Accelerometer and slide up from the bottom of the screen

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Not Applicable

**Would you like to work on the issue?**

Yes.

**Comment by cweitat** [comment]
If other instruments are also behaving the same, please open a separate issue for each.
