### ISSUE TITLE
Crashes when recording data on Accelerometer instrument and run Power Source

### ISSUE THREAD

**Issue by ezvezdov** [fossasia/pslab-android#1465]
**Actual Behaviour**

It crashes when I record data in the accelerometer and run power source.
Doesn't work graphics at "sensors" and multimeter (nothing happens when I run it)

**Expected Behaviour**
Multimeter should work. The application should not crash.

**Would you like to work on the issue?**

Yes
![screenshot_pslab_20181210-103438](https://user-images.githubusercontent.com/26501697/49717334-cf9ffd80-fc67-11e8-9247-b692c38c9724.png)

**Comment by CloudyPadmal** [comment]
Hello @ho-dor ! Would you like to take this up?

**Comment by CloudyPadmal** [comment]
The issue has some corrections to do.

Firstly, the views wouldn't respond if the PSLab device is not connected unless we're using inbuilt sensors such as in Lux Meter, Accelerometer etc. Multimeter requires the PSLab device to show any functionality.

Similarly all the external sensors need the PSLab device to interface them with the app.

Other issues are valid.

**Comment by ho-dor** [comment]
@CloudyPadmal yes . I will work on this . Thanks.

**Comment by CloudyPadmal** [comment]
Before you start, we have an abstract class for sensors `PSLabSensor` that contains all the templates needed to record and function. Please have a look at how luxmeter is designed and implement accelerometer in the same way. Thanks!

**Comment by CloudyPadmal** [comment]
Hello @ho-dor  ! Any update on this?

**Comment by ho-dor** [comment]
@CloudyPadmal I am having trouble with my internet connection. Will give you an update in a day or 2 . Thanks

**Comment by CloudyPadmal** [comment]
Well, accelerometer instrument already has a guide and you can use the content from there.

**Comment by ho-dor** [comment]
@CloudyPadmal A new menu will have to be created for Accelerometer similar to Lux meter. Also , there is no fragment for accelerometer like in the case of Lux meter which has LuxMeterDataFragment and a RealmObject like LuxData for accelerometer will be needed . Am I thinking right or wrong ? 0a

**Comment by CloudyPadmal** [comment]
Yes, we need a menu, data fragment and a settings fragment along with layout file.

**Comment by ho-dor** [comment]
@CloudyPadmal A new menu will have to be created for Accelerometer similar to Lux meter. Also , there is no fragment for accelerometer like in the case of Lux meter which has LuxMeterDataFragment and a RealmObject like LuxData for accelerometer will be needed . Am I thinking right or wrong ? 0a

**Comment by ho-dor** [comment]
@CloudyPadmal A new menu will have to be created for Accelerometer similar to Lux meter. Also , there is no fragment for accelerometer like in the case of Lux meter which has LuxMeterDataFragment and a RealmObject like LuxData for accelerometer will be needed . Am I thinking right or wrong ?

**Comment by ho-dor** [comment]
The Data fragment layout will have to be created for 3 axes and So the currently used recycler view has to be removed ? @CloudyPadmal

**Comment by CloudyPadmal** [comment]
Remove the scroll views and constraint the three graphs in the fixed view

**Comment by ho-dor** [comment]
@CloudyPadmal I have solved the issue partially . But the problem is that I have to convert LuxDataFragment from one graph to 3 graphs for accelerometer. So , as of now x-axis is working fine but how to convert it for 3 axes ?

**Comment by CloudyPadmal** [comment]
Only the `PSLabSensor` class is abstract. Other classes and fragments feel free to modify to have a working implementation. Send us a PR to review and we can progress from there.

**Comment by ho-dor** [comment]
I have solved this issue . I will be creating a PR by tomorrow.

**Comment by harsh-2711** [comment]
@ho-dor Any updates?
