### ISSUE TITLE
Unexpected Crash when recording at multimeter

### ISSUE THREAD

**Issue by KSNINJA** [fossasia/pslab-android#1466]
**Actual Behaviour**
In multimeter , unexpected crash occurs on pressing delete after pausing the recording .
Please state here what is currently happening.

**Expected Behaviour**
The app should work smoothly.
State here what the feature should enable the user to do.

**Steps to reproduce it**
Go to multimeter , click on record , then pause and then on delete .
Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Screenshots of the issue**
![screenshot2](https://user-images.githubusercontent.com/26023139/49743386-9e075080-fcc0-11e8-9f80-f0eeea853017.gif)

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
No , just a review

**Comment by ho-dor** [comment]
@CloudyPadmal @cweitat can I solve this in a similar way by using PSLabSensor abstract class ?

**Comment by CloudyPadmal** [comment]
`PSLabSensor` class is only for sensors. Other instruments need to be handled individually.

**Comment by ho-dor** [comment]
I will like to work on this then

**Comment by abhinavraj23** [comment]
@CloudyPadmal @ho-dor I would like to take up the issue if it's okay

**Comment by ho-dor** [comment]
@abhinavraj23 I want to learn the working of multimeter . I would like to help you in this if it's ok .

**Comment by ho-dor** [comment]
Did this issue require the pslab device to solve ? @abhinavraj23

**Comment by abhinavraj23** [comment]
No, I just added the condition that the recording will take place only when PSLab is connected which makes sense.
