### ISSUE TITLE
Add back button in Lux Meter

### ISSUE THREAD

**Issue by Princejhabak** [fossasia/pslab-android#1467]
**Actual Behaviour**

There is no back button in the toolbar of Lux Meter.

**Expected Behaviour**

User should be able to navigate to the main screen by clicking the back button in the toolbar

**Steps to reproduce it**
1. setDisplayHomeAsUpEnabled() to true
2. Add the case of android.R.id.home in the onOptionsItemSelected method

**Screenshots of the issue**

![whatsapp image 2018-12-11 at 18 50 23](https://user-images.githubusercontent.com/25201519/49803512-07956680-fd76-11e8-8b82-6e6b6dc2eedd.jpeg)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by CloudyPadmal** [comment]
We are adding burger menu instead of back button. Refer to #1443
