### ISSUE TITLE
Update gradle dependencies

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1473]
**Actual Behaviour**

Project library versions are somewhat outdated. Especially, the gradle and support libraries.

**Expected Behaviour**

Need to update the outdated libraries with newer ones and make the code base compatible with the new libraries

**Steps to reproduce it**

Check app.gradle file

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes or if any new developer wants to get familiar with the code base, please feel free to make a PR with a fix.

**Comment by Smit2010** [comment]
Yes, I want to work on this.
