### ISSUE TITLE
Incompatible with the popular Android devices

### ISSUE THREAD

**Issue by HiFromAjay** [fossasia/pslab-android#1487]
The app declares that it cannot function without the light sensor hardware. The light sensor is not available in popular Android devices currently in use such as Galaxy Grand Prime, Grand Prime Plus, J7 Neo, J5 Prime, J3-2016, J2, and J1 Ace. The Play store will filter the app based on this feature. Therefore, the app will not be available in the Play store on the aforementioned devices. You can make the light sensor feature optional by declaring android:required="false" in the Android manifest file <uses-feature android:name="android.hardware.sensor.light" android:required="true" />

**Comment by CloudyPadmal** [comment]
Nice finding @HiFromAjay ! :+1: Thank you for the input!
