### ISSUE TITLE
CH1 dropdown list pops up in Oscilloscope instrument

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1511]
**Actual Behaviour**

The dropdown of voltage setting in CH1 pops up when opening Oscilloscope instrument

**Expected Behaviour**

The drop down shouldn't pop up

**Steps to reproduce it**

Open Oscilloscope instrument -> Analyze

**LogCat for the issue**

NA

**Screenshots of the issue**

![oscilloscope_issue](https://user-images.githubusercontent.com/32356267/50382085-24f2fa80-06bd-11e9-8d9c-7837b0eee71c.jpg)

**Would you like to work on the issue?**

Yes

**Comment by cweitat** [comment]
any updates on this?
