### ISSUE TITLE
Update README of permissions needed in the app and reason

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1516]
**Actual Behaviour**
Currently the README is not showing what permissions are needed and explaining it

**Expected Behaviour**

Permissions required and of explanation why it is needed in the README.

**Comment by Sjsingh101** [comment]
can i start working on this issue

**Comment by cweitat** [comment]
@Sjsingh101 yes

**Comment by Sjsingh101** [comment]
@cweitat  could you please review this
