### ISSUE TITLE
Unstable oscilloscope readings

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1518]
**Actual Behaviour**
The oscilloscope reading are not stable. The readings jump around especially when the flashing frequency becomes high or if time base goes up.

**Expected Behaviour**
readings should be smooth and not stuck

**Steps to reproduce it**
Do a simple experiment of flickering LED with wave generator

**Screenshots of the issue**
![pslaboscilloscope](https://user-images.githubusercontent.com/11439477/50604383-bb16f400-0ef9-11e9-8067-3c713cd3ccae.gif)

**Comment by cweitat** [comment]
Similar to #1389

**Comment by geekyjoyce72** [comment]
Why not I look into it? Do you have actual hardware samples on hand?

**Comment by cweitat** [comment]
https://docs.google.com/document/d/1MJ8MnqumBS0ZbtPb2n0we-QWOodeTaVfiBo8jkOKfSQ/edit
try with this experiment but with the Android app

**Comment by ho-dor** [comment]
@neel1998 I will have a go at this one. Thanks.

**Comment by neel1998** [comment]
@ho-dor sure go ahead. But first make sure this issue still exists

**Comment by ho-dor** [comment]
Yup. We also need to figure out whether #1388 exists or not.

**Comment by cweitat** [comment]
@ho-dor try to do the experiment from the link I gave above. It's the closest one that I can find. Else you can just do what I mentioned in the issue above

**Comment by ho-dor** [comment]
@cweitat I am unable to re-generate this issue with frequency above 4000 and maximum timebase possible. Can you try once this expt , I think this issue doesn't exist anymore maybe.

**Comment by ho-dor** [comment]
Works perfectly for me oscilloscope even with max frequency and timebase

**Comment by neel1998** [comment]
@ho-dor i also thought that after the new changes in the oscilloscope this issue might have been solved. But let's wait for confirmation from @cweitat

**Comment by woshikie** [comment]
![image](https://user-images.githubusercontent.com/11439405/60293216-635dc080-9951-11e9-8318-5ae083c73b07.png)
Still looks slightly glitchy, especially towards the end.
When reading 2 channels at the same time, the app glitches out

**Comment by neel1998** [comment]
@woshikie can you please check with the latest app. The last gif you sent is not with the latest app version. Thanks

**Comment by neel1998** [comment]
@cweitat  @woshikie  Have you been able to check this issue with the latest app?

**Comment by neel1998** [comment]
@cweitat any updates on this?

**Comment by woshikie** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/11439405/62051470-0bfb8a80-b246-11e9-86bc-93f165190ca2.gif)

sorry for the delay. It's still buggy

**Comment by cweitat** [comment]
@neel1998 do you know the setup to acheive this readings?

**Comment by neel1998** [comment]
@cweitat sorry for the late reply. I have been able to get this reading. I will try to get it fixed by today. :innocent:
