### ISSUE TITLE
Add Tablet screen size support to Oscilloscope UI

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#152]
Make Oscilloscope UI to support tablet screen size ( 7''  and 10''). Planning to increase text sizes, spaces between widgets and margins.

![screenshot_1497114633](https://user-images.githubusercontent.com/26146675/27005281-f7a4edf6-4e38-11e7-87be-dfc9d5c82835.png)
Screenshot of Oscilloscope Activity running in 7'' tablet.

**Comment by akarshan96** [comment]
I have made some changes in Oscilloscope UI for tablets. The following is the screenshot for the same. 
@jithinbp @viveksb007 @asitava1998 @CloudyPadmal please suggest improvements.

![screenshot_1497166683](https://user-images.githubusercontent.com/26146675/27009261-12ade6d4-4ea7-11e7-9ca7-d5d730a86d39.png)'
![screenshot_1497167071](https://user-images.githubusercontent.com/26146675/27009294-eff2e31e-4ea7-11e7-9b55-63d7bcb85e29.png)
![screenshot_1497167001](https://user-images.githubusercontent.com/26146675/27009288-c20c3d42-4ea7-11e7-8d9b-bf46f617ee74.png)

**Comment by viveksb007** [comment]
@akarshan96 there is a lot of empty space in between. Could you try to increase graph size that would decrease panel size and you can also bring all those spinners in single line for large screens.

**Comment by akarshan96** [comment]
@viveksb007 Yeah, on it. 👍

**Comment by CloudyPadmal** [comment]
Do we need to add a round corners in the white panel? :thinking:

**Comment by asitava1998** [comment]
@akarshan96  We can take advantage of bigger screens to allocate more space to the graph. The side bar looks really large, we need to think of something since reducing its size means it won't cover the entire width. The font sizes can be increased slightly.

**Comment by akarshan96** [comment]
@asitava1998 I have reduced the size of both docks. Now the graph size is 3/4 of the height of the tablet and 7/8 of the with of the tablet (acording to the landscape mode). Let me know if they are required to be deacresed more. @CloudyPadmal I have remove boders from the lower dock, what you should I remove them?

![screenshot_1497195984](https://user-images.githubusercontent.com/26146675/27012328-45e3b60c-4eeb-11e7-8db6-3b96f9d2a4ec.png)
**Screenshot for Nexus 7'' tablet**

![screenshot_1497195237](https://user-images.githubusercontent.com/26146675/27012338-6bb5507a-4eeb-11e7-9da4-fde0c32961c1.png)

 **Screenshot for Nexus 10'' tablet**
