### ISSUE TITLE
Comma and dot are used in no particular order when the device locale is set to language with comma separator

### ISSUE THREAD

**Issue by Yahhi** [fossasia/pslab-android#1526]
**Actual Behaviour**

On the same screen, there can be numbers with dot and comma separators.  

**Expected Behaviour**

If a comma is used in locale, then all numbers are shown with a comma

**Steps to reproduce it**

Set phone language to Russian for example

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/4613133/50939815-6d693100-148f-11e9-95ad-ca63045552d5.png)

**Would you like to work on the issue?**

Yes

**Comment by Smit2010** [comment]
Can I contribute on this issue?

**Comment by Yahhi** [comment]
No. I already work on it

> Can I contribute on this issue?

**Comment by ho-dor** [comment]
@cloudyPadmal can I take this up ? The PR of this issue has been idle for a long time .

**Comment by CloudyPadmal** [comment]
Yes @ho-dor please do.
