### ISSUE TITLE
Suggestion :  Improvement of String.equals("xxx")

### ISSUE THREAD

**Issue by o0lwj0o** [fossasia/pslab-android#1527]
Hi,
I have found some usage of “String.equals("xxx")” in this project.

When using string.equals("a") ，it will get nullpointexception if string ==null.
The problem can be fixed by repalced with "a".equals(string) or Objects.equals(string,"a").

Detail websites and lines are listed below

47 55 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/peripherals/DACChannel.java

Best regards

**Comment by harsh-2711** [comment]
@o0lwj0o Thanks for the suggestion. Will surely look into it.

**Comment by neel1998** [comment]
@harsh-2711  i think this issue can be closed . Since I also find no need to make this changes
