### ISSUE TITLE
Improvement of sleep in loop

### ISSUE THREAD

**Issue by o0lwj0o** [fossasia/pslab-android#1532]
Recently, I found an interesting case in this project.
It has “Thread.sleep()” in a “while(true)” loop. I found some discussion in Stackoverflow and other website. It can be refactored by using a executor service.
https://ejrh.wordpress.com/2012/07/13/sleeping-in-loops-considered-harmful/
https://stackoverflow.com/questions/3535754/netbeans-java-new-hint-thread-sleep-called-in-loop

Detailed websites and lines:
102 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/sensors/SensorADS1115.java
110 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/sensors/SensorHMC5883L.java
162 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/sensors/Sx1276.java
284 305 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/sensors/BMP180.java
108 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/sensors/SHT21.java
124 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/sensors/SensorMPU6050.java
118 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/sensors/SensorMLX90614.java
187 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/sensors/SensorMPU925X.java
107 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/sensors/SensorBMP180.java
115 | https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/sensors/SensorTSL2561.java

Best regards

**Comment by mariobehling** [comment]
Thank you. We will take this into account in further development.
