### ISSUE TITLE
Oscilloscope crashes application

### ISSUE THREAD

**Issue by vincentmakes** [fossasia/pslab-android#1542]
**Actual Behaviour**

Oscilloscope causes application to crash

**Expected Behaviour**

Oscilloscope should actually launch

**Steps to reproduce it**

Issue on Nexus 7 with Android 6.0.1

1.Connect the pslab card
2.Open the Application
3.Launch Oscilloscope
Application crashes

**Comment by cweitat** [comment]
@vincentmkes hello, did you sent the crash log?

**Comment by vincentmkes** [comment]
Yes I did - if there is anything else I can do let me know.
I also had the same issue with Android 5.0 but can’t upgrade any further than that

**Comment by vincentmakes** [comment]
Is it closed because it is solved ?

**Comment by cweitat** [comment]
No other reports of it crashing and can't reproduce. Do try with other phones and if it still happens please reopen this issue.

**Comment by vincentmakes** [comment]
Other reviews on the Google Playstore are stating similar issue so that's disappointing you are ignoring it. I don't have any other Android hardware. How can I get a refund ? Thanks

**Comment by cweitat** [comment]
I saw that there was an update of the app version in the store. please try that out.
