### ISSUE TITLE
Add back Button in Baraometer and LUX Meter.

### ISSUE THREAD

**Issue by prajurock** [fossasia/pslab-android#1543]
**Actual Behaviour**
Add  Back button in Barometer and LUX Meter.

**Screenshots of the issue**
![whatsapp image 2019-02-10 at 1 53 38 pm 1](https://user-images.githubusercontent.com/26791135/52531462-e3391480-2d3b-11e9-9b3b-138d91f257a8.jpeg)
![whatsapp image 2019-02-10 at 1 53 38 pm](https://user-images.githubusercontent.com/26791135/52531463-e3391480-2d3b-11e9-91f6-c30119a925ab.jpeg)

**Environment**
PSlab branch-Latest Master
Device-Asus Zenfone Max M1 pro
OS version-API 21(Android 8.1)

**Would you like to work on the issue?**
Yes.

**Comment by CloudyPadmal** [comment]
Not a back button, we have to implement hamburger icon to include a navigation bar #1031
