### ISSUE TITLE
App crashes when recording button is pressed in Accelerometer

### ISSUE THREAD

**Issue by prajurock** [fossasia/pslab-android#1544]
**Actual Behaviour**

App crashes when recording button is pressed in Accelerometer

**Steps to reproduce it**
1.Open Accelerometer
2. Click on Recording Button.

**Screenshots of the issue**
![whatsapp video 2019-02-10 at 2 06 18 pm](https://user-images.githubusercontent.com/26791135/52531576-92c2b680-2d3d-11e9-9835-097255ea449e.gif)

**Would you like to work on the issue?**
Yes.

**Comment by abhinavraj23** [comment]
@prajurock This is the same issue as #1465 and a PR has also been sent by @ho-dor solving the issue, it is currently in the review process.

**Comment by prajurock** [comment]
OK. Thanks I will close this issue
