### ISSUE TITLE
Adding the '?' symbol in toolbar of all devices like in Compass device.

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1546]
**Actual Behaviour**
We have to slide the guide from the bottom which is not always visible to user and confusing for some users when they try to find the guide.

**Expected Behaviour**

Like in the Compass device , a '?' icon in toolbar will help users to easily open the guide in all devices.

**Steps to reproduce it**

Open Compass and click on '?' icon.

**Would you like to work on the issue?**

Yes.

**Comment by CloudyPadmal** [comment]
Once every instrument extends PSLabSensor, they will have "Show Guide" option in menu bar
