### ISSUE TITLE
No Back Arrow on action bar of LuxMeter and BaroMeter 

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1557]
**Actual Behaviour**

There is now Back arrow on the action bar of Lux Meter and Baro Meter, which inconsistent with other Meters' activity layout

**Expected Behaviour**

There should be a back arrow

**Steps to reproduce it**

Open Lux Meter or Baro Meter

**Screenshots of the issue**

![screenshot_20190220-122932](https://user-images.githubusercontent.com/32041242/53072613-ab845680-350b-11e9-9622-bf8748f7e32e.png)
![screenshot_20190220-122927](https://user-images.githubusercontent.com/32041242/53072614-ac1ced00-350b-11e9-9ba3-9f15e3c78168.png)

**Would you like to work on the issue?**

Yes

**Comment by ho-dor** [comment]
We don't have to add back button as @cloudypadmal has mentioned in #1543

**Comment by neel1998** [comment]
Okay...I didn't see that issue. I will close this issue
