### ISSUE TITLE
Clicking on "Open" on the snackbar after recording in Luxmeter should take to logged data activity rather than file manager

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1569]
**Actual Behaviour**

Nothing happens on clicking "Open" on the snackbar of Lux meter after recording
**Expected Behaviour**

should open logged data screen of lux meter
**Steps to reproduce it**

1. Recored data in Lux meter

**Would you like to work on the issue?**
yes

**Comment by ho-dor** [comment]
@neel1998  it takes me to the local storage where the data is saved. I think the issue can be modified and in place of going to the local storage , it should open the particular recording.
