### ISSUE TITLE
A start message for guiding new users

### ISSUE THREAD

**Issue by riyasingh1004** [fossasia/pslab-android#1577]
**Actual Behaviour**

No message appears on home screen when the user starts the application.

**Expected Behaviour**
A start message should appear to guide new users.

**Would you like to work on this issue**
Yes

**Comment by CloudyPadmal** [comment]
Hi, I see you're making lot of PRs related to wording and texts. It's great to have those kind of contributions but I would like to encourage more on actual code contribution.
