### ISSUE TITLE
To avoid confusion between triangular and Saw-Tooth wave

### ISSUE THREAD

**Issue by riyasingh1004** [fossasia/pslab-android#1581]
**Actual Behaviour**
In the wave generator guide saw-tooth sine waves are mentioned.
In the wave generator instrument screen of waves triangular waves are mentioned.
**Expected Behaviour**

In the show guide it must be shown that triangular and saw-tooth sine waves are same to avoid confusion

**Steps to reproduce it**
Updating the show guide of wave generator.

**Screenshots of the issue**

<img width="138" alt="2019-03-04 1" src="https://user-images.githubusercontent.com/43132209/53733446-053f3600-3ea7-11e9-8a80-b0405db46025.png">

<img width="137" alt="2019-03-04 2" src="https://user-images.githubusercontent.com/43132209/53733516-391a5b80-3ea7-11e9-910d-1e5e12669504.png">

**Would you like to work on the issue?**
Yes

**Comment by neel1998** [comment]
@riyasingh1004  kindly close this issue
