### ISSUE TITLE
Message to start or stop Lux Meter data recording

### ISSUE THREAD

**Issue by riyasingh1004** [fossasia/pslab-android#1587]
**Actual Behaviour**

No message appears for starting or stoping data recording In Lux Meter

**Expected Behaviour**

A message should appear to guide the user how to start or stop data recording. i.e by pressing on record and stop button respectively.

**Steps to reproduce it**

By adding a toast to Lux Meter activity
 
**Screenshot**

<img width="216" alt="screenshot_2019-03-05-22-48-25-83 1" src="https://user-images.githubusercontent.com/43132209/53824273-9262b780-3f99-11e9-9b97-097b7275eebb.png">

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Not needed at the moment. Please help to implement recording features in all instruments instead.
