### ISSUE TITLE
Home Screen message to tell about the pin layout

### ISSUE THREAD

**Issue by riyasingh1004** [fossasia/pslab-android#1594]
**Actual Behaviour**

There is no message to tell a new user where to see the pin layout

**Expected Behaviour**

A Toast message to tell them where to look for pin layout

**Would you like to work on the issue?**

yes

**Comment by riyasingh1004** [comment]
I think this will be better than implementing a start message for guiding new users

**Comment by neel1998** [comment]
@riyasingh1004  adding so many toast at every activity decrease the User experience, Since the pin layout option is in the action bar menu , there is no need to add such toast messages

**Comment by riyasingh1004** [comment]
I thought this Toast will replace the earlier one. This would. be more useful because in the beginning even I had to search for the pin layout. It would guide them where to look

**Comment by riyasingh1004** [comment]
Definitely all the Toast messages will not be implemented. I am just suggesting all the possibilities.@neel1998

**Comment by mariobehling** [comment]
Need to think about user communication, but this seems a bit too much at the moment.
