### ISSUE TITLE
Reset Button in power source

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1597]
**Actual Behaviour**

Currently there is no reset button, user has to move the meter to take to initial state
**Expected Behaviour**
There should be a button for each power source to reset it to -5 V

**Steps to reproduce it**
1. Open power source

**Screenshots of the issue**
![screenshot_20190307-112329](https://user-images.githubusercontent.com/32041242/53935297-c9d18100-40cb-11e9-8d6d-ae8c4822c1c3.png)

**Would you like to work on the issue?**
Yes

**Comment by CloudyPadmal** [comment]
It will get too crowded.
