### ISSUE TITLE
Feature Request: Altitude Meter

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1598]
**Actual Behaviour**
Currently no altitude meter

**Expected Behaviour**
Since there is barometer, we can calculate the altitude for those devices which supports barometer
**Would you like to work on the issue?**
Yes

@harsh-2711  @CloudyPadmal  @cweitat kindly share your view on this feature

**Comment by mariobehling** [comment]
Nice idea!

**Comment by neel1998** [comment]
@mariobehling  @CloudyPadmal  @harsh-2711 @abhinavraj23  @cweitat should i add the altitude information in the barometer activity or should there be a separate activity only for altitude meter. If we are adding altitude meter to the barometer activity, how should we display the graph of the altitude meter? Kindly shed some light on this matter

**Comment by neel1998** [comment]
@mariobehling  @CloudyPadmal  kindly share your views on how to add altitude meter. I have given two options in the previous comment.

**Comment by neel1998** [comment]
@CloudyPadmal  @abhinavraj23  please share some suggestion for this feature. Should it be included in barometer itself or there should be separate activity like other sensors.

**Comment by ho-dor** [comment]
@neel1998 what about this ?
