### ISSUE TITLE
No show logged data menu in accelerometer

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1601]
**Actual Behaviour**
There is no option to see logged data in accelerometer menu

**Expected Behaviour**
There should be option to show logged data since user is allowed to record data

**Screenshots of the issue**
![screenshot_20190308-025029](https://user-images.githubusercontent.com/32041242/53990142-99cac200-414d-11e9-9fe6-274056eb8814.png)

**Would you like to work on the issue?**
yes

**Comment by ho-dor** [comment]
@neel1998 a PR is already created which solves this issue . It is under review ,

**Comment by neel1998** [comment]
@ho-dor  thanks for drawing my attention. I will close this issue. Cheers!:)
