### ISSUE TITLE
No recording functionality in Power Source

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1602]
**Actual Behaviour**

No recording functionality in Power source

**Expected Behaviour**

Recording functionality should be added to power source

**Steps to reproduce it**

Open Power source

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

![toast_issue](https://user-images.githubusercontent.com/37077735/55240947-45b87800-51f7-11e9-8094-62caab3e9485.gif)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please add screenshots directly on Github. Thanks.
