### ISSUE TITLE
Unnecessary actionbar menu in FAQ and About us Activity

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1603]
**Actual Behaviour**
Currently the action bar menu in FAQ and about us activity have "show pin layout option"

**Expected Behaviour**

FAQ and About activity don't require option to show pin layout
**Steps to reproduce it**
Open FAQ / About Us activity

**Screenshots of the issue**
![screenshot_20190308-025800](https://user-images.githubusercontent.com/32041242/53990494-6c324880-414e-11e9-8ac3-8c77391bce11.png)
![screenshot_20190308-025754](https://user-images.githubusercontent.com/32041242/53990496-6c324880-414e-11e9-8ad1-06a6271b8727.png)

**Would you like to work on the issue?**
yes

**Comment by mariobehling** [comment]
Change not needed atm. Please help to focus on functionality issues of actual instruments as well as implementing data logging (recording in all instruments).
