### ISSUE TITLE
Unnecessary grey colored bar at the bottom of accelerometer

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1610]
**Actual Behaviour**
Unnecessary grey colored bar at the bottom of accelerometer

**Expected Behaviour**
the view should be removed

**Screenshots of the issue**
![20190308_180639_rmedited](https://user-images.githubusercontent.com/32041242/54029254-caead700-41cd-11e9-8a9c-d734d69421ce.jpg)

**Would you like to work on the issue?**
yes

**Comment by chanmol1999** [comment]
Are you still working on this?
Can I work on it.

**Comment by neel1998** [comment]
@chanmol1999  i was busy with my exams. Will file PR for all the pending issues soon. Sorry
