### ISSUE TITLE
Autoscan button squeezed in Sensors Activity

### ISSUE THREAD

**Issue by harshdevl** [fossasia/pslab-android#1616]
**Actual Behaviour**

Button width is squeezed while reformatting the project (120dp -> 20dp)

**Expected Behaviour**

Button width should be 120dp in Sensors Activity

**Steps to reproduce it**

Go to Sensors Activity -> Observe

**LogCat for the issue**

N/A

**Screenshots of the issue**

![Screenshot (31)](https://user-images.githubusercontent.com/44299483/54071241-dacaef80-428f-11e9-9a3c-c22c2f6118cd.png)

**Would you like to work on the issue?**

Yes

**Comment by ho-dor** [comment]
One PR #1541 is open for this which solves the error . It is under review .

**Comment by harshdevl** [comment]
I can't see any related issue in your PR. The issue that you are solving is #1465 which handles crash in Accelerometer and Power Source instrument.
