### ISSUE TITLE
Missing back button

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/pslab-android#1622]
**Actual Behaviour**

Their is no back button in instruments in case of Barometer and Lux meter.

**Expected Behaviour**

Their should be a navigating back button so that same interface is followed for all instruments.

**Steps to reproduce it**

change in activity or fragment.

**LogCat for the issue**

**Screenshots of the issue**

![Screenshot_20190319_004056](https://user-images.githubusercontent.com/42909612/54556929-03658e80-49e0-11e9-91c3-74e2fccf3ff9.jpg)
![Screenshot_20190319_004050](https://user-images.githubusercontent.com/42909612/54556930-03fe2500-49e0-11e9-80a1-3e2fc2f62e27.jpg)

**Would you like to work on the issue?**
Yes

**Comment by PalAditya** [comment]
Can I Work on this issue?

**Comment by chanmol1999** [comment]
No I am working on it and will soon do a pr .You can search for another issue:)

**Comment by neel1998** [comment]
@chanmol1999  we don't need a back button here as @CloudyPadmal  mentioned in #1543 Kindly check closed issues before raising a new one. You can close this one

**Comment by ho-dor** [comment]
Already a navigation menu has been added to these instruments .

**Comment by Smit2010** [comment]
Anybody working on this?

**Comment by neel1998** [comment]
@Smit2010  I guess we won't need a back button since consistent action bar is to be added to all the devices.

**Comment by Smit2010** [comment]
@neel1998 I guess @mariobehling suggested to implement the same back arrow to all the instruments rather than implementing menu.

**Comment by Smit2010** [comment]
@CloudyPadmal Is this required now? I would like to take this up.
