### ISSUE TITLE
Add card view for FAQ's page

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/pslab-android#1623]
**Actual Behaviour**

For a better user interface Faq activity should contain question questions in card view.Currently no such thing is there.

**Expected Behaviour**

Instead of simply showing up the faq a better ui of card view can be there.
**Steps to reproduce it**
change in xml file and its activity.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Currently not needed.
