### ISSUE TITLE
Barometer BM180 I2C produce random values

### ISSUE THREAD

**Issue by gdampf** [fossasia/pslab-android#1625]
**Actual Behaviour**

conected BMP180 based on GY-68 is detected in Sensors, but not in Barometer (shows not connected).
trying to measure produces very unstable data (Temperature show random values between 10 and 400 degree centigrade). But you can see, if you filter just the lowest values, that this raises, if you warm the sensor.

**Expected Behaviour**

More or less stable temperature, if not warming or cooling the sensor

**Steps to reproduce it**

Connect a BMP180 based on GY-68 (4-pin-connector: GND, VIN, SCL, SDA) to corresponding pins as described and auto-detect sensors, than choose BMP180 external and start measurement.

**Would you like to work on the issue?**

No -  too messy project.

Screenshot:
![IMG_2433](https://user-images.githubusercontent.com/22430204/54590680-e86b3c80-4a28-11e9-9f92-719a305bb867.JPG)

**Comment by kartikeysaran** [comment]
Should i work on this ? @CloudyPadmal @mariobehling

**Comment by CloudyPadmal** [comment]
Hello @kartikeysaran , without a device it would be challenging. But you can give it a try. 👍🏼

**Comment by kartikeysaran** [comment]
> Hello @kartikeysaran , without a device it would be challenging. But you can give it a try. 👍🏼

Sure ! :)

**Comment by marcnause** [comment]
Will be fixed in https://github.com/fossasia/pslab-android/pull/2527

**Comment by marcnause** [comment]
Fixed via https://github.com/fossasia/pslab-android/pull/2527
