### ISSUE TITLE
Oscilloscope: Clicking options on bottom area opens top red bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#1628]
The oscilloscope doesn't show the top bar of the phone. However when the user clicks options in the white bottom bar area the top bar shows up. Expected: top bar should not show up.

![Screenshot_2019-03-24-08-34-07-373_io pslab](https://user-images.githubusercontent.com/1583873/54873400-80de3400-4e10-11e9-99a2-5eea4b5cf747.png)

**Comment by ho-dor** [comment]
can I work on this @mariobehling ?

**Comment by neel1998** [comment]
@mariobehling  I guess this issue was solved in #1562 . This issue doesn't occur on my app. Kindly check once .
![20190324_102118](https://user-images.githubusercontent.com/32041242/54875138-b8ec7380-4e1e-11e9-9c53-4d13ab52b46e.gif)

**Comment by neel1998** [comment]
@mariobehling  this can be closed

**Comment by neel1998** [comment]
@CloudyPadmal  @mariobehling  @harsh-2711 @abhinavraj23  I think this issue is solved by #1556  and can be closed.

**Comment by ho-dor** [comment]
@mariobehling this can be solved . It is resolved by #1556

**Comment by CloudyPadmal** [comment]
This is fixed in #1556
