### ISSUE TITLE
Changing export data format in one device changes export data format for all devices

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1631]
**Actual Behaviour**
Changing export data format in one device changes export data format for all devices

**Expected Behaviour**
Export data format should not be changed for all devices

**Steps to reproduce it**

Change export data format in general settings menu, then change data format in some specific device. Data format will be changed in general settings as well

**Would you like to work on the issue?**
yes

**Comment by mariobehling** [comment]
Yes, I think this is as expected. Anyways, we probably should stick to CSV only.
