### ISSUE TITLE
Add functionality to continuously record data in compass

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1632]
**Actual Behaviour**
Currently record function in compass stores instantaneous value 

**Expected Behaviour**
Compass should record data until stop button is pressed , like other instruments

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Please provide an example of an existing app or mockups. So, we can better understand how you want to implement this feature.

**Comment by neel1998** [comment]
@mariobehling  currently the compass logs instantaneous values. I am suggesting implemet loggin function in compass just like barometer and lux meter, so user can start/stop the logging and can see the result for a time period not just for the given instance. Kindly share your thought. @CloudyPadmal @harsh-2711 @abhinavraj23  @cweitat please take a look at this issue. Thanks
