### ISSUE TITLE
Decimal degits in Default values in barometer not consistent

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1633]
**Actual Behaviour**
Max, min, average pressure values have different numbers of decimal degits

**Expected Behaviour**
Number of decimal digits should be consistent

**Screenshots of the issue**
![Screenshot_20190325-113941](https://user-images.githubusercontent.com/32041242/54898613-f7536280-4ef2-11e9-92cb-d926d4ca90d3.png)

**Would you like to work on the issue?**
Yes

**Comment by Smit2010** [comment]
@neel1998 Are you still working on this? If not, I would like to take this up.

**Comment by neel1998** [comment]
@Smit2010  sure. Since i am working on other issues, you can work on this one. Cheers!
