### ISSUE TITLE
Show message to user when any sensor is not present in device

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1634]
***Actual Behaviour**

Compass is not working on Samsung J8 device as it does not have any gyroscope .

**Expected Behaviour**
A toast or a dialog should appear to tell user that there is no gyroscope in this device so compass will not work.

**Steps to reproduce it**

On a Samsung J8 device , open compass

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

![Screenshot_20190325-114927_PSLab](https://user-images.githubusercontent.com/37077735/54899004-5e254b80-4ef4-11e9-9bc4-711e73553ae6.jpg)

**Would you like to work on the issue?**

Yes

**Comment by neel1998** [comment]
@ho-dor  i think compass uses built in magneto meter and not gyroscope. Kindly check once . @harsh-2711  since you worked on implementation of compass kindly check this once

**Comment by ho-dor** [comment]
Either way , we should give a message to user when any sensor isn't present . @neel1998  I can change gyroscope to any sensor

**Comment by neel1998** [comment]
@ho-dor i am not saying issue is wrong, i am just saying make sure you check availability of correct sensor. Cheers!
