### ISSUE TITLE
New Instrument : GyroScope

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1636]
**Actual Behaviour**
Currently the app has accelerometer and compass, though both may seem similar to gyroscope, functionality of gyroscope is quite different. Gyroscope provides absolute rotation of device, where accelerpmeter give changes in orientation , whereas compass uses magnetic sensors. Since almost every smart phone has gyroscope built in, this would be a good feature to include

**Would you like to work on the issue?**
Yes

**Comment by neel1998** [comment]
@mariobehling i think this would be a nice feature to include. If you agree i would start working on it. Thanks

**Comment by mariobehling** [comment]
Thanks, please provide a mockup or screenshot of an existing app, that has this feature. Please include Guide, top menu bar with burger menu etc.
