### ISSUE TITLE
Decimal digits in default values of lux meter inconsistent 

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1638]
**Actual Behaviour**

There are unequal number of decimal digits in default values of lux meter

**Expected Behaviour**

Consistent number of decimal digits should be there

**Steps to reproduce it**

Open Lux meter

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

![Screenshot_20190326-095753_PSLab](https://user-images.githubusercontent.com/37077735/54971848-78bbfb00-4fae-11e9-812c-4243ae2064cc.jpg)

**Would you like to work on the issue?**

Yes.

**Comment by Smit2010** [comment]
@ho-dor Are you still working on this? If not, I would like to take this up.

**Comment by ho-dor** [comment]
Ya sure . You can work on this . Thanks .

Regards,
Kunal Rai(BT16CSE058),
NATIONAL INSTITUTE OF TECHNOLOGY , UTTARAKHAND,
+91-7895780897
