### ISSUE TITLE
cache gradle directory in travis

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#164]
cache gradle directory in travis to speed up the build process.

**Comment by CloudyPadmal** [comment]
Currently it's downloading all the files from the beginning! This issue was addressed in fossasia-phimpme once! :)

**Comment by viveksb007** [comment]
Yes, open-event-android also caches gradle directories. We can adopt caching code for travis.yml directly from there.

**Comment by CloudyPadmal** [comment]
Let's enhance our one as well! :+1:

**Comment by viveksb007** [comment]
Fixed in #171
