### ISSUE TITLE
Change title bar of about us 

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/pslab-android#1640]
**Actual Behaviour**
Currently all the items in navigation drawer have their title names in their activity except ,about  page for which title of activity is PSlab.

**Expected Behaviour**

Also just like other activities it should be about instead of Ps Lab.

**Steps to reproduce it**
Open About page.

**LogCat for the issue**

**Screenshots of the issue**

![Screenshot_20190327_005856](https://user-images.githubusercontent.com/42909612/55027670-d3476c80-502b-11e9-82ee-99ff1e512d7c.jpg)

**Would you like to work on the issue?**
yes

**Comment by VishalBhosale5** [comment]
May I take up this issue please

**Comment by chanmol1999** [comment]
No I am working on this and will soon make pr.

**Comment by VishalBhosale5** [comment]
I got it, can I fix this.
