### ISSUE TITLE
Lux Meter Recording should not be allowed if there is no sensor in device

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1642]
**Actual Behaviour**

Even if there is no sensor , recording is allowed . Wastes memory.

**Expected Behaviour**

If no sensor , don't allow recording

**Steps to reproduce it**

If device doesn't have lux sensor then open lux meter and click recording.

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Not Applicable

**Would you like to work on the issue?**

Yes

**Comment by Smit2010** [comment]
@ho-dor Are you still working on this? If not, I would like to work on this.

**Comment by ho-dor** [comment]
I think I have created a PR for this . Thanks .

Regards,
Kunal Rai(BT16CSE058),
NATIONAL INSTITUTE OF TECHNOLOGY , UTTARAKHAND,
+91-7895780897

**Comment by ho-dor** [comment]
Closing this as this has been merged
