### ISSUE TITLE
Show logged data option in Barometer shows logged data from other instruments as well

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1645]
**Actual Behaviour**

Show logged data option in Barometer shows logged data from other instruments as well

**Expected Behaviour**

Show logged data option in Barometer should display only logged data of barometer

**Steps to reproduce it**

Record some data in barometer, select show logged data

**Screenshots of the issue**
![20190327_101041](https://user-images.githubusercontent.com/32041242/55050810-9bb2e180-5078-11e9-84f6-5628f767cb0a.gif)

**Would you like to work on the issue?**
yes

**Comment by mariobehling** [comment]
Thanks for this issue. We would like to become more efficient. Instead of making a single small issue for each instrument, please help to resolve this and add "Logged Data" to any missing instrument. Thanks.
