### ISSUE TITLE
Accelerometer Guide does not appear on sliding up

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1646]
**Actual Behaviour**

Accelerometer Guide does not appear on sliding up

**Expected Behaviour**

The guide should  be visible on sliding up

**Steps to reproduce it**

Go to acccelerometer and try opening guide by sliding up

**Would you like to work on the issue?**

yes

**Comment by ho-dor** [comment]
@neel1998 this is solved in #1541 . Thank You .

**Comment by neel1998** [comment]
Okay . Thanks for drawing my attention
