### ISSUE TITLE
Wrong information showed in Compass Instrument

### ISSUE THREAD

**Issue by Smit2010** [fossasia/pslab-android#1656]
**Actual Behaviour**
On long press of show guide button in Compass Instrument, "Get current axis" is displayed.

**Expected Behaviour**
 "Show guide" should be the message as like in Power Soucre instrument.

**Steps to reproduce it**
Go to compass instrument >> top-right button in toolbar >> long-press the button.

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/34190580/55133622-4e07a900-514c-11e9-8b2a-77c2a3c2fbf2.gif" width = 300px/>

**Would you like to work on the issue?**
Yes, I would like to work.

**Comment by neel1998** [comment]
@CloudyPadmal  @abhinavraj23  @harsh-2711  why do we have long press functionality in the first place. I don't see any practical use of it. Kindly inform me if I am missing something
