### ISSUE TITLE
Add Show guide option to instruments menu where it is missing

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1657]
**Actual Behaviour**
Currently there is no option for show guide in multimeter menu. Which is inconsistent with menu of barometer and lux meter and other instruments

**Expected Behaviour**
There should be a show guide menu

**Screenshots of the issue**
![Screenshot_20190328-124936](https://user-images.githubusercontent.com/32041242/55137946-51089680-5158-11e9-8006-4e9c4a5b996d.png)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Thanks for this issue. We would like to become more efficient. Instead of making a single small issue for each instrument, please help to resolve this and add the Guide to any missing instrument. Thanks.

**Comment by Smit2010** [comment]
@neel1998 Are you still working on this? If not, I would like to work on this.

**Comment by neel1998** [comment]
@Smit2010  sorry. I am working on this. Since i busy completing my proposal I could not make a PR. will file a PR soon.
