### ISSUE TITLE
No Location data stored in CSV even though "include location data" option is checked

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1662]
**Actual Behaviour**

Even if user has selected to add location data in .csv logs, the latitude and longitude columns have zero values in generated csv

**Expected Behaviour**
The current values of latitude and longitude should be included in csv when "include location data" option is checked.

**Steps to reproduce it**

Go to any instruments. (eg. Lux meter) select "include location data" option in configuration menu. Record some data. Check the generated .csv file

**Would you like to work on the issue?**
yes

**Comment by CloudyPadmal** [comment]
Hi, could you please check if this can be implemented with open street maps? We are not using Google Maps FYI.

**Comment by neel1998** [comment]
@CloudyPadmal  I will surely look into it. Will update you if I make ant progress. Thanks
