### ISSUE TITLE
Power source guide not opening by sliding up

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1664]
**Actual Behaviour**

Guide of power source is not opening from the bottom of the screen by sliding up. Guide does get opened by '?' Sign on taskbar but it should also open by sliding up like in the case of oscilloscope.

**Expected Behaviour**

On sliding up , guide should open from bottom of screen.

**Steps to reproduce it**

Open power source and slide up from bottom of the screen

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

![Screenshot_20190329-201833_PSLab](https://user-images.githubusercontent.com/37077735/55241032-77314380-51f7-11e9-8ee3-968f968138cb.jpg)

**Would you like to work on the issue?**

Yes

**Comment by neel1998** [comment]
@ho-dor  i think this is issue with all the activities which have scroll bars. Same as compass. Kindly resolve the issue for all. As @mariobehling suggested . Don't open separate issue for each instrument. Fix this and all similar when you fix the compass one. Also change compass to power source in the text of this issue. Cheers!

**Comment by ho-dor** [comment]
Thanks.  I will take a look.
