### ISSUE TITLE
Edit Text taking focus abruptly in Control Activity

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#167]
**Actual Behaviour**

When Control Activity is opened, Edit-Text takes Auto-Focus resulting in opening soft-keyboard abruptly.

**Expected Behaviour**

Control Activity should be opened fully without, Edit-Text coming into focus.

**Steps to reproduce it**

Open-Control Activity from Application Fragment

**LogCat for the issue**

None

**Screenshots of the issue**

![atfocus](https://user-images.githubusercontent.com/12713808/27138772-ea06c206-513e-11e7-960d-90944ffb72b1.png)

**Would you like to work on the issue?**

@asitava1998 Have a look at it. Please!

**Comment by asitava1998** [comment]
@viveksb007  Thanks for creating the issue. I will work on it.
