### ISSUE TITLE
App crashes when clicked on FAQ in Nav menu

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1670]
**Actual Behaviour**
App crashes when clicked on FAQ in Nav menu

**Expected Behaviour**
App should not crash

**Steps to reproduce it**
Click on FAQ in nav menu

**Would you like to work on the issue?**
Yes

**Comment by ho-dor** [comment]
@neel1998 it is just a one digit fix and as I solved the one for About us , I solved this one too . I have created a PR with both the crashes solved . Hope you don't mind . Cheers.

**Comment by neel1998** [comment]
yes no problem. Good job. Just mention this issue as well when you file the PR. :)

**Comment by ho-dor** [comment]
Yeah I am doing that right now .
