### ISSUE TITLE
No option to open logged data in compass

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1673]
**Actual Behaviour**

No option to open logged data in compass

**Expected Behaviour**

An option to view/open logged data should be there.

**Steps to reproduce it**

Open compass and record some data

**Screenshots of the issue**

![Screenshot_20190401-081832_PSLab](https://user-images.githubusercontent.com/37077735/55300907-90d0c600-5457-11e9-8f42-88f0e2048be8.jpg)

**Would you like to work on the issue?**
Yes.

**Comment by neel1998** [comment]
I am working on adding logged data option to all the instruments. I will cover compass as well

**Comment by neel1998** [comment]
#1645 #1635  will solve this one as well... I think this issue can be closed

**Comment by ho-dor** [comment]
Ok . Thanks .
