### ISSUE TITLE
New Feature : Add functionality to save graph views in gallery

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1674]
**Actual Behaviour**

Currently there is no functionality to save graphs

**Expected Behaviour**
User should be able to save the graph of some instance in gallery using a button click

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
yes

**Comment by neel1998** [comment]
@mariobehling  @CloudyPadmal  @cweitat  @harsh-2711 I need some suggestions for this feature. I am thinking of adding a button next to record button on the action bar for the instrument. upon clicking would capture the current state of the graph on the screen and store it as jpeg. Kindly share your views and suggestions

**Comment by ho-dor** [comment]
@neel1998 since we can already record the graph readings , what purpose will this function serve ? Thanks.

**Comment by neel1998** [comment]
@ho-dor  this feature will save the image of the graph in the device. So you can share it if you want. Unlike the csv it will be visual representation which much more comprehensive . Also this functionality has been added as a TODO list in the code as well.

**Comment by ho-dor** [comment]
@neel1998 when I think about the use that you have mentioned , I think the person who will receive this graph image will also need at what time in the experiment was the graph captured . What do you think ? Maybe a timer can be added when recording is started and hence we will receive the exact time during the experiment this was captured .

**Comment by neel1998** [comment]
Kindly explain the timer part again. The X-axis of the graph is anyways time(s). So we can easily understand the time that is passed since the experiment was started from the image of the graph.

**Comment by ho-dor** [comment]
What I am trying to say is that we can extend this functionality beyond the instruments with graph like Barometer reading for exact instant , adding a timer there and then share it might be useful.

**Comment by neel1998** [comment]
Most of the instruments have graphs and they are the only ones which requires logging in my opinion. Only compass and Multimeter dont have graphs. We can think something about them, once this basic functionality is working
