### ISSUE TITLE
Add the long press functionality to other instruments like in Power Source

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1687]
**Actual Behaviour**

No message appears on long press in other instruments like in Power Source "Show Guide".

**Expected Behaviour**

"Show Guide message should appear on long press of "Show Guide" item.

**Steps to reproduce it**

Go to Power Source and long press "?" symbol

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by neel1998** [comment]
@harsh-2711  @abhinavraj23  @CloudyPadmal  why do we have this functionality. Anyways "?" is self explanatory regarding the use of that button and also single click is more prompt response than a long press. User is like to click the "?" button before long pressing, and that would anyway open the guide.This is still my point of view.

**Comment by ho-dor** [comment]
@neel1998 I agree. Either we can remove this from all instruments or add it to all . Consistency was my motive when I opened this issue.

**Comment by neel1998** [comment]
@ho-dor  I understand your point. Let's wait for mentors opinion regarding this.
