### ISSUE TITLE
Playback data from SD Card

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1690]
**Actual Behaviour**

PSLab v6 has SD card feature to log recording from different instruments. These recording will be in raw values with no visualization.

**Expected Behaviour**

Android app needs to support a feature to let user play back these recorded data by importing them from SD card and display in a similar manner to logged data in current app.

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

New contributors can take up this issue and discuss with me how to integrate with the firmware

**Comment by ho-dor** [comment]
@CloudyPadmal an you please explain how to go about this . I am interested .

**Comment by neel1998** [comment]
@CloudyPadmal  i am also interested to work on this. Kindly guide how to go about it.

**Comment by Smit2010** [comment]
@CloudyPadmal I am keen on working on this. Please guide to get started.
