### ISSUE TITLE
High Light Tab strip in Control Activity

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#170]
**Actual Behaviour**

Tab-Strip doesn't indicate which tab is opened currently.

**Expected Behaviour**

Tab-strip should high-light the section of tab-strip showing which tab/fragment is opened currently.

**Steps to reproduce it**

Open Control Activity and switch between tabs, tab won't indicate which one is opened currently.

**LogCat for the issue**

None

**Screenshots of the issue**

![highlight_tabstrip](https://user-images.githubusercontent.com/12713808/27139921-e0a3b716-5141-11e7-81a3-1cc5e390e18a.png)

@asitava1998  Have a look at it. Please!

**Comment by asitava1998** [comment]
@viveksb007  I think it would be better if the active tab is slightly bulged from background or maybe the text colour is changed from white to any other colour. I will work on it but let us just fix how we want to represent a highlighted tab. What do you think the representation should be done

**Comment by viveksb007** [comment]
Changing color of text and image from white -> black,etc should be okay to show the high-light. Something like lower tab-strip of Paytm.
