### ISSUE TITLE
Implement save graph function for accelerometer

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1705]
**Actual Behaviour**
Currently save graph function is not implemented for accelerometer

**Expected Behaviour**
Simpleng the save graph function like barometer and lux meter

**Would you like to work on the issue?**
Yes

**Comment by CloudyPadmal** [comment]
May be we can implement a prototype in PSLabSensor class so that it will be available everywhere?

**Comment by neel1998** [comment]
I will check if that can be done.

**Comment by neel1998** [comment]
@CloudyPadmal in my opinion adding a prototype function in PSLabSensor for saveGraph() function would make the implementation a bit complex. Because all the instruments have different CSV formats. also to save the graph as .jpg we need to access linear layout of each instrument, doing all these through a common function would require to add many getters in the respective instrument activities. Kindly share your views.

**Comment by CloudyPadmal** [comment]
Ok, let's dig deep and see in the coming days. For now you can continue with this issue.
