### ISSUE TITLE
Implement import log from SD card functionality for accelerometer

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1706]
**Actual Behaviour**
Currently user can't add log for accelerometer from SD card

**Expected Behaviour**
Implement this functionality similar to barometer and lux meter

**Would you like to work on the issue?**
Yes

**Comment by CloudyPadmal** [comment]
May be we can implement a prototype in PSLabSensor class so that it will be available everywhere?

**Comment by neel1998** [comment]
This function needs to ne implemented in DataloggerActivity. So having a prototype in PSLabSensor won't help. Correct me if I am wrong.
