### ISSUE TITLE
Improvement: Gyroscope instrument is inconsistent

### ISSUE THREAD

**Issue by Smit2010** [fossasia/pslab-android#1716]
**Actual Behaviour**
Major functionalities are working fine but user guide, configurations and logged data is inconsistent.

**Expected Behaviour**
Alignment in configuration should be consistent with luxmeter and barometer, clicking map option in logged data should work, adding text in user guide and setting appropriate message and limit in Update time and High limit in configurations.

**Steps to reproduce it**
Open app -> open Gyroscope and observe its functionalities.

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/34190580/57710985-8e36d280-768b-11e9-9c42-fa12859f3717.jpeg" width="300px" /> <img src="https://user-images.githubusercontent.com/34190580/57711103-bf170780-768b-11e9-831b-a8df8324a13a.jpeg" width = "300px" /> <img src="https://user-images.githubusercontent.com/34190580/57711201-ebcb1f00-768b-11e9-8502-cadddca6cff5.gif" width="300px" />

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by neel1998** [comment]
@Smit2010  let me know if you find any trouble going through the implementation of gyroscope :)

**Comment by Smit2010** [comment]
Yeah sure. @neel1998
