### ISSUE TITLE
Servo motor control option

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1719]
**Actual Behaviour**

PSLab device can be used to control a robot arm set with 4 servo motors. Currently it is done by writing a Python script and there is no option in PSLab Android app to do so. This feature is requested by Marco

**Expected Behaviour**

Implement a tool giving an option to control servo motors using Android app.

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Add this to GSoC timeline. Developer who takes over this issue needs to understand how servo motors work and how to use PWM pins of PSLab device to control them.

**Comment by neel1998** [comment]
@CloudyPadmal  i have worked with servo motors earlier. Kindly elaborate a little bit further on this so that I can start working on this

**Comment by adityastic** [comment]
It was my minor to control servo's using android, haha what a coincidence. @neel1998 good luck

**Comment by CloudyPadmal** [comment]
We have a robot arm that moves with 4 servo motors. They are controlled with a code similar to
```python
from PSL import sciencelab
Robot = sciencelab.connect()
Robot.servo4(30,30,30,30)
```

Idea is to make it more user friendly and give user the ability to change these `30` values to different values so the arm will move differently. You get the idea. It'll be just calling a function but have to make it catchy

**Comment by adityastic** [comment]
@CloudyPadmal that would be great

**Comment by neel1998** [comment]
@CloudyPadmal  that's great

**Comment by adityastic** [comment]
@CloudyPadmal can you show us the real look of the robotic arm, I would love to create something exactly like it inside the app

**Comment by CloudyPadmal** [comment]
> @CloudyPadmal can you show us the real look of the robotic arm, I would love to create something exactly like it inside the app

This would be hard. Something like ![this](https://img.staticbg.com/thumb/large/oaupload/banggood/images/84/5E/a9559f3e-cdd7-403f-96a8-18d91a819306.jpg)

**Comment by neel1998** [comment]
@adityastic  instead of creating a arm like layout in the app , i was thinking of having a co troller for each four motor, which would make user able to move the servo as interested. It would look more neat

**Comment by CloudyPadmal** [comment]
Just some sliders would be good without a complicated UI

**Comment by neel1998** [comment]
@CloudyPadmal  i agree with you

**Comment by adityastic** [comment]
@CloudyPadmal got it

**Comment by adityastic** [comment]
> @adityastic instead of creating a arm like layout in the app , i was thinking of having a co troller for each four motor, which would make user able to move the servo as interested. It would look more neat

What about 4 dials? that would be neat for an initial interface

**Comment by neel1998** [comment]
@adityastic  i was also thinking something like that. Let's both create some mock ups and then decide which layout to opt

**Comment by adityastic** [comment]
> @adityastic i was also thinking something like that. Let's both create some mock ups and then decide which layout to opt

Sounds Great, Lets talk about it on the public channel on gitter

**Comment by neel1998** [comment]
@CloudyPadmal  i have made 2 mock ups for this functionality. Kindly share your views so that i can start working on it.
<img src = "https://user-images.githubusercontent.com/32041242/57874833-16091200-782f-11e9-84c9-3df93976d72d.png" width = "300"/>

<img src = "https://user-images.githubusercontent.com/32041242/57874835-16091200-782f-11e9-8c52-f0dfc7d620ae.png" width = "300" />

**Comment by CloudyPadmal** [comment]
First one looks more comfortable to slide :thinking:

**Comment by mariobehling** [comment]
As the numbers symbolize degrees in a circle, please also use a circle for the UI. Ensure that the degrees e.g. 90° have the correct position in the circle.

**Comment by mariobehling** [comment]
Furthermore give the option that uses can enter values as numbers if they click/tap on the number area.

**Comment by neel1998** [comment]
@mariobehling I will start working on it as per your suggestion

**Comment by adityastic** [comment]
@neel1998 looks goood
