### ISSUE TITLE
Gyroscope Guide not showing correct Information

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1722]
**Actual Behaviour**

The gyro guide doesn't show correct text below the image.

**Expected Behaviour**

The guide should show directions to use the instrument in guide.

**Steps to reproduce it**

Open Gyroscope guide.

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

![gyro_guide](https://user-images.githubusercontent.com/37077735/57795512-cc072a00-7763-11e9-8410-4aaf3333eb3f.jpg)

**Would you like to work on the issue?**

Yes.

**Comment by neel1998** [comment]
I think #1718  fixes this. @Smit2010 check once

**Comment by ho-dor** [comment]
@neel1998 I will close this as it is solved in #1718 .
