### ISSUE TITLE
Logged Data not showing graph in Gyroscope when sensor absent

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1723]
**Actual Behaviour**

When logged data is opened , it does not show the graph in devices with sensor absent.

**Expected Behaviour**

The graph should show either zero like when recorded or disable recording when sensor not present.

**Steps to reproduce it**

Open gyroscope with device not having the sensor and record some data and open it.

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

![Screenshot_20190515-215301_PSLab](https://user-images.githubusercontent.com/37077735/57795690-391abf80-7764-11e9-9bb7-68a2f954d719.jpg)

**Would you like to work on the issue?**

Yes

**Comment by ho-dor** [comment]
@CloudyPadmal  should we disable recording when sensor not present or add the graph ?

**Comment by neel1998** [comment]
@ho-dor kindly change the title of the issue to include that this issue occurs only when sensor is not present.

**Comment by ho-dor** [comment]
> @CloudyPadmal should we disable recording when sensor not present or add the graph ?

@CloudyPadmal @neel1998 what are your thoughts on this ?

**Comment by CloudyPadmal** [comment]
@ho-dor , disable the graph and give some visual output to user about the situation
