### ISSUE TITLE
Implement a 60 second timeline for four servos similar to a video editor

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#1734]
Servos should be able to run after each other at a certain time. Please implement a timeline as follows on the bottom of the screen as follows:

* With 4 rows similar to a video editor.
* The length of the timeline should be 60 seconds
* Users should be able to put in a number in a servo and then drag and drop the servo by tapping on the servo and dragging it into the timeline (similar to how you drag a video in a video editor timeline)
* Users should be able to drag the same servo several times into the timeline
* Implement a play, pause, stop, loop button

Compare to a video editor
![Screenshot from 2019-05-19 07-44-09](https://user-images.githubusercontent.com/1583873/57978334-cf244380-7a0b-11e9-97a2-04cf5ba46d97.png)

**Comment by neel1998** [comment]
@mariobehling  this seems an excellent feature. I will start working on it.
