### ISSUE TITLE
Adding the Instagram follow option in about us like in Neurolab App

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1735]
**Actual Behaviour**

RIght now there is no option to follow on instagram.

**Expected Behaviour**

An option to follow on instagram like present in neurolab app.

**Steps to reproduce it**

Open about us.

**LogCat for the issue**

N/A

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

It is a beginner's issue . If no one takes it up in a few days . I will do it.

**Comment by ho-dor** [comment]
@CloudyPadmal can you please add the beginner's tag to this

**Comment by mariobehling** [comment]
Not right app and IG following is not important currently for us.
