### ISSUE TITLE
UI orientation of robotic control

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1751]
1. UI Issue: Currently seeing this in the app. Able move the play pause controls beside the circular controls and extend the graph to eliminate gray space? 
2. Currently the servor moves in one direction only. Expected: Also, the instrument only functions in one direction. It should rotate accordingly in the landscape mode instead of fixing it to just one orientation. Please provide the option to show negative value e.g. -45 degrees. This should result in the servor moving left (instead of right).

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/11439477/58436307-438b7080-80f7-11e9-96da-13c1cb3a5c3e.png)

**Comment by neel1998** [comment]
@ho-dor  take a look at this issue
