### ISSUE TITLE
control_main_list_item has a few issues in the view

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#176]
**Actual Behaviour**

The `control_main_list_item.xml` ;
- Doesn't contain padding on left and right
- Text boxes allow letters other than numerical values
- Text boxes don't have a padding

**Expected Behaviour**

- Cardview needs a padding on the sides
- Text boxes can be allowed to have numerical values to avoid programming errors occurring in future when functionalities are to be implemented
- Text boxes should have a padding to display content not sticked to the border

**Steps to reproduce it**

- Open app
- Go to `Applications`
- Click on `Control` and go to main control section and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![a](https://user-images.githubusercontent.com/14261304/27187273-46eb6e68-51da-11e7-9bf5-34a1a4d2cb97.png)

**Would you like to work on the issue?**

Yes!

**Comment by asitava1998** [comment]
@CloudyPadmal Before you start, let me have a look at it. The view on this screen is distorted. What screen size are you using?

**Comment by CloudyPadmal** [comment]
Yes @asitava1998 there is a text box on the right side but it's not having enough space to be displayed. My screen is `480 x 800`!

**Comment by asitava1998** [comment]
@CloudyPadmal Can you create another issue with this screenshot and mention the details of the problem ? Then I can work on the screen compatibility.

**Comment by CloudyPadmal** [comment]
Sure @asitava1998 ! :+1:
