### ISSUE TITLE
Add feature to preview the wave to be generated from the wave generator

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1763]
**Actual Behaviour**
Currently user cant visually see the wave that will be generated unless it is opened in oscilloscope 

**Expected Behaviour**
Give user an option to preview the wave in wave generator itself

**Would you like to work on the issue?**
Yes.

**Comment by ho-dor** [comment]
@neel1998 this can be done without the board ? Should I work on this ?

**Comment by neel1998** [comment]
@ho-dor you can. But I don't know whether we need this feature or not. @CloudyPadmal can you please confirm . And if we need it please add this issue to Milestone 4

**Comment by CloudyPadmal** [comment]
Yes @neel1998 , Wave Generator UI is already pretty compact and it's a bit hard to figure out buttons too. Having a preview; I'm not sure if that's a good idea. We already giving user the shape of waveform (sine, triangular etc). Devices in market also don't provide such feature. So I'll close this for now.
