### ISSUE TITLE
Add feature to save timeline in Robotic Arm controller

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1766]
**Actual Behaviour**
Currently user has to set time line every time

**Expected Behaviour**
User should be able to save current time line and import it later

**Would you like to work on the issue?**
Yes

**Comment by ho-dor** [comment]
@neel1998 you working on this ?

**Comment by neel1998** [comment]
@ho-dor yes I have all the last few issues in my to-do list for this week.
