### ISSUE TITLE
Main Control window having screen compatibility issues

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#178]
**Actual Behaviour**

There is a text label at the right side of the `control_main_list_item.xml` but it is not provided with enough space on a `480 x 800` display

**Expected Behaviour**

The screen space should be allocated properly to display all the text fields

**Steps to reproduce it**
-    Open app
-   Go to `Applications`
-   Click on `Control` and go to main control section and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![Image](https://user-images.githubusercontent.com/14261304/27192011-375a6f6c-51e9-11e7-8b38-938b06a39ec8.png)

**Would you like to work on the issue?**

@asitava1998 will work on screen compatibility :+1:

**Comment by viveksb007** [comment]
Fixed in #181
