### ISSUE TITLE
Release PSLab v2.0.15

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1811]
**Actual Behaviour**

Development branch has enough commits and new features to make a new release

**Expected Behaviour**

Release v2.0.15 with version code 16

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@neel1998 can try.
Steps:
1. Increment version code and version in gradle file
2. Make a PR with the change
3. Create a merge request to master branch

**Comment by neel1998** [comment]
@CloudyPadmal  okay. Will do asap
