### ISSUE TITLE
Add Fourier Transform feature for CH3 and Built In MIC

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1817]
**Actual Behaviour**
Currently Fourier Transform option is only for CH1 and CH2.

**Expected Behaviour**
Add Fourier Transform option for CH3 and builtin MIC

**Would you like to work on the issue?**
Yes

**Comment by neel1998** [comment]
This one is not yet fixed entirely. Fourier Transform for Built In mic input is still to be implemented. Reopening this issue

**Comment by CloudyPadmal** [comment]
Don't add tag lines like "Fix #nnn" in PR body. They will automatically closes issues. Also I got a question. I guess the solution for this issue is something quiet similar to what you've done in #1799 addressing #1798. And this issue is opened for 3 days. Can we get a quick fix for this?

**Comment by neel1998** [comment]
No actually after converting all capture, audio buffer classes to one, it will be different to have fourier for Built in Mic Audio Input. Still i will make a PR by tonight
