### ISSUE TITLE
Refactor Code for Fourier Transform Class and AudioBufferTask

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1821]
**Actual Behaviour**
Currently there are separate classes to handle different number of channels

**Expected Behaviour**
Create single class to handle all the channels

**Would you like to work on the issue?**
Yes

**Comment by neel1998** [comment]
@CloudyPadmal  @mariobehling  add this to Milestone 5

**Comment by neel1998** [comment]
@mariobehling can this be added to milestone so we can keep track of the issues closed during this week. Thanks

**Comment by CloudyPadmal** [comment]
Done
