### ISSUE TITLE
XY plot feature doesn't work properly in oscilloscope

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1823]
**Actual Behaviour**
XY plot feature doesn't work properly in oscilloscope

**Expected Behaviour**
Implement the functionality similar to desktop app

**Would you like to work on the issue?**
Yes

**Comment by ho-dor** [comment]
Let me take a look at this . Will help me get acquainted with device working . @neel1998

**Comment by neel1998** [comment]
@ho-dor actually i have started working on this one. All new issues are under my this weeks plan. Maybe to get idea of oscilloscope you could review PRs or try figuring something out for #1518 #1388 . Thanks

**Comment by neel1998** [comment]
@cweitat  can you please add this one to milestone 5. Thanks
