### ISSUE TITLE
Logic Analyser Not working as expected

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1825]
**Actual Behaviour**
Currently logic analyser is giving weird outputs

**Expected Behaviour**
Logic analyser should give output similar to python library and conventional logic analyser

**Would you like to work on the issue?**
Yes

**Comment by CloudyPadmal** [comment]
Can post any screenshots of the output?

**Comment by neel1998** [comment]
![Screenshot_20190623-181107](https://user-images.githubusercontent.com/32041242/59976582-26599d00-95e4-11e9-8ab1-e147885798f4.png)
![Screenshot_20190623-181122](https://user-images.githubusercontent.com/32041242/59976583-26599d00-95e4-11e9-9c76-2e5624f98817.png)
