### ISSUE TITLE
Update APK generation and follow name conventions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#1847]
Please reduce the number of APKs generated and change the generation of the APK file as follows:

- pslab-dev-debug.apk
- pslab-dev-debug-fdroid.apk
- pslab-master-debug.apk
- pslab-master-debug-fdroid.apk
- pslab-master-unsigned.apk
- pslab-master-unsigned-fdroid.apk

**Comment by neel1998** [comment]
@mariobehling i don't think we can generate fdroid apk as of now , since fdroid version is yet not finalized and working.
