### ISSUE TITLE
Back Press not working properly in multiple instruments

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1858]
**Actual Behaviour**

infinite loop between logged data screen and lux meter activity.

**Expected Behaviour**

Main Screen should open up when back is pressed on lux meter activity.

**Steps to reproduce it**

Open logged data in luxmeter and press your device's back button.

**LogCat for the issue**

**Screenshots of the issue**

![20190711_200753](https://user-images.githubusercontent.com/37077735/61060647-7de76d80-a418-11e9-8c6b-cfe4feaf1703.gif)

**Would you like to work on the issue?**

Yes

**Comment by neel1998** [comment]
@ho-dor  this is happening with al the instruments i think. Change the title from just lux meter. I think same fix will work for all the instruments
