### ISSUE TITLE
Robotic Arm time line control buttons not visible

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1860]
**Actual Behaviour**
Currently play/pause/stop buttons are not visible

**Expected Behaviour**
Buttons should be visible

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/32041242/61067016-41217380-a424-11e9-9bba-5385a4053f8e.png" width = "500"/>

**Would you like to work on the issue?**
yes

**Comment by ho-dor** [comment]
![Screenshot_20190711-220808_PSLab](https://user-images.githubusercontent.com/37077735/61068816-8c3d8580-a428-11e9-8f6d-d655e34f00b9.jpg)

Visible on my device.

**Comment by neel1998** [comment]
@ho-dor  may be the size of the layouts are assigned properly from java, so it is looking different on different screen size. I will look into it
