### ISSUE TITLE
Twitter and Facebook links not working in About screen

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1864]
**Actual Behaviour**
Twitter and Facebook links not working in About screen

**Expected Behaviour**
Links should direct to respective pages

**Steps to reproduce it**
Click on facebook/twitter links in About page

**Screenshots of the issue**
![20190711_221749](https://user-images.githubusercontent.com/32041242/61069491-07ec0200-a42a-11e9-8c40-f33f2b73d4e3.gif)

**Would you like to work on the issue?**
Yes

**Comment by neel1998** [comment]
@mariobehling  can you please provide the links for the facebook and twitter accounts. Thanks

**Comment by CloudyPadmal** [comment]
@neel1998 haven't you followed the twitter account and fb page yet?

**Comment by neel1998** [comment]
fb : https://www.facebook.com/fossasia/?ref=br_rs
twitter : https://twitter.com/fossasia
Are these two links correct?

**Comment by CloudyPadmal** [comment]
Search PSLab and you'll see

**Comment by CloudyPadmal** [comment]
Twitter link is already in the readme. Always need guidance.

**Comment by neel1998** [comment]
Got it. Sorry for bothering you.
