### ISSUE TITLE
PSLab SD Card configuration

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1882]
**Actual Behaviour**

In order to use PSLab without using a device (say, mount on a weather station), a configuration file is needed to save in SD card so that the PSLab can read the setting from this file and do the processing and logging

**Expected Behaviour**

Have these properties in the config file in YAML format
- File Name (Optional)
- Instrument Name
- Logging Interval
- Parameters needed to be log (Depending on the instrument, Oscilloscope:: CH1, CH2 etc..)

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Issue for GSoC

**Comment by neel1998** [comment]
@CloudyPadmal user should be able to give start time and end time , right? To specify the period in which the data should be logged for given parameters.

**Comment by CloudyPadmal** [comment]
No. It will make things complicated.  Just add the configs mentioned in the issue body.

**Comment by neel1998** [comment]
What should be the unit of logging interval, minutes / hours / days? Should there be an option for that as well?

**Comment by CloudyPadmal** [comment]
Yea put an option
