### ISSUE TITLE
Release 2.0.17 app version

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1898]

**Comment by neel1998** [comment]
For this i ll have to make a PR to master branch, right?

**Comment by CloudyPadmal** [comment]
No. You've done this once. Update the version and version code in gradle files and make a PR. Two lines of code will take one minute.

**Comment by neel1998** [comment]
@CloudyPadmal sorry. My bad. I have classes now. Will make a PR within 2 hours
