### ISSUE TITLE
Master branch Playstore APKs not being built

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1901]
**Actual Behaviour**

Once a release is made (i.e. push to master), master apks should be generated and supply them to fastlane for Google Play store. Build is ending without proceeding to next steps from https://github.com/fossasia/pslab-android/blob/master/scripts/upload-apk.sh#L24

**Expected Behaviour**

Generate signed apks and fastlane sends them to Google Play

**Steps to reproduce it**

> Not available

**LogCat for the issue**

https://travis-ci.org/fossasia/pslab-android/builds/565944930#L1705

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@neel1998

**Comment by adityastic** [comment]
Directory needs to be changed, let me drop a pr in a minute

**Comment by neel1998** [comment]
@adityastic yes we are in apk directory. We need to use ../gradlew

**Comment by adityastic** [comment]
@neel1998 no xD that wont work. ( cd .. & ./gradlew ... ) is what you need to do.

**Comment by adityastic** [comment]
but for the case of debugging, let us store the aab for debug as well.

**Comment by neel1998** [comment]
@adityastic got it.

**Comment by CloudyPadmal** [comment]
Didn't get fixed

**Comment by CloudyPadmal** [comment]
Refer this https://github.com/fossasia/open-event-attendee-android/blob/development/scripts/update-apk.sh

**Comment by neel1998** [comment]
@adityastic i guess we are not giving the correct path for the aab.... @CloudyPadmal the problem is only occurring when trying to upload using fastlane, right?

**Comment by CloudyPadmal** [comment]
It doesn't even reach that far. Basic file handling errors

**Comment by neel1998** [comment]
@CloudyPadmal done. Please check. Hopefully, it should work as expected this time

**Comment by CloudyPadmal** [comment]
https://travis-ci.org/fossasia/pslab-android/builds/566339963#L1748

Still errors. I'll look into this issue

**Comment by CloudyPadmal** [comment]
Fixed
