### ISSUE TITLE
Add support for MQ 135 gas sensor

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1912]
**Actual Behaviour**
Currently no feature to get output of MQ 135 sensor

**Expected Behaviour**
Add support for MQ 135

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes

@CloudyPadmal since this is not a I2C sensor, I was thinking of adding it as a separate instrument like barometer and luxmeter. Does that sound okay?

**Comment by CloudyPadmal** [comment]
Yes, sounds good. I hope in the meantime you're checking out I2C issue.

**Comment by neel1998** [comment]
@CloudyPadmal  sure. I am onto it. Constantly communicating with Aakash as well regarding I2C
