### ISSUE TITLE
Add documentation for ESP communication and connection

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1925]
**Actual Behaviour**
Currently no docs available regarding ESP connection and communication

**Expected Behaviour**
Add docs with following details
1. How to attach ESP chip
2. How to set up the chip
3. How to communicate with the PSLab over Wifi

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes

**Comment by DARK-art108** [comment]
Can I work on this issue?

**Comment by adityastic** [comment]
> Can I work on this issue?

Go ahead

**Comment by DARK-art108** [comment]
The above docs should be added in Pocket science Lab documentation Repo under tutorials section?

**Comment by hariom9522** [comment]
can i work on this issue

**Comment by limitless-Sky** [comment]
@neel1998 can I work on this issues?

**Comment by AtigPurohit** [comment]
can i work on this issue?

**Comment by marcnause** [comment]
I think this ticket refers to the PSLab v5 board which is superseded by the v6 board now. ESP8266 support was never included in the firmware as far as  know. 

Support for the ESP-01 and the v6 board is developed in https://github.com/fossasia/pslab-android/issues/2509.

Can this issue be closed?
