### ISSUE TITLE
Navigation Drawer: Change sorting, move items, fix design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#1939]
1. Please change the navigation drawer as follows:
* Instruments
* Logged Data
  * Spacer here
* Connect Device
* Generate Config File
* Settings
  * Spacer here
* About Us
* Buy PSLab -> Link to https://pslab.io/shop/
* FAQ
* Share

2. Move the following items
* Add the link "Feedback and Bugs" to About us (compare to Neurolab)

3. FAQs
* Rename from FAQs to FAQ
* Fix spacing of the actual FAQ screen on the right hand side. There is not spacing to the right of the screen making it difficult to read.
![Screenshot_20190815_135151_io pslab](https://user-images.githubusercontent.com/1583873/63093100-2d59b780-bf64-11e9-895d-efcb9a5379a5.jpg)

**Comment by CloudyPadmal** [comment]
While addressing the issue, remove the 4th question (save experiments)
