### ISSUE TITLE
Oscilloscope main screen UI changes

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1947]
**Actual Behaviour**
Make following changes to Oscilloscope main screen UI
1. Add radion button for pslab mic and built in mic
2. Align spinners
3. add spacing between different sections
4. reduce the width of the left control panel

**Would you like to work on the issue?**
Yes

**Comment by rajput2122** [comment]
sir, I want to fix this issue. can you allow me to do the changes and contribute

**Comment by neel1998** [comment]
@rajput2122 sure. Go ahead. Ask any doubts related to code base on the bitter channel. Once the changes are done make a PR in specified format. Cheers!

**Comment by rajput2122** [comment]
thank you sir :)

**Comment by mariobehling** [comment]
@rajput2122 It it is difficult to dive into what we discussed in detail in meetings recently. Please choose an easier issue first. @neel1998 Please finalize the work you have stated in your scrum with this issue and make a PR as discussed in the last meeting. We dont have time to assign issues we discussed in detail in our meetings to others. Thanks.

**Comment by neel1998** [comment]
@mariobehling sure will make a PR asap

**Comment by rajput2122** [comment]
@mariobehling ok sir thanks for guidance
