### ISSUE TITLE
Add robotic arm screenshot with actual values and examples instead of everything 0

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#1953]
The robotic arm screenshot has everything showing 0. Add robotic arm screenshot with actual values and examples instead of everything 0.

**Comment by neel1998** [comment]
@mariobehling this can be solved by a newbie .. should I add beginner label or you want me to fix this.

**Comment by mariobehling** [comment]
Please also add an updated screenshot of the robotic arm screen.

**Comment by neel1998** [comment]
@mariobehling i have added the updated screen shot of robotic arm. Please check if that screen shot is okay. So this issue can be closed. Thanks

**Comment by neel1998** [comment]
@CloudyPadmal  can we close this?
