### ISSUE TITLE
Update readme file in apk branch

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1964]
**Actual Behaviour**

APK branch readme is outdated and it's not synced with development branch docs.

**Expected Behaviour**

This readme file needs to be updated with similar content to neurolab-android repo.
- QR codes for both Fdroid and Playstore links
- Redirect links
etc

**Steps to reproduce it**

Check out https://github.com/fossasia/pslab-android/blob/apk/README.md

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Beginner issue

**Comment by XDivergent** [comment]
Can I work on this Issue?

**Comment by neel1998** [comment]
@XDivergent sure go ahead.

**Comment by XDivergent** [comment]
> This readme file needs to be updated with similar content to neurolab-android repo.

Is that mean I need to delete most of the current contents and add only content similar to **neurolab-android repo** readme?

**Comment by CloudyPadmal** [comment]
@XDivergent yes correct. You'll have to delete those outdated content and make it similar to what neurolab-android repo has.

**Comment by XDivergent** [comment]
@CloudyPadmal Sir, Can I submitted PR after 20 sept. I am having exams till then.

**Comment by XDivergent** [comment]
<img width="1440" alt="Screenshot 2019-09-19 at 11 12 59 AM" src="https://user-images.githubusercontent.com/40258150/65216531-d731e400-dace-11e9-996b-42bd0aeed691.png">
@CloudyPadmal @neel1998

**Comment by XDivergent** [comment]
@fossasia/pslab-admins

**Comment by CloudyPadmal** [comment]
Hello @XDivergent looks good. Can make a PR?

**Comment by tusharr-98** [comment]
@CloudyPadmal is this issue still open?

**Comment by refactor-droidyy** [comment]
Hello @CloudyPadmal can I work on this?
