### ISSUE TITLE
Add degree symbol to wavegenerator

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#1967]
**Actual Behaviour**

Current UI has `deg` to indicate degrees

**Expected Behaviour**

Use correct symbol instead

**Steps to reproduce it**

Check out Wave generator UI

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Beginner issue

**Comment by XDivergent** [comment]
Can I work on this issue?

**Comment by XDivergent** [comment]
<img width="319" alt="Screenshot 2019-08-31 at 3 59 28 PM" src="https://user-images.githubusercontent.com/40258150/64063900-868a4200-cc18-11e9-85bd-0bf0098fa286.png">

what about space between value and symbol? shall I remove it or not?

**Comment by CloudyPadmal** [comment]
Hello @XDivergent , Let's remove the space. Once done, make a PR with the changes. Thanks.

**Comment by XDivergent** [comment]
@CloudyPadmal I remove the space between value and symbol but it would remove spaces for other symbols also like `Hz` and `%`.
So do you want to keep the spaces for other symbols or remove space for every symbol?
![Screenshot_1567329569](https://user-images.githubusercontent.com/40258150/64074367-d96f0280-ccc7-11e9-8ee4-3363dc6a0aeb.png)

**Comment by CloudyPadmal** [comment]
@XDivergent make changes only for the degree symbol
