### ISSUE TITLE
Improving the UI of generate config file activity

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1973]
**Actual Behaviour**

UI of generate config file doesn't look ordered. Lot of empty space on screen

**Expected Behaviour**

Checkboxes should be assigned, more screen space should be covered

**Steps to reproduce it**

Open Generate config file from nav bar.

**LogCat for the issue**

N/A

**Screenshots of the issue**

![Screenshot_20190909-121635_PSLab](https://user-images.githubusercontent.com/37077735/64509356-2886ea00-d2fd-11e9-8c48-95af93201960.jpg)

**Would you like to work on the issue?**
Yes

**Comment by kshitiz-kumar** [comment]
anyone working on this

**Comment by kshitiz-kumar** [comment]
If not I can work.

**Comment by kshitiz-kumar** [comment]
@neel1998  I would like to work on this.Please assign this to me.
