### ISSUE TITLE
Logged data not shown for gas sensor

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1984]
**Actual Behaviour**

No logged data shown after recording in gas sensor.

**Expected Behaviour**

Recorded data should be shown after recording.

**Steps to reproduce it**

Record data on gas sensor and open logged data.

**LogCat for the issue**

N/A

**Screenshots of the issue**

![20191002_143214](https://user-images.githubusercontent.com/37077735/66031874-e3cc2880-e521-11e9-9d68-983977b952d6.gif)

**Would you like to work on the issue?**

Yes.

**Comment by VIKAS9899** [comment]
Want to work on this issue, please assign it to VIKAS@9899

**Comment by CloudyPadmal** [comment]
@VIKAS9899 you can go ahead with a fix :+1:
