### ISSUE TITLE
Replace Toast with Snackbar

### ISSUE THREAD

**Issue by reckoner1429** [fossasia/pslab-android#1999]
**Actual Behaviour**

Currently brief messages at some places in the app use Toast to display brief messages to the user.

**Expected Behaviour**

According to android documentation - 
> Snackbar is now the preferred way to display brief, transient messages to the user.

[https://developer.android.com/training/snackbar/](url)

Therefore it would be better to replace the Toast with Snackbar, as it is possible that in the future the support for Toast might end.

**Steps to reproduce it**

- Toast is displayed when the user tries to exit the app
- Toast message is displayed when the user tires to use an option which requires PSLab device without actually connecting the PSLab device.

**LogCat for the issue**

N/A

**Screenshots of the issue**
![toast_issue1](https://user-images.githubusercontent.com/13999905/68525862-065d1880-02fc-11ea-9a45-f29df3996421.jpeg)

![toast_issue3](https://user-images.githubusercontent.com/13999905/68525868-1117ad80-02fc-11ea-9ce1-394c80d8a20b.jpeg)

![toast_issue4](https://user-images.githubusercontent.com/13999905/68525872-1bd24280-02fc-11ea-897a-231be5cab5a5.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by Darshpreet2000** [comment]
I want to work on this, Please assign me.
