### ISSUE TITLE
Menu button does not works

### ISSUE THREAD

**Issue by shreyansjain012** [fossasia/pslab-android#2004]
**Actual Behaviour**
When you click on **Menu** button nothing happens

**Expected Behaviour**
Not known

**Steps to reproduce it**
Do the following
1. Go to Navigation menu
2. Click on **Connect Device**
3. Click on **What is PSLab Device?**
4. Click on **Menu** Button on the top right corner
 

**Screenshots of the issue**
![WhatsApp Image 2019-11-14 at 1 34 01 PM](https://user-images.githubusercontent.com/45244830/68839078-f7081180-06e5-11ea-9918-8447020c8f99.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by dheerajkotwani** [comment]
@CloudyPadmal can you tell the expected behaviour on pressing the menu button there?

**Comment by dheerajkotwani** [comment]
@shreyansjain012 this page is the webpage of site "pslab.io" in mobile view. Pressing this button in mobile web view open navigation drawer of the webpage.

**Comment by amit6663** [comment]
can i work on this issue @shreyansjain012 ?

**Comment by shreyansjain012** [comment]
Yes please go ahead @amit6663
