### ISSUE TITLE
Letters of the Spinner are corrupted 

### ISSUE THREAD

**Issue by shreyansjain012** [fossasia/pslab-android#2005]
**Actual Behaviour**
Letters in the Spinner are not properly visible in **Generate Config File**  

**Expected Behaviour**
It should be readable

**Steps to reproduce it**
Go to
1. Navigation Menu
2. Click on **Generate Config File**
3. There will be a corrupted view in the spinner in front of **Time Interval**

**Screenshots of the issue**
![WhatsApp Image 2019-11-14 at 2 01 01 PM](https://user-images.githubusercontent.com/45244830/68839752-531f6580-06e7-11ea-9fdb-fa127b1c9591.jpeg)

**Would you like to work on the issue?**
Not right now. Due to College Exams

**Comment by dheerajkotwani** [comment]
I would like to work on this issue
