### ISSUE TITLE
'Show Logged Data' menu of Dust Sensor showing logged data from other sensors as well

### ISSUE THREAD

**Issue by reckoner1429** [fossasia/pslab-android#2009]
**Actual Behaviour**
On Opening the *Show Logged Data* Menu of Dust Sensor, the saved logs of all the sensors are being displayed

**Expected Behaviour**
On Opening the *Show Logged Data* Menu of Dust Sensor, only the logs that belong to the Dust Sensor must be displayed.

**Steps to reproduce it**
1. Click on the Dust Sensor Option from the Main Menu
2. Click on the 'Overflow Menu' button.
3. Click on 'Show Logged Data' Option.

**LogCat for the issue**
`Not Applicable`

**Screenshots of the issue**
![dust_sensor_log_issue](https://user-images.githubusercontent.com/13999905/69219313-9b7fcd00-0b98-11ea-86a7-6b387e5cf9dd.gif)

**Would you like to work on the issue?**
Yes, definitely!

**Comment by amit6663** [comment]
@asitava1998 can i work on this issue?

**Comment by reckoner1429** [comment]
@amit6663 This issue already has a fix. [#2023 ](https://github.com/fossasia/pslab-android/pull/2023)
