### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by chamodperera** [fossasia/pslab-android#2017]
### App crashes when recording oscilloscope

- **I opened oscilloscope in pslab**

![Screenshot_20191209-134848 1](https://user-images.githubusercontent.com/39716499/70419491-8c9b8480-1a8b-11ea-8c39-482ee1ebcdc9.png)

- **And I selected In-Built Mic**

![Screenshot_20191209-134827 1](https://user-images.githubusercontent.com/39716499/70419581-b94f9c00-1a8b-11ea-8459-47a359f4d8de.png)

- **when I try to record it the app crashes**

![Screenshot_20191209-134832 1](https://user-images.githubusercontent.com/39716499/70419775-2ebb6c80-1a8c-11ea-93cd-7f9d9216d191.png)

**Comment by reckoner1429** [comment]
Perhaps it could be some device specific issue, I tried to reproduce the bug but didn't get any results, the built in mic recording is working fine for me. Perhaps uploading the logcat of the crash would give more insights.

**Comment by ho-dor** [comment]
Same as #2081. @CloudyPadmal please verify or we can close this.

**Comment by CloudyPadmal** [comment]
Similar issue raised #2032
