### ISSUE TITLE
Crashing of the App while using the Logged Data

### ISSUE THREAD

**Issue by aryanguls** [fossasia/pslab-android#2019]
**Actual Behaviour**
On pressing the icon next to the delete option in the logged data(images provided below) the app crashes followed by complete blacking out of the phone screen.

**Steps to reproduce it**
1) Use any of the gadgets present in PSLab such as the oscilloscope or the lux meter.
2) Record the data observed by the instrument.
3) Go to the drop down menu and select the logged data option.
4) Press the icon to the left of the bin/delete icon.
5) The app crashes on doing so.

**Screenshots of the issue**
![Screenshot_2019-12-09-22-38-49-367_io pslab](https://user-images.githubusercontent.com/58459496/70457215-c1342e00-1ad5-11ea-81bf-5929e7bc3906.jpg)
![Screenshot_2019-12-09-22-38-49-367_io pslab_2](https://user-images.githubusercontent.com/58459496/70457484-41f32a00-1ad6-11ea-8b23-6b61093e12a8.jpg)
![Screenshot_2019-12-09-22-38-20-495_io pslab](https://user-images.githubusercontent.com/58459496/70457241-cdb88680-1ad5-11ea-9627-daa49c72fddc.jpg)
![Screenshot_2019-12-09-22-38-28-929_io pslab](https://user-images.githubusercontent.com/58459496/70457246-d01ae080-1ad5-11ea-9b81-7861c9494e95.jpg)

**Would you like to work on the issue?**
Yes if given the option I would like to work on the problem.

**Comment by amit6663** [comment]
can i work on this issue? @aryanguls

**Comment by ho-dor** [comment]
Unable to produce this crash @CloudyPadmal please verify or else we can close this

**Comment by CloudyPadmal** [comment]
Hello @aryanguls , can you please report the issue when the dialog shows when the app is crashed? It would help us see what's causing the issue. Thanks.

**Comment by cweitat** [comment]
No response, assume is working. Reopen if problem still persists
