### ISSUE TITLE
Alignment of "Time Interval" dropdown ;Addition of 'back' button and colour contrast of instrument screen

### ISSUE THREAD

**Issue by PicantaData** [fossasia/pslab-android#2020]
1. - The drop-down in the time interval in "Generate Config File" is not properly aligned initially.
      The dropdown containing sec, min, hr and day is not properly aligned.
2. - There is no back button anywhere on the 'sensors' screen. When we open the Sensors in 
       the instrument(home screen), there is no option to go back to the main menu on the UI.
3. - The color contrast of the home screen is not decent. The colors are too bright and it pains in 
      eyes. 

To Reproduce the first bug;
1. Go to the "Generate Config File" section in the navigation bar.
2. See error -->The dropdown corresponding to the "Time Interval". You will be able to see the dropdown not properly aligned

To Reproduce the second Bug;
1. Go to the "Sensors" in the instruments section.
2. See error-->There is no back button anywhere in that section to return back to the home screen.

**Screenshots**
![Bug-1](https://user-images.githubusercontent.com/58455626/70461235-3b68b080-1ade-11ea-8701-b5bdabe7c5d1.png)
![Bug-2](https://user-images.githubusercontent.com/58455626/70461237-3b68b080-1ade-11ea-86e2-395e6b75fdb5.png)
![Color contrast](https://user-images.githubusercontent.com/58455626/70461239-3c014700-1ade-11ea-9a84-07f1fc03b26c.png)

**Smartphone Info:**
|Device          |[Redmi Note-5 Pro]|
|Android Version|[Android 10]|

**Additional context**
Please choose a decent color contrast for the home screen.

**Would you like to work on the issue?**
 -[No]

**Comment by dheerajkotwani** [comment]
I would like to work on the issue
