### ISSUE TITLE
Soundmeter/Sonometer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2024]
Implement a Sonometer as an instrument. There are a number of examples of a Sonometer on the Playstore, e.g. here https://play.google.com/store/apps/details?id=app.tools.soundmeter.decibel.noisedetector. These can be used to understand the requirements.

**Comment by reckoner1429** [comment]
@mariobehling I am interested in implementing this. Should I wait for someone to assign this or just start working ?
