### ISSUE TITLE
clicking 'open' on the snackbar after recording data, opens logged dataset list of all sensors rather than the dataset list of that specific sensor

### ISSUE THREAD

**Issue by reckoner1429** [fossasia/pslab-android#2027]
**Actual Behaviour**
On clicking the 'Open' button on Snackbar after recording, opens the dataset list of all the sensors.
This issue occurs with **Power Source**, **Lux Meter**, **Accelerometer**, **Barometer**, **Compass**, **Gyroscope**, **Thermometer**, **Gas Sensor**, **Dust Sensor**

**Expected Behaviour**
On Clicking the 'Open' button on Snackbar after recording, should open the list of datasets of only the current sensor.

**Steps to reproduce it**
1. Start recording data in any of the above mentioned sensors
2. Stop recording data after a while, a Snackbar with 'OPEN' button pops up.
3. Click on the Open button.

**LogCat for the issue**
`Not Applicable`

**Screenshots of the issue**
![snackbar_open_issue_pic1](https://user-images.githubusercontent.com/13999905/70720934-c504c200-1d1a-11ea-94e0-79aebd1156ca.gif)
![snackbar_open_issue_2](https://user-images.githubusercontent.com/13999905/70720937-c6ce8580-1d1a-11ea-978f-d30d2c52f815.gif)
![snackbar_open_issue_3](https://user-images.githubusercontent.com/13999905/70720943-c7ffb280-1d1a-11ea-8e16-487ad3b99be7.gif)
![snackbar_open_issue_4](https://user-images.githubusercontent.com/13999905/70720945-c930df80-1d1a-11ea-9d42-f4067273fe4e.gif)
![snackbar_open_issue_5](https://user-images.githubusercontent.com/13999905/70720947-cafaa300-1d1a-11ea-97d0-0e4ba6a904c4.gif)
![snackbar_open_issue_6](https://user-images.githubusercontent.com/13999905/70720950-cc2bd000-1d1a-11ea-8ce2-edaa08a0de04.gif)
![snackbar_open_issue_7](https://user-images.githubusercontent.com/13999905/70720965-d3eb7480-1d1a-11ea-8110-7570546aa24f.gif)
![snackbar_open_issue_8](https://user-images.githubusercontent.com/13999905/70720969-d5b53800-1d1a-11ea-9f7f-00b2ef512fbc.gif)
![snackbar_open_issue_9](https://user-images.githubusercontent.com/13999905/70720972-d6e66500-1d1a-11ea-8313-6538dcda5708.gif)

**Would you like to work on the issue?**
Yes

**Comment by rakesh-1601** [comment]
I would like to work on this issue
