### ISSUE TITLE
Different Slider at Oscilloscope UI

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#203]
**Actual Behaviour**

In `Channel Parameter`, the slider related to `Trigger` is different from the one implemented in the application

**Expected Behaviour**

All the sliders in the app should share similar characteristics. Hence this slider needs to be changed

**Steps to reproduce it**
1. Open app
2. Go to `Applications`
3. Select `Oscilloscope`
4. Click on `Timebase and Trigger` tab and observe

**LogCat for the issue**
> Not available

**Screenshots of the issue**
![osc](https://user-images.githubusercontent.com/14261304/27324687-8cc774f2-55d8-11e7-8e11-fba7fdb03a35.png)

**Would you like to work on the issue?**
Yes!

**Comment by viveksb007** [comment]
@CloudyPadmal both sliders are same in my Android device. Api level 23. Whats the api level of your device? Could this be due to different Android versions?

**Comment by CloudyPadmal** [comment]
@viveksb007 I checked this with an API level 17 device!
