### ISSUE TITLE
About Us should contain additional information.

### ISSUE THREAD

**Issue by yuvrock** [fossasia/pslab-android#2043]
About Us should contain additional information such as about FOSSASIA, which made this application PSLab. There should be some information about FOSSASIA so people will be curious and search for other apps by FOSSASIA in case they like PSLab. This will increase downloads of FOSSASIA's all apps and softwares along with other benefits such as gained popularity, more job applications, more downloads, and more revenue.

**Comment by SAITARUN55** [comment]
I would like to work on this issue. Can someone please assign this to me
