### ISSUE TITLE
Bug that makes Not Connected pop up be displayed continuously.

### ISSUE THREAD

**Issue by yuvrock** [fossasia/pslab-android#2044]
A bug that makes Not Connected pop up be displayed continuously, which can be annoying and disturbing to the user and this Not Connected pop up doesn't go away until the application is closed and opened again.
![GIF-191224_173900](https://user-images.githubusercontent.com/35378149/71412647-a1c00800-2674-11ea-92aa-5409a6ac4d97.gif)

**Comment by angmas1** [comment]
Unable to reproduce, please check with latest version and let me know if bug still persists.
