### ISSUE TITLE
Add a language - Polish

### ISSUE THREAD

**Issue by rradzzio** [fossasia/pslab-android#2048]
**Actual Behaviour**

The app does not have a Polish language

**Expected Behaviour**

Full support for one additional language - Polish

**Would you like to work on the issue?**
Yes

**Comment by amit6663** [comment]
can i work on this issue? @rradzzio , @ho-dor

**Comment by ho-dor** [comment]
Sure

**Comment by CloudyPadmal** [comment]
Hello @amit6663 , unless you're a native Polish speaker, or know the language very well, I would suggest not to attempt different language translations from Google translate

**Comment by amit6663** [comment]
> Hello @amit6663 , unless you're a native Polish speaker, or know the language very well, I would strongly suggest not to attempt different language translations from Google translate.
> 
> Also I see @rradzzio is from Poland and we better let him continue with a PR.

ok
