### ISSUE TITLE
Record option not working (Wave Generator)

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/pslab-android#2056]
**Actual Behaviour**
The record option present in the wave generator does not record the wave.
The files obtained on recording are empty and are only 35 Bytes in size .

**Expected Behaviour**
On pressing the save option,the app should record the wave and save it as .CSV file.

**Steps to reproduce it**
* Open PSLab Android App
* Select Wave Generator option
* Click the Save icon in the top right corner of the app
* Produce a wave

**LogCat for the issue**

**Screenshots of the issue**
![Screenshot_2020-01-01-15-46-32-528_io pslab](https://user-images.githubusercontent.com/34577844/71640320-f33c4880-2cad-11ea-9c62-4457174c8593.jpg)

**Would you like to work on the issue?**

**Comment by rakesh-1601** [comment]
i would like to work on this issue.

**Comment by NishithP2004** [comment]
Go ahead :)

**Comment by ankit2019j** [comment]
can i work on this issue?

**Comment by NishithP2004** [comment]
Sure

**Comment by Ananyaas** [comment]
hey ! if this issue is still open ,may I work on this issue?

**Comment by NishithP2004** [comment]
> hey ! if this issue is still open ,may I work on this issue?

Sorry for the late reply, You may proceed with this issue. :)
