### ISSUE TITLE
Add gyroscope documentation

### ISSUE THREAD

**Issue by pranavkarthik10** [fossasia/pslab-android#2059]
Currently there is no Gyroscope tutorial/documentation for users intending to use it. This could be beneficial for students and contributors alike and would make a great addition to the existent set of tutorials for other instruments.

# Are you going go to work on this?
- [x] Yes
- [ ] No

**Comment by amanjn38** [comment]
Sir I would like to solve this issue.

**Comment by pranavkarthik10** [comment]
Sorry I am closing because there is the merged PR https://github.com/fossasia/pslab-documentation/pull/57.
