### ISSUE TITLE
Misaligned buttons

### ISSUE THREAD

**Issue by aa200400** [fossasia/pslab-android#2063]
**Describe the bug**

In the "Generate Config File", the buttons for instrument and time interval are misaligned and are partially cut out.

**To Reproduce**

1. Open the tabs to the right
2. Open "Generate Config File" screen
**Expected behavior**

The buttons should not be misaligned and out of place.
**Screenshots**

![Screenshot_20200107-072353](https://user-images.githubusercontent.com/54151334/71898765-bd6ce900-311f-11ea-86fb-7f4b4b223352.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | OnePlus 6|
|Android Version|   10.0 |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by rakesh-1601** [comment]
After fix there is still some misalignment . can i work on this issue ?

**Comment by angmas1** [comment]
Sorry, fixed with recent commit.

**Comment by rakesh-1601** [comment]
Okay :)

**Comment by cweitat** [comment]
Fixed by another PR
