### ISSUE TITLE
Dark Color Scheme

### ISSUE THREAD

**Issue by Sid911** [fossasia/pslab-android#2065]
## Objective
Dark color scheme or **Dark mode** for the pslab application

_**Please wait for more description**_
## Goals

- [ ] Have a perfect dark scheme setup with accent color of red
- [ ] User's Ability to change between light mode and dark mode

**Would you like to work on the issue?**

Yes I am working on this issue :)

**Comment by Sid911** [comment]
![image](https://user-images.githubusercontent.com/27860105/72585562-94650900-3914-11ea-99f0-41861e3a74ff.png)
![image](https://user-images.githubusercontent.com/27860105/72585564-962ecc80-3914-11ea-8e94-bdeabfd0f667.png)
![image](https://user-images.githubusercontent.com/27860105/72585567-975ff980-3914-11ea-93b5-5bdb68955324.png)

I know I might have flipped the colors of the action bar and the background but I was wondering weather to keep the accent in the card or the action bar? A good dark theme would have dark cards but action bar can be like of phimp.me with red accents?

(there are a few issue with black images, I am currently working on fixing them)

**Comment by Sid911** [comment]
@mariobehling @fcartegnie @cweitat @adityastic It would be nice to have opnion .. on the color scheme 😇

**Comment by Sid911** [comment]
Also the dark theme switches with system settings..

**Comment by hoangdatngo** [comment]
@Sid911 LGTM

**Comment by Sid911** [comment]
@hoangdatngo Thanks 😇

**Comment by mariobehling** [comment]
Currently out of scope as we have more basic things on the list. Therefore closing it.
