### ISSUE TITLE
Add limit in input value

### ISSUE THREAD

**Issue by juniorjainsahab** [fossasia/pslab-android#2071]
cc: @cweitat @CloudyPadmal @mariobehling

**Actual Behaviour**
In Robotic Arm Screen, the User can input as large value as they can in servo sections, Which causes the value out of its view bounds.

**Expected Behaviour**
Users should not be allowed to input more than 360. 

**Steps to reproduce it**

- Open the Application.
- Navigate to a Robotic-arm screen.
- Enter large values like "338439483" in any servo section.
- You will found that the values cross the view bounds.

**Screenshots of the issue**

![WhatsApp Image 2020-01-13 at 5 00 11 PM](https://user-images.githubusercontent.com/21375373/72252913-486d4800-3626-11ea-8a3e-f6866a86d28b.jpeg)

**Would you like to work on the issue?**
Yes, I would like to work on the issue.

**Comment by 991rajat** [comment]
Yes, I would like to work on the issue.

**Comment by juniorjainsahab** [comment]
@991rajat I have raised the issue and i am waiting for maintainers to approve this so I can start working on this. I have already stated that I am interested to work on this issue. @CloudyPadmal  @cweitat could you please do something in this issue?

**Comment by 991rajat** [comment]
@juniorjainsahab Sorry I didn't know that. I thought you opened the issue publicly. I will close my PR. Sorry for this

**Comment by juniorjainsahab** [comment]
@991rajat make it close once maintainers approve this issue I will start work on this.

**Comment by Sid911** [comment]
what if the user wants to make the servo do multiple loops 😕... it may be that .. the robotic arm's specific servo is being used for different purpose

**Comment by juniorjainsahab** [comment]
hey @Sid911 
As you can see the blue circular button to set value in the servo section it is limited to 360 as you can also see it in the image. Hence, It should be the same when you entering the value manually.

![WhatsApp Image 2020-01-14 at 11 28 59 PM](https://user-images.githubusercontent.com/21375373/72369317-dd0a9f80-3725-11ea-9b71-53f53bfd2c4a.jpeg)
