### ISSUE TITLE
App shutting down

### ISSUE THREAD

**Issue by TheVagabond1512** [fossasia/pslab-android#2081]
On my Redmi Note 4, the app keeps shutting down as soon as I switch on the inbuilt mic and the in-app recorder at the same time.

**Comment by ho-dor** [comment]
@TheVagabond1512 can you please share the logcat of this crash

**Comment by CloudyPadmal** [comment]
Hello @TheVagabond1512 , could you please report when the dialog shows when the app crashes so that we can investigate more into this issue.. Thanks.

**Comment by CloudyPadmal** [comment]
Similar issue raised #2032
