### ISSUE TITLE
bug: Accelerometer recording not stop

### ISSUE THREAD

**Issue by 991rajat** [fossasia/pslab-android#2082]
**Summary**
Can't able to stop Accelerometer recording.
But logs of recording are available.

**Steps to reproduce it**
Accelerometer > Start Rec > Stop Rec(Not able to stop)

**Screenshots of the issue**
![GIF-200118_201329](https://user-images.githubusercontent.com/38184186/72666356-59a7c180-3a37-11ea-8fb3-8f939bd1dbf3.gif)

**Device**
Moto E2
Android 7.1.2

**Would you like to work on the issue?**
Open to all.

**Comment by 991rajat** [comment]
@juniorjainsahab

**Comment by ho-dor** [comment]
@991rajat works fine on my device.

**Comment by 991rajat** [comment]
@ho-dor  I don't know why it is not working in my device.I thought maybe it's a bug.
