### ISSUE TITLE
bug: Map icon in Accelerometer logged data

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/pslab-android#2092]
**Actual Behaviour**
Nothing happens on clicking the map icon in Accelerometer logged data

**Expected Behaviour**
When clicking on map icon it should display the location data for the log(When location data is present).

**Steps to reproduce it**
Open the logged data for the Accelerometer instrument
Click on the map icon on logged data list item

**LogCat for the issue**
Nothing in the log

**Screenshots of the issue**
![bug accelerometer](https://user-images.githubusercontent.com/44086235/72877109-25c1ea00-3d1e-11ea-8be9-74ade6f12aa1.gif)

**Would you like to work on the issue?**
Yes

**Comment by nileshteji** [comment]
I am working on this issue .Thank You
