### ISSUE TITLE
bug: Recording start even when device not connected

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/pslab-android#2093]
**Actual Behaviour**
Recording can be started even if the device is not connected to mobile or mobile does not have inbuilt feature support

**Expected Behaviour**
If any device is not connected then for that device recording should not start

**Steps to reproduce it**
Open any device which is not connected or whose sensor are not present in mobile(Gas Sensor)
Click on Record button
See the error

**Screenshots of the issue**
![recording_issue](https://user-images.githubusercontent.com/44086235/73130918-dafae780-4027-11ea-8d69-cc2ca60013fc.gif)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Expected behavior would be a pop up "Please connect a device or choose an phone sensor (if available)" and two buttons "Configure Active Sensor" and "Cancel".

**Comment by mariobehling** [comment]
In sensors that are usually present on the phone the recording should work nevertheless.

**Comment by SpandanBasu** [comment]
I am a beginner. I want to work on this issue please assign me

**Comment by SpandanBasu** [comment]
When the sensor is not present and the user clicks on the recording button, A pop-up dialog comes..right..but on pressing on Configure active sensor where should the app take the user?

**Comment by sambhavsaxena** [comment]
Please assign this issue to me

**Comment by SpandanBasu** [comment]
This issue is already fixed i opened a pull request. Try a different issue. Thanks

**Comment by shubham-200315** [comment]
Hey @mariobehling , Issue is fixed and PR is merged already so i think we can close this.
Thank you.

**Comment by marcnause** [comment]
Fixed in https://github.com/fossasia/pslab-android/pull/2295. A notification (SnackBar) is shown that informs the user that no device is connected.
