### ISSUE TITLE
Bmp180

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2098]
**Actual Behaviour**
Doesn't read temp (readout stays at 0)

**Comment by hariom9522** [comment]
i want to c ontribute to this project.please assign me

**Comment by marcnause** [comment]
Will be fixed in https://github.com/fossasia/pslab-android/pull/2527

**Comment by marcnause** [comment]
Fixed via https://github.com/fossasia/pslab-android/pull/2527
