### ISSUE TITLE
Oscilloscope: Range does not change, when option is chosen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2099]
The Oscilloscope has the option to change the range, e.g. of the Voltage display. This is currently not working. There is no visual change in the app if the user changes the range.

* Th setting sensitivity doesn't work, it is always +-16V

![Screenshot_20200203_133437_io pslab](https://user-images.githubusercontent.com/1583873/73653770-555fe300-468a-11ea-82da-7c418ab6a2df.jpg)

**Comment by 991rajat** [comment]
Works fine on my device.
![GIF-200203_232341](https://user-images.githubusercontent.com/38184186/73677543-7fda8c00-46dc-11ea-8e94-5fd12bd7923f.gif)

**Comment by Low012** [comment]
It works if the channel is selected (check mark is set). It does not work if the channel is not selected.

If the expected behaviour is that the range can only be changed if the channel is selected I would expect the range selection to be disabled if the channel is not selected. This would provide a visual hint to the user.

Also the range does not change if:
1. the channel is not selected
1. a different range is selected
1. the channel is selected

**Comment by 991rajat** [comment]
Still in my device.
If the channel is not selected -> changing range changes the graph.
If the channel is selected -> changing range changes the graph.
I'm not able to get it what bug is.

**Comment by Low012** [comment]
It may depend on the Android API level. 

It works as pictured by @991rajat on my device with Android 9, but if I use my test device with Android 7 I get the behaviour as described by @mariobehling.

**Comment by 991rajat** [comment]
@Low012, Yaa not able to reproduce.

**Comment by kartikeysaran** [comment]
Can i take up this issue

**Comment by AnishaSingh0118** [comment]
may i work on this issue?

**Comment by kartikeysaran** [comment]
Sure @AnishaSingh0118 go ahead !

**Comment by AnishaSingh0118** [comment]
> Sure @AnishaSingh0118 go ahead !

Thanks 😊

**Comment by marcnause** [comment]
I had a quick look at the issue again. I think it is only reproducable with the hardware. If no signal is displayed in the oscillosocope screen, changing the range works on my device. Once a signal is displayed, the range always resets to +/- 16V

**Comment by marcnause** [comment]
I tested again with the latest development version of the app (https://github.com/fossasia/pslab-android/commit/5d6b449a6ca2d5b33ac1996f01f294a753cefaea) and a v6 board. The problem still exists.
