### ISSUE TITLE
Oscilloscope: Trigger CH1 actually works on CH2

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2101]
Oscilloscope: Trigger CH1 actually works on CH2.

**Comment by CodeWithSouma** [comment]
@mariobehling  sir, please help me how to fix this problem I want to work on this issue.

**Comment by PrajwalG22** [comment]
Hey I have just started with open source contribution.
Can you help me working on this issue.

**Comment by suman-somu** [comment]
working on this. 
good to me, if assigned.

thank you.

**Comment by MonuGit9** [comment]
Claim

**Comment by marcnause** [comment]
I close this issue since triggering works as intended after https://github.com/fossasia/pslab-android/pull/2482 has been merged.
