### ISSUE TITLE
How to input new graph instread of Plot2D View?

### ISSUE THREAD

**Issue by hayleyshim** [fossasia/pslab-android#2106]
Hello,

I would like to change Plot2D.java source code.

In this code, 'Class' is implemented 'extends view'. 

But, I would like to plot my data with MpAndroidChart.

Could you explain how to plot my data in Plot2D source code?

 
![image](https://user-images.githubusercontent.com/8789789/74756235-9590a980-52b7-11ea-90b6-be7bba19efd2.png)

**Comment by reckoner1429** [comment]
Hi @hayleyshim, It would be better if you could kindly use the gitter channel for the queries. You can delete this issue hence. 
And if you want to raise an issue then there is an specific format for that, it would be helpful for others if you use that format.

Here is the link for gitter channel 
[https://gitter.im/fossasia/pslab](url)

I might be able to answer your question there
