### ISSUE TITLE
Use Interface Callbacks to reduce Coupling between Activity and Fragments and reduce the lines of code

### ISSUE THREAD

**Issue by reckoner1429** [fossasia/pslab-android#2108]
**Actual Behaviour**
`PsLabSensor` directly calls methods from fragments such as `LuxMeterDataFragment,` `SoundMeterFragment` etc, which increases coupling and also increases lines of codes in the `onOptionItemSelected()` method of `PsLabSensor`. In addition it increases chances of introducing bugs when new sensors are implemented. 

**Expected Behaviour**
**Interface callbacks** can be used to reduce the coupling between `PsLabSensor` and other data fragments. We can define a interface with common set of methods such as play(), stop(), pause(), resume() etc and have the fragments implement this interface.

**Steps to reproduce it**
`N/A`

**LogCat for the issue**

`N/A`

**Screenshots of the issue**
The lines of codes below are redundant.
![coupling_issue](https://user-images.githubusercontent.com/13999905/74801008-45d3d180-52fb-11ea-8233-37be7c39cf4e.png)

**Would you like to work on the issue?**
Yes

**Comment by VIKAS9899** [comment]
I want to work on this issue, Please assign it to @VIKAS9899

**Comment by adityastic** [comment]
@VIKAS9899 go ahead
