### ISSUE TITLE
Mainscreen: Tiles disappear

### ISSUE THREAD

**Issue by Low012** [fossasia/pslab-android#2116]
**Actual Behaviour**

The tiles in the main screen disappear under certain circumstances.

**Expected Behaviour**

The tiles should always be visible in the main screen.

**Steps to reproduce it**

1. Open app
1. Tap on "Wave Generator"
1. Tap on "Produce Sound" button until text on button changes to "Stop Sound" (I need to tap twice on my device)
1. Tap on Android back button or on arrow in the Action bar
1. Change orientation of device

**LogCat for the issue**

The only remotely interesting lines:

2020-06-10 22:22:59.166 1119-1205/? I/WindowManager: Screen frozen for +503ms due to Window{4b88b9c u0 io.pslab/io.pslab.activity.WaveGeneratorActivity}
2020-06-10 22:22:59.173 1119-1142/? I/ActivityManager: Displayed io.pslab/.activity.WaveGeneratorActivity: +500ms

**Screenshots of the issue**

![Screenshot_20200610-214602_PSLab](https://user-images.githubusercontent.com/11596220/84316219-0d3a5b00-ab6b-11ea-814a-6c133714a23e.png)

**Would you like to work on the issue?**

I can have a look or help debugging this issue.

**Comment by Low012** [comment]
The AsyncTask in InstrumentsFragment seems to not be executed in the error case described above. This may or may not be related to the AsyncTask in WaveGeneratorActivity.

AsyncTask will be deprecated in API level 30 (Android 11). AsyncTask has always been a pain to use and caused all kinds of problems. Maybe it would be a good idea to get rid of it where possible.

**Comment by nileshteji** [comment]
@Low012  I tried to reproduce your error but Bug was never seen .Can you tell more about the Device which you were using .Thank You

**Comment by Low012** [comment]
I was able to reproduce the issue with:

- Fairphone 2 (LineageOS 17.1)
- Moto X Play (Android 7.1.1)
- Lenovo Yoga Smart Tab (Android 9)

I could make a video if that helps, just let me know. It could take a few days though.

**Comment by nileshteji** [comment]
You can upload all the videos of each device on a google drive which would be of great help. I will be waiting for the link. Thank you again @Low012

**Comment by Low012** [comment]
I have uploaded the videos to https://drive.google.com/drive/folders/10BubwXAjHLAjVP75cFxwg-YbBPRx6AdM

I am using version 2.0.20 of the app on all devices, Play Store flavor on Moto X Play, Fdroid flavor on Fairphone 2 and Lenovo Yoga Smart Tab.

**Comment by nileshteji** [comment]
Thank you @Low012 I will be working on this issue.

**Comment by Low012** [comment]
@nileshteji, thank you for your changes and for your pull request. Unfortunately GitHub does not let me comment the pull request at the moment, that's why I am replying here.

I can confirm that the APK you provided fixes the problem for me.
