### ISSUE TITLE
Mainscreen: Layout issues on tablets

### ISSUE THREAD

**Issue by Low012** [fossasia/pslab-android#2117]
**Actual Behaviour**

Part of the menu on the left side is hidden, circle around logo has visible pixels on my device (Lenovo Yoga Smart Tab).

**Expected Behaviour**

No parts of the layout should be hidden (logo, PsLab status), no single pixels should be visible.

**Steps to reproduce it**

Open the app on a Lenovo Yoga Smart Tab (maybe any tablet)

**Screenshots of the issue**

![Screenshot_20200610-224145](https://user-images.githubusercontent.com/11596220/84316908-3c9d9780-ab6c-11ea-8d74-e2d98d9bf1be.jpeg)

**Would you like to work on the issue?**

I can have a look if nobody else feels like it.

**Comment by saketsingh0078** [comment]
yes , i want to work on this issue

**Comment by CloudyPadmal** [comment]
Fixed by #2134
