### ISSUE TITLE
Multimeter: Layout looks weird on tablet devices

### ISSUE THREAD

**Issue by Low012** [fossasia/pslab-android#2118]
**Actual Behaviour**

The multimeter looks weird on tablet devices, the measured value is partly hidden.

**Expected Behaviour**

The layout should look more pleasing (larger knob or a margin around the whole multimeter) and the value should be completely visible.

**Steps to reproduce it**

1. Start app on tablet device
1. Select multimeter

**Screenshots of the issue**

![Screenshot_20200610-224910](https://user-images.githubusercontent.com/11596220/84317575-48d62480-ab6d-11ea-8274-d131d9868f2d.jpeg)

**Would you like to work on the issue?**

Maybe..

**Comment by xanmolx** [comment]
I am unable to reproduce the issue. 
![Screenshot_1593444674](https://user-images.githubusercontent.com/23299222/86025411-c7770100-ba4b-11ea-819a-02ef42653303.png)

This is the screenshot on a tablet emulator device
Device:- Pixel C
Android Version:- 10

**Comment by Low012** [comment]
My device:

Device: Lenovo Yoga Smart Tab
Android Version: 9

**Comment by Girish-Bharadwaj** [comment]
Hey I would like to solve this issue and try my best
