### ISSUE TITLE
Request: Horizontal layouts for all screens

### ISSUE THREAD

**Issue by Low012** [fossasia/pslab-android#2119]
**Actual Behaviour**

At the moment not all screens have an extra layout for horizontal (landscape) orientation. Instead the screens are displayed in vertical (portrait) orientation, no matter of the orientation of the device.

**Expected Behaviour**

It would be really nice to have horizontal layouts for all screens in order to improve user experience for devices which can be placed on a table in horizontal orientation.

**Steps to reproduce it**

Open app, choose multimeter

**Photo of the issue**

![IMG_20200610_225851](https://user-images.githubusercontent.com/11596220/84318793-470d6080-ab6f-11ea-9fea-99a002387d9c.jpg)

**Would you like to work on the issue?**

Not really.

**Comment by Hyper-Matrix** [comment]
i would like to work on this issue

**Comment by sanchi0204** [comment]
Is this issue available to work? 
@Hyper-Matrix can you tell if you are working on this issue or not?

**Comment by Hyper-Matrix** [comment]
No...since so one confirmed it...i haven't started it yet.

**Comment by Anu-123-gif** [comment]
@Low012 can I work on this issue?

**Comment by Low012** [comment]
I'd love to see this issue taken care of and I am not working on it since I am not very good at layouts. I am not a maintainer of this project, but I'd say go for it!
