### ISSUE TITLE
Faq section expandable list view not working 

### ISSUE THREAD

**Issue by CodeWithSouma** [fossasia/pslab-android#2126]
### Expected Behaviour
It should show answer of that question 

### Screenshots of the issue

<pre><img src = "https://user-images.githubusercontent.com/38830139/91998200-8efbe800-ed58-11ea-835b-12fcc50adb33.png" width="200"/> <img src = "https://user-images.githubusercontent.com/38830139/91999851-7c82ae00-ed5a-11ea-8766-30423551280b.png" width="200" /> <img src="https://user-images.githubusercontent.com/38830139/91999994-a5a33e80-ed5a-11ea-8f1f-7952f27d0996.png" width="200"/> <img src="https://user-images.githubusercontent.com/38830139/92000650-5e697d80-ed5b-11ea-9357-7c458300f778.png" width="200"/></pre>

### Gif 
<pre>
                                        <img src="https://user-images.githubusercontent.com/38830139/92000818-953f9380-ed5b-11ea-9cf6-de7d5361b601.gif" width="200" /> </pre>

**Comment by ritmojs** [comment]
I want to work on this issue

**Comment by CodeWithSouma** [comment]
> I want to work on this issue

I already **fixed** it. and send **PR** #2127

**Comment by nileshteji** [comment]
@CodeWithSouma  the pr you mentioned is not mergest . Are you still working on this issue?Thank you

**Comment by CodeWithSouma** [comment]
> Are you still working on this issue?

Yes i am woking on this issue
