### ISSUE TITLE
Update pin names

### ISSUE THREAD

**Issue by bessman** [fossasia/pslab-android#2133]
Change all instances of

ID1/2/3/4 -> LA1/2/3/4
SEN -> RES
AN8 -> VOL
CNTR -> FRQ
W1/2 -> SI1/2

**Comment by CodeWithSouma** [comment]
> Change all instances of
> 
> ID1/2/3/4 -> LA1/2/3/4
> SEN -> RES
> AN8 -> VOL
> CNTR -> FRQ
> W1/2 -> SI1/2
I don't  under stand where to change this instances....do you want to change these in string file ???

**Comment by bessman** [comment]
Everywhere throughout the code. The old pin names were used in a previous hardware revision. For example, the pins called ID1, ID2, ID3, and ID4 in the code should be changed to LA1, LA2, LA3, and LA4 to reflect the current hardware.

This command should do the trick:
```
find app/src/main/ \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/ID1/LA1/g'
```
Repeat for all above-mentioned strings.

**Comment by CodeWithSouma** [comment]
> Everywhere throughout the code. The old pin names were used in a previous hardware revision. For example, the pins called ID1, ID2, ID3, and ID4 in the code should be changed to LA1, LA2, LA3, and LA4 to reflect the current hardware.
> 
> This command should do the trick:
> 
> ```
> find app/src/main/ \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/ID1/LA1/g'
> ```
> 
> Repeat for all above-mentioned strings.

sir can you tell me how to use this command to find reference .....i don't  use this command before please help me i want to work on this issue
