### ISSUE TITLE
App crashing on Android 8.0

### ISSUE THREAD

**Issue by AtigPurohit** [fossasia/pslab-android#2145]
<img width="249" alt="Screenshot 2020-12-07 193415" src="https://user-images.githubusercontent.com/64990546/101360120-3b52ea80-38c3-11eb-9579-71fb70a08421.png">
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by CodeWithSouma** [comment]
can you tell me when it crash

**Comment by AtigPurohit** [comment]
@CodeWithSouma  the app is not opening itself, I gave the screen shot

**Comment by CodeWithSouma** [comment]
> @CodeWithSouma the app is not opening itself, I gave the screen shot

I don't find any issue it runs smoothly on my device. I think you are using an emulator. Try to run on a physical device.
