### ISSUE TITLE
Keyboard hiding the snackbar output in USB Connection.

### ISSUE THREAD

**Issue by asaikarthikeya** [fossasia/pslab-android#2176]
**Actual Behaviour**

When the user enters the IP Address of ESP module the error message is hidden behind the keyboard .User is able to see the snackbar output only if we press back button to remove keyboard 

**Expected Behaviour**

The error message should be visible to the user.

**Steps to reproduce it**

The edittext that is used to enter the IP address is replaced by materialdesign TextInputLayout ,so that we can view the error messages near the edittext instead of snackbar from bottom.

**Screenshots of the issue**

https://user-images.githubusercontent.com/70392921/105354591-c50e0b80-5c16-11eb-8374-7caa141a030c.mp4

**Comment by KushMehta1511** [comment]
@asaikarthikeya I am not facing this issue on my device. Did you check using the emulator as well?

**Comment by asaikarthikeya** [comment]
@KushMehta1511 Checked in 2 real device , Found this issue in both.

**Comment by Prashant830** [comment]
Can I solve this problem ??

**Comment by asaikarthikeya** [comment]
@Prashant830 PR is yet to be reviewed.

**Comment by asaikarthikeya** [comment]
> Can I solve this problem ??

There is a PR already attach. Kindly wait till it gets reviewed.

**Comment by Prashant830** [comment]
Ok
