### ISSUE TITLE
"Generate Config Files" layout is not uniform.

### ISSUE THREAD

**Issue by asaikarthikeya** [fossasia/pslab-android#2181]
**Actual Behaviour**

The spacing between the instrument and time interval is varing for different instrument.

**Expected Behaviour**

All the instruments should have a similar layout style.

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/70392921/105576602-ef3c0680-5d99-11eb-8c43-9e42b0e7dc51.png" width="300" height="500"/> <img src="https://user-images.githubusercontent.com/70392921/105576727-ccf6b880-5d9a-11eb-8d3b-ae922ac1d7a9.png" width="300" height="500"/>  
<img src="https://user-images.githubusercontent.com/70392921/105576608-f5ca7e00-5d99-11eb-9f81-803b6089b932.png" width="300" height="500"/>

**Device**

Asus max pro m1(5.9 inch)

**Comment by AnishaSingh0118** [comment]
hey, I am Anisha, I would like to work on this issue if it is still open.

**Comment by kartikaysharma01** [comment]
> hey, I am Anisha, I would like to work on this issue if it is still open.

Hi anisha. This issue has a few open PRs which will potentially close it. You can look into some other issue. Thanks.

**Comment by kartikaysharma01** [comment]
@CloudyPadmal can we close and move this issue to #2208 to reduce confusion as a whole layout change has been decided

**Comment by AnishaSingh0118** [comment]
> > hey, I am Anisha, I would like to work on this issue if it is still open.
> 
> Hi anisha. This issue has a few open PRs which will potentially close it. You can look into some other issue. Thanks.

Oh ok :)
