### ISSUE TITLE
Add icon for developers in About us.

### ISSUE THREAD

**Issue by asaikarthikeya** [fossasia/pslab-android#2189]
**Actual Behaviour**

Currently in about us section there is no icon for Developers and "Connect with us" heading can be made better.

**Expected Behaviour**

Add a developers icon  and improve the visibility/appearance  of "Connect with us " text .

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/70392921/106695864-83f7fd00-6601-11eb-97d6-07f52e49cb29.png" width="250" height="400"/>

**Comment by CadencePrestissimo** [comment]
Can I do this ?
