### ISSUE TITLE
At navigation drawer, The menu option of help & Report a Bug is missing ..

### ISSUE THREAD

**Issue by Prashant830** [fossasia/pslab-android#2190]
**Actual Behaviour**
At navigation drawer, The menu option of help & Report a Bug is missing ..

**Expected Behaviour**
After creating the report a bug & help option, navigation drawer, if any user sees any issue or bug in app, then that user will click on this option and then he will come to the issue option of github repository of app so that he can create his new issue .

**Steps to reproduce it**
Creating a menu option for report a bug at navigation drawer.

**Screenshot**
![WhatsApp Image 2021-02-04 at 10 06 04 AM](https://user-images.githubusercontent.com/72181295/106845515-187d6080-66d1-11eb-9428-7da12847f5ef.jpeg)

**Would you like to work on the issue?**
yes

**Comment by MonuGit9** [comment]
Claim

**Comment by marcnause** [comment]
I am closing this issue since the PR for this issue was closed without merge with the reasoning that adding more options would overcrowd the navigation drawer,
