### ISSUE TITLE
The same bluetooth device is shown multiple time in listview

### ISSUE THREAD

**Issue by CodeWithSouma** [fossasia/pslab-android#2204]
**The same Bluetooth device is shown multiple time in listview when we click scan and then stop then rescan Please check the gif**

![Bluetooth error](https://user-images.githubusercontent.com/38830139/111830505-10d9ea00-8914-11eb-8237-2c6801b8c993.gif)

**Comment by raghavpartani** [comment]
I want to work on this issue.

**Comment by CodeWithSouma** [comment]
> I want to work on this issue.

Hey, I already made a PR please go through another issue.
