### ISSUE TITLE
getDrawable() is deprecated and needs to be replaced

### ISSUE THREAD

**Issue by Abhinavtdk** [fossasia/pslab-android#2206]
**Actual Behaviour**

getDrawable( int ) is deprecated and is used in many places in the project

**Expected Behaviour**

getDrawable() needs to be replaced, we can use ResourcesCompat.getDrawable() 

**Would you like to work on the issue?**

Yes

**Comment by Glock123** [comment]
Is this issue closed?

**Comment by Abhinavtdk** [comment]
> Is this issue closed?

I made a pr #2207 , it has to be approved

**Comment by Aditya8840** [comment]
is this open ?

**Comment by kartikaysharma01** [comment]
Hi @Aditya8840, This issue is not a priority right now. Please have a look at some other issues. You can refer to the prior discussion [here](https://github.com/fossasia/pslab-android/pull/2207#issuecomment-811760004). Thanks.

**Comment by sakshampruthi** [comment]
Great, I'd like to work on this issue

**Comment by Prakhar-Agarwal-byte** [comment]
I would like to work on this issue

**Comment by Prakhar-Agarwal-byte** [comment]
I am working on this issue
