### ISSUE TITLE
Offer choice of Google Maps or OpenStreetMap 

### ISSUE THREAD

**Issue by kartikaysharma01** [fossasia/pslab-android#2209]
**Actual Behaviour**
For Playstore users, we can provide an option to use Google Maps or OpenStreetMap in App settings 

**Would you like to work on the issue?**
Yes

**Comment by kartikaysharma01** [comment]
@CloudyPadmal Should i go ahead with the implementation ?

**Comment by CloudyPadmal** [comment]
Yes please go ahead.

**Comment by kartikaysharma01** [comment]
@CloudyPadmal What should be the default map for playstore users?  
Should we keep OpenStreetMap as default and give a small one-time-warning before switching to Google Maps that it is a proprietary API.

**Comment by kartikeysaran** [comment]
I am working on this

**Comment by kartikaysharma01** [comment]
I am occupied in another project as of now. If somebody wants to pick up this issue you are most welcome.

**Comment by sempsmahad** [comment]
Hello guys, I am new to the technology, on which screen is the current version of the map?, I can not find it.
Adding the options in settings should be easily doable but the effect on the interface

**Comment by CloudyPadmal** [comment]
Not using Google Maps anymore. Moved to Openstreetmaps.
