### ISSUE TITLE
Bug in connect device activity.

### ISSUE THREAD

**Issue by Prashant830** [fossasia/pslab-android#2217]
**Actual Behaviour**

Bug in connect device activity.

**Expected Behaviour**

When i click <b>`What is psLab device ? textView`</b> and at the same time i press backspace button then the fragment of pslab device overloaded at the connect device activity due to this the ui of the connect device activity is mismatching form (It Ui looks not batter ).

**Steps to reproduce it**
When i click <b>`What is psLab device ? textView`</b> and at the time i press backspace button then it not showing any further activity ,simply showing connect device ui..

**Screen Recording of the issue**

[Click here for access Screen Recording Video ](https://drive.google.com/file/d/1uONkhBF46c4Yqh3mu5SC7bpmIzTwX6TJ/view?usp=drivesdk) 

**Would you like to work on the issue?**
Yes I would like to solve this issue..

**Comment by Prashant830** [comment]
@mariobehling , @CodeWithSouma please review it..

**Comment by CloudyPadmal** [comment]
Thanks for reporting the issue. If you can fix it, please go ahead.

**Comment by Prashant830** [comment]
@CloudyPadmal ok..

**Comment by Prashant830** [comment]
@CloudyPadmal , @CodeWithSouma   [ please review  solution  in sample videos](https://drive.google.com/drive/folders/1wE6W-_STez0wA_st5AGYEAttWbUMf2iI?usp=sharing)

**Comment by CloudyPadmal** [comment]
Looks good. Can you file a pull request with the modifications?
