### ISSUE TITLE
Threat of cash with NoClassDefFoundError on some devices

### ISSUE THREAD

**Issue by Linlinllll** [fossasia/pslab-android#2219]
Dear pslab developers,

I have found out that when I touch any point on the UI screen shown bellow, the app will crash with `NoClassDefFoundError`. After I check the log file, I found the method is `android/text/Html.fromHtml(Ljava/lang/String;I)Landroid/text/Spanned;`. This method is introduced at API level 24, but the `minSDKVeriosn` is set to 23. When I install the app into devices with API level 23, and then touch any point on the screen shown bellow, the app will crash with `NoClassDefFoundError`.

Thank you very much if you can fix this. Hope this information is helpful. :)

<img width="305" alt="截屏2021-07-06 下午1 51 12" src="https://user-images.githubusercontent.com/41045759/124549120-4b36ab00-de61-11eb-9676-d85c24edbbe6.png">

**Comment by Low012** [comment]
I think this issue should be fixed in version 2.1.0

**Comment by CloudyPadmal** [comment]
Thanks @Low012 for following this up. Let me check if it still exists and update this issue.

**Comment by CloudyPadmal** [comment]
This is fixed
