### ISSUE TITLE
Substitute Travis CI with Github Actions and Circle CI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2226]
Travis CI was used to build test apps automatically. We also used Travis CI for tests. As Travis no longer supports Open Source please use Github Actions and Circle CI instead.

**Comment by CloudyPadmal** [comment]
We have already moved from travis to GitHub actions..

**Comment by CloudyPadmal** [comment]
There are some breadcrumbs from travis in the project. Reopened to fix those.
