### ISSUE TITLE
Create auto builds of APKs using Github Actions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2245]
Until a few months ago Travis supported us and we used it for continuous integration and creating auto-builds of APKs in the apk branch. Please update the project to use Github Actions instead of Travis CI to create these auto builds in https://github.com/fossasia/pslab-android/tree/apk.

**Comment by MohitGupta121** [comment]
Okay I'm ready to work on that issue @mariobehling can you please assign that issue.

**Comment by MohitGupta121** [comment]
@mariobehling  I have make initial PR for this issue so that I can step by step work on that issue.
I need guide to work on this issue can you please Review my this PR and tell me what more things required in this PR so that I can add that also.

**Comment by CloudyPadmal** [comment]
It's not solved to say. But the APKs are available as artefacts. We might still need to implement this feature

**Comment by CloudyPadmal** [comment]
Fixed with #2314
