### ISSUE TITLE
Implement Logic Analyzer Functionality

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#225]
**Actual Behaviour**

Currently Logic Analyzer is generating randon digital signal.

**Expected Behaviour**

It should generate signal corresponding to selected channel mode. The following channel modes needs to be implemented for Logic Analyzer:
- [ ] Single Channel Mode
- [ ] Two Channel Mode
- [ ] Three Channel Mode
- [ ] Four Channel Mode

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
@CloudyPadmal If you don't have any issue at hand currently. Could you take this one up?
I did some work commits are on [dev](https://github.com/viveksb007/pslab-android/tree/dev) branch.

**Comment by CloudyPadmal** [comment]
Sure @viveksb007 ! I'll give this a try! :+1: Thanks a lot!

**Comment by asitava1998** [comment]
@CloudyPadmal  What is the current status of this issue?

**Comment by CloudyPadmal** [comment]
Hi @asitava1998 ! Implementation is complete! But errors in byte reading cause issues. That's where it is stuck!

**Comment by CloudyPadmal** [comment]
Will be addressed in #912
