### ISSUE TITLE
`About us` section just after launching app does not close navigation drawer and take longer time than usual

### ISSUE THREAD

**Issue by developer-nobita** [fossasia/pslab-android#2267]
**Actual Behaviour**

When we click on `About Us` section in navigation drawer first time after launching the app, then it takes a longer time than usual and navigation drawer is in open state.

https://user-images.githubusercontent.com/51999411/138159968-9eb0b909-24e4-4b5f-9458-a6a2a7d6719c.mp4

**Expected Behaviour**

When we click on `About Us` section in navigation drawer first time after launching the app, then it should take as much time as other sections and navigation drawer should be in close state.

https://user-images.githubusercontent.com/51999411/138159989-3179a09a-2b97-4781-a7d7-876b28fadb96.mp4

**Steps to reproduce it**

Try to open `About us` section from navigation drawer just after launching the app.

**Screenshots of the issue**

N/A

**LogCat for the issue**

N/A

**Would you like to work on the issue?**

I would like to work on this issue.

**Comment by developer-nobita** [comment]
I go through the code to fix this bug and found that it is occurring in development branch only when device is in dark mode. So I tried to comment the `simulateDayNight(0);` function call in `AboutUsFragment.java` and it worked.

I want to know why we are calling this function only in `AboutUs` fragment?

**Comment by suman-somu** [comment]
@developer-nobita , the function work in there was to decide whether the user device is in light or dark mode and work accordingly. But that method was directing to the light mode of the device only. And I think that's why it is lagging in night mode.

**Comment by suman-somu** [comment]
i am on it

**Comment by duttabhishek0** [comment]
Hey, is the issue still open?
