### ISSUE TITLE
Field values have a higher resolution than required in Control UI

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#228]
**Actual Behaviour**

The Control UI input boxes has nearly 8 decimal places.

**Expected Behaviour**

The precision for voltages should be set to 3 decimal places & frequency should be set to one decimal place

**Steps to reproduce it**

1. Open App
2. Go to `Applications`
3. Proceed to `Control`
4. Try sliding the sliders to set values to input boxes and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![screenshot_2017-06-24-08-00-45](https://user-images.githubusercontent.com/14261304/27506863-66770c20-58f5-11e7-8e7a-4a03572e85fd.png)

**Would you like to work on the issue?**

Yes!

**Comment by asitava1998** [comment]
@CloudyPadmal I would suggest you to make a new layout directory `layout-sw320dp` and adjust the layouts for control in that file. Are you also going to take care about the digits after decimal or should I do it?

**Comment by CloudyPadmal** [comment]
@asitava1998 I am planning on creating a new directory to support 320dp screens and adjust view changes there :) I'm working on this issue and will send the pull request soon! :+1:
