### ISSUE TITLE
Remove flavour settings from app

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#2305]
**Actual Behaviour**

There are two flavours fdroid and playstore apk versions being built in this app

**Expected Behaviour**

Now that we have removed Google maps, we don't need these two flavours anymore. Remove the configurations and update app.

**Steps to reproduce it**

Check build.gradle file

**LogCat for the issue**

> N/A

**Screenshots of the issue**

> N/A

**Would you like to work on the issue?**

Up for grabs!

**Comment by yash37158** [comment]
can I work on this issue?
