### ISSUE TITLE
Multimeter screen layout incomplete

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2342]
**Actual Behaviour**
The multimeter screen shows only part of the layout. The knob is not visible.

**Expected Behaviour**
The complete layout should be visible, including the knob.

**Steps to reproduce it**
Open the multimeter screen

**Screenshots of the issue**
![Screenshot_20220413-234737_PSLab](https://user-images.githubusercontent.com/11596220/163277632-972458d3-50ce-448d-83d4-44076d7abeaa.png)

**Would you like to work on the issue?**
Yes

**Comment by rehanwick** [comment]
## Please Assigned me this issue 
I Have seen the issue- 
- XMl  file error Layout 
- activity_ultimeter_main.xml file the layout error 

I can solve the issue please Assigned me the task

**Comment by Low012** [comment]
Hey @rehanwick, thanks for having a look. I wanted to fix the issue, but my Android layout skills are a little bit rusty (to say the least) and I didn't manage to solve the problem. I don't have the access rights to assign you this task, but I am not working on it, so you won't be doing double work.

**Comment by MonuGit9** [comment]
Claim
