### ISSUE TITLE
Fix issues related to app store

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2374]
1. Update your target API level by August 31, 2023 to ensure that your app is available to new users
We've detected that your app is targeting an old version of Android. To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements. From August 31, 2023, if your target API level is not within 2 years of the latest Android release, your app will not be available to new users running Android versions higher than your app's target API level. 
2. Update privacy policy to make it adequate

**Comment by CloudyPadmal** [comment]
APK HAS A PRIVACY POLICY​ BUT IT IS NOT ADEQUATE

Privacy Policy in Play Console  
Your app is uploading users' File information without disclosing it in the privacy policy in Play Console.
Privacy Policy in Play Distributed App
Your app is uploading users' File information without posting a privacy policy in Play Distributed App.
