### ISSUE TITLE
PSLab v6 does not connect

### ISSUE THREAD

**Issue by bessman** [fossasia/pslab-android#2381]
The USB VID & PID values must be updated for the new hardware version: https://github.com/fossasia/pslab-android/blob/7f0c6406ebfc8f929cbb6be03030bfc430dcf904/app/src/main/java/io/pslab/communication/CommunicationHandler.java#L18

The new values are:
VID: 0x10C4
PID: 0xEA60

**Comment by ihrishix** [comment]
Still open for contributions?

**Comment by bessman** [comment]
Yes.

**Comment by marcnause** [comment]
Fixed with https://github.com/fossasia/pslab-android/pull/2488
