### ISSUE TITLE
Resuscitate PSLab Android app at Playstore

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#2386]
**Actual Behaviour**

Currently, due to different issues as listed in the play console, the app is not available for download.

**Expected Behaviour**

The app should be available at Playstore.

**Steps to reproduce it**

> N/A

**LogCat for the issue**

> N/A

**Screenshots of the issue**

<img width="1108" alt="PlayConsole" src="https://github.com/fossasia/pslab-android/assets/14261304/8e1bc243-8e6d-44ac-973c-2f7926ad2942">

**Would you like to work on the issue?**

Yes

**Comment by Detective-Khalifah** [comment]
This issue is interesting. How is it turning out so far? Have you resolved it?

**Comment by Detective-Khalifah** [comment]
Very well, thanks!
