### ISSUE TITLE
App not available to new users on Play Store

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#2395]
From 31 August 2023, if your target API level is not within two years of the latest Android release, your app will not be available to new users running Android versions higher than your app's target API level.

To ensure that your app is available to new users, update your app to target Android 13 (API level 33).

**Comment by AsCress** [comment]
Hey there. Currently the app is set to target API level 34. Is it still not available to the new users ?

**Comment by AsCress** [comment]
Is this issue still there ? Because I see now that the app is set to target API level 34.

**Comment by CloudyPadmal** [comment]
The requirements by Google Play is now in effect. We're working on a solution to make the app available on Playstore.
