### ISSUE TITLE
What can be the best approach to deal with the threads?

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#241]
**Current Approach**
The following diagram explains the current approached the is used in Oscilloscope Activity.

![screen shot 2017-06-27 at 6 49 39 pm](https://user-images.githubusercontent.com/26146675/27589558-7a57ff80-5b69-11e7-8211-abab40ea9f32.png)

**Comment by viveksb007** [comment]
Checking boolean values inside a while loop might be inefficient. 
There is one approach I can think of i.e besides Oscilloscope Activity, start a service which would create Async tasks. Now when any checkbox is checked, pass a message to service from listener of checkbox and service after receiving message from Activity, would start an Async task. When Async task is completed it would update graph. There are 2-3 ways of communication between Activity and Service, will see what's most suitable for us. I hope the approach is clear.
