### ISSUE TITLE
minSDK is too high

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#2419]
**Actual Behaviour**

The minSDK version is at 31

**Expected Behaviour**

minSDK can be as low as 23 as discussed in this [comment](https://github.com/fossasia/pslab-android/commit/2946be973ecba6b4af59ed913c8e1d41ab2800cf#commitcomment-142114362)

**Steps to reproduce it**

> None

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

@AsCress would it be possible for you to take this?

**Comment by AsCress** [comment]
Yes sure!!
