### ISSUE TITLE
Wave Generator: layout not really usable in horizontal orientation

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2432]
**Actual Behaviour**

When the Wave Generator screen is used in horizontal orientation, some elements are too small to se or to read the labels on the elements.

**Expected Behaviour**
All UI elements should be easy to use and all labels should be readable. Maybe adding a second layout for horizontal orientation would help.

**Steps to reproduce it**

1. Open app
2. Open Wave Generator screen 
3. Change to horizontal oriientation 

**Screenshots of the issue**
![image](https://github.com/fossasia/pslab-android/assets/11596220/bf754e4a-54db-49c5-b2e4-a7a7ae0603e0)

**Would you like to work on the issue?**
Maybe.

**Comment by AsCress** [comment]
@marcnause @CloudyPadmal I see that most of our layouts don't support horizontal orientation, not just this one. Should we keep them as it is to support only vertical orientation ? Or should we create separate layouts for each of the screens to support horizontal orientation ?

**Comment by marcnause** [comment]
I requested horizontal layouts some time ago (see https://github.com/fossasia/pslab-android/issues/2119). Since I still own the tablet mentioned in the request, I would still love to have horizontal layouts for every screen.

**Comment by AsCress** [comment]
> I requested horizontal layouts some time ago (see #2119). Since I still own the tablet mentioned in the request, I would still love to have horizontal layouts for every screen.

Right, it would be very nice to have horizontal orientation layouts for our screens. I would work on them one by one, starting with the Wave Generator screen, and then we can one by one explore all the other screens (they would also be having several issues on orientation changes as this one).
