### ISSUE TITLE
Wave Generator: seekbar inactive on start of screen even though Freq-button is active

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2442]
**Actual Behaviour**

When the Wave Generator is started, the seekbar at the bottom is inactive, even though the Freq-button is active. The user needs to tap the Freq-button to activate the seekbar.

**Expected Behaviour**

The seekbar should be active and ready to change the frequency since the Freq-button is active.

**Steps to reproduce it**

1. Open app
2. Choose Wave generator

**Screenshots of the issue**

![Screenshot_20240528_210401](https://github.com/fossasia/pslab-android/assets/11596220/fcdaea7d-24eb-4be1-b9bc-8dd0b2803547)

**Would you like to work on the issue?**

Maybe

**Comment by AsCress** [comment]
@marcnause I guess that the seekbar grayed out is a feature to emphasize that nothing is selected at the start and the user has to click on the property he wants to change. According to me, the frequency button should be greyed out instead at the start. Does that sound right ?

**Comment by marcnause** [comment]
Yes, I think that either none of the 3 buttons should be active or the seekbar should be active and set to some default value (e.g. 440 Hz). I am not sure which solution is preferable.

**Comment by AsCress** [comment]
According to me, I think we should prefer to keep all the buttons greyed out in the start and let the user select what he wants to set first.
