### ISSUE TITLE
Wave Generator: phase cannot be selected for first waveform

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2444]
**Actual Behaviour**

If Wave1 (analog wave) or SQR1 (digital wave) is selected, tapping the Phase-button has no effect.

**Expected Behaviour**

If this is due to hardware limitations, then the button should be disabled (greyed out).

If this is not due to hardware limitations, then it should be possible to select phase and change it via the seekbar.

**Steps to reproduce it**

1. Open app
2. Choose Wave Generator
3. Tap Wave1 button
4. Tap Phase button

or

1. Open app
2. Choose Wave Generator
3. Tap Digital button
4. Tap SQR1 button
5. Tap Phase button

**Would you like to work on the issue?**

Maybe

**Comment by AsCress** [comment]
@marcnause As I can see in the code, the phase for Wave1 (analog wave) and SQR1 (digital wave) has purposely been disabled. I am not sure if this is due to hardware limitations.

**Comment by marcnause** [comment]
@AsCress If I find the time, I will dig through the [PSLab Python library](https://github.com/fossasia/pslab-python/tree/development) which is well documented to find out if it is a hardware limitation.

**Comment by marcnause** [comment]
OK, I checked the Python library and the comments in https://github.com/fossasia/pslab-python/blob/development/pslab/instrument/waveform_generator.py were very enlightening:

`Phase between waveforms when generating waveforms on both SI1 and SI2 in degrees. The default is 0.`

The same is true for digital waveforms.

I think it would be a good to color the button grey when it is disabled. Currently it is not possible to tell apart if a button is bright red because it is not in active state or if it is disabled.

**Comment by AsCress** [comment]
Right. I think that we should make the phase buttons invisible for the waveforms which don't support a phase change, to differentiate between _inactive_ and _disabled_. Does that sound right ? @marcnause @CloudyPadmal

**Comment by marcnause** [comment]
@AsCress Sounds good to me.
