### ISSUE TITLE
Oscilloscope: Add new feature for Position Controls

### ISSUE THREAD

**Issue by AsCress** [fossasia/pslab-android#2458]
This is for the addition of the following proposed feature:-

**Horizontal & Vertical Position Controls**:
- Another feature would be to control the horizontal and vertical position of the waveform on the oscilloscope display, for manual measurements.
- The horizontal position control moves the waveform back and forth on the display and can be used to either align the waveform with the horizontal divisions of the display or to view different sections of the waveform.
- The vertical position control moves the waveform up and down on the display and can be used for manual measurements in a similar way as the horizontal position control.

**Actual Behaviour**
Currently, the app doesn't have any such feature to control the position of the waveform.

**Expected Behaviour**
Such a feature is an integral part of dedicated oscilloscope devices, and thus, our app should also be having it.

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
Yes

**Comment by AsCress** [comment]
![Screenshot 2024-06-04 193720](https://github.com/fossasia/pslab-android/assets/125425881/bcd23122-7e2a-47a4-9a76-efb3c398aae2)
@marcnause Just wanted to confirm is there any UI element, such as a button or so, which pops up in the area marked with the red rectangle, when the PSLab Device is connected ? I couldn't see any in the code, I think. Because, if there isn't any element there and the space is free, we can work on an even better layout for the Position Controls feature.

**Comment by marcnause** [comment]
@AsCress You are right, the layout does not change when the PSLab device is connected.

![Screenshot_20240604-222831](https://github.com/fossasia/pslab-android/assets/11596220/41d99073-f8cf-4b9b-acdc-cf4f9ac354bf)
