### ISSUE TITLE
Oscilloscope: Graph doesn't clear after deselecting the In-Built MIC

### ISSUE THREAD

**Issue by AsCress** [fossasia/pslab-android#2460]
**Actual Behaviour**
If one toggles the In-Built MIC ON by clicking on the radio button, and then turns it OFF the same way, the plot of the waveform still remains on the graph.

**Expected Behaviour**
Ideally, the graph should be cleared whenever a channel is turned OFF.

**Steps to reproduce it**

- Turn the In-Built MIC feature ON using the radio button.
- Turn it OFF the same way.
- One would observe that the plot for the input through the MIC is still there on the graph.

**Screenshots of the issue**
The following is a screenshot of the Oscilloscope screen after following the aforementioned steps: -

![Screenshot_20240603_163514](https://github.com/fossasia/pslab-android/assets/125425881/a8b3bc1e-32a7-45b5-9ac7-f0d240c4ebe0)

**Would you like to work on the issue?**
Yes

**Note**
I've found this issue with the In-Built MIC only.
@marcnause Could you please find out if it exists for all the other channels as well ?

**Comment by marcnause** [comment]
@AsCress Yes, same behavior for CH1, CH2, CH3 and PSLab MIC.

![Screenshot_20240603-191820](https://github.com/fossasia/pslab-android/assets/11596220/f34eaeec-56ea-4051-a526-bb570dbc3c68)
![Screenshot_20240603-191840](https://github.com/fossasia/pslab-android/assets/11596220/ef035c0d-84bf-4b7d-9f31-a2d960bfb33a)
![Screenshot_20240603-191929](https://github.com/fossasia/pslab-android/assets/11596220/5975c158-5d05-4218-abe2-ffea91436336)
![Screenshot_20240603-192117](https://github.com/fossasia/pslab-android/assets/11596220/1a0a1807-010f-4b08-aa85-891d1f1792e7)
