### ISSUE TITLE
Use LED icon in Oscilloscope to show the current status of the device

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#247]
**Actual Behaviour**

There is no indication of current status of the device in Oscilloscope.

**Expected Behaviour**

A small green LED icon that flickers every time data is being read. It stops flickering and turn to red if the device is not longer connected.

**Steps to reproduce it**

Menu Drawer -> Applications -> Oscilloscope 

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

**Comment by akarshan96** [comment]
@jithinbp @viveksb007 @asitava1998 @CloudyPadmal, here is the [video link](https://goo.gl/photos/TNCEJk1xiiCrCxAWA). I have added a LED icon which goes from red to green when data is read. Please provide your reviews

**Comment by viveksb007** [comment]
Looks great @akarshan96.
