### ISSUE TITLE
Oscilloscope: Auto Scale problem in combination with new Position Control feature

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2475]
**Actual Behaviour**

Auro Scale does not work as intended if the vertical offset is negative in the new Position Control feature.

**Expected Behaviour**

Auto Scale should take the vertical offset into account and scale the waveform the same no matter if the vertical offset is positive or negative.

**Steps to reproduce it**

0. Connect PSLab device to phone
1. Open app
2. Choose Wave Generator
3. Set frequency for Wave1
4. Start oscilloscope via "play"-button in Wave Generator
5. Enbable CH1
6. Tap "AUTO"
7. Go to "Data Analysis"
8. Set vertical offset for CH1 to positive value
9. Tap "AUTO" --> waveform looking good
10. Set vertical offset for CH1 to negative value
11. Tap "AUTO" --> waveform is too high and cut off partly

**Screenshots of the issue**
### Auto Scale without vertical offset
![Screenshot_20240612-224109](https://github.com/fossasia/pslab-android/assets/11596220/5f80fa7d-0a54-4188-8534-1b07701d6c65)

### Auto Scale with positive vertical offset
![Screenshot_20240612-224129](https://github.com/fossasia/pslab-android/assets/11596220/3945cac1-3eb0-471e-ae2e-a1f6db3ace39)

### Auto Scale with negative vertical offset
![Screenshot_20240612-224222](https://github.com/fossasia/pslab-android/assets/11596220/70725d58-3dbb-40bd-a0bf-395c1f0453d6)

**Would you like to work on the issue?**

Maybe, but @AsCress probably knows better what to do.

**Comment by AsCress** [comment]
@marcnause Just discovered this issue yesterday night 😂. I'll fix this today.
