### ISSUE TITLE
Oscilloscope: Making our fragment layouts more descriptive

### ISSUE THREAD

**Issue by AsCress** [fossasia/pslab-android#2477]
**Actual Behaviour**
Currently in the layouts of the fragments, we don't have any labels for controls. As we go on adding more features in the future, this can cause confusion as to what a particular UI element does.

**Expected Behaviour**
We can add small _TextViews_ in the layouts of the fragments that would make our layouts more descriptive.

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
So, here is how I propose to add the labels:-
- The labels can be added in the places marked with the red boxes -

![Screenshot 2024-06-13 104321](https://github.com/fossasia/pslab-android/assets/125425881/e01a1f80-6663-4b39-b49f-b0ceaf749b77)

![Screenshot 2024-06-13 104407](https://github.com/fossasia/pslab-android/assets/125425881/ee49b638-f893-49a8-903d-0e9fcaff15ff)

- The style of the labels would be as the ones already implemented in the _WaveGeneratorActivity_ -

![Screenshot 2024-06-13 104506](https://github.com/fossasia/pslab-android/assets/125425881/5f68e6bc-4187-450c-9be3-8d78cd95840f)

**Would you like to work on the issue?**
Yes.

Comments on this @marcnause @CloudyPadmal ?

**Comment by marcnause** [comment]
I like your proposal! 👍
