### ISSUE TITLE
Read error during fetchTrace 

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#249]
**Actual Behaviour**

There is read error during fetchTrace. Most probably due to timeout. Due to which chart update on oscilloscope Activity is quite slow.

**Expected Behaviour**

There should be any read error and oscilloscope Activity shouldn't be laggy.

**Steps to reproduce it**

Open oscilloscope Activity and see chart update is quite slow.

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
@akarshan96 @jithinbp There are still read errors. But sometimes I can read complete 1000 sample data i.e 2000 bytes successfully.
[Screencast Link](https://goo.gl/photos/jVM2RSy2CDXx6idJ6)
[APK Link](https://drive.google.com/open?id=0B30IF3fyX4Q3anRwNEJIQldvYXc). @asitava1998 @CloudyPadmal you can also check the apk. Just connect W1 to CH1 before connecting device to Mobile and you should see sine wave. 
Should be move ahead from here?  because root cause for packet drop hasn't been found yet. ( Most probably buffer issue.) Its not Thread related, I checked for single cycle of CaptureTrace and fetchTrace.

**Comment by akarshan96** [comment]
@viveksb007, it's faster now👍 . I am sharing the screenshot.

![screenshot_2017-07-01-02-43-51-201_org fossasia pslab](https://user-images.githubusercontent.com/26146675/27754328-a1717024-5e07-11e7-8898-0acdf36ededb.png)

**Comment by jithinbp** [comment]
Cool :+1:
But the amplitude seems to be +-40V . So either the scaling polynomial isn't right, or there is some issue with the graph. do check please. You can simply log max(ydaya), min(ydata) to know which.
Thanks

**Comment by jithinbp** [comment]
Oh wait. You have set the range to +/-160V, and there is no 10Mohm resistor in series probably, so the amplitude must be around 3.3 V . Sorry.

If you look at the schematic, the input stage is an op-amp in the inverting configuration with RF=200K and Ri = 1M , so gain is 1/5 . When you add a series resistor of 10M , gain becomes 200K/(1M+10M)  , so the slopes of your calibration polynomials must be further divided by a factor of 11 for this  special case

**Comment by viveksb007** [comment]
@jithinbp During unpacking bytes in fetchChannel, I assumed I am getting MSB first then LSB, could you confirm if that's the case?

**Comment by jithinbp** [comment]
No. First LSB, then MSB.
Refer to getInt in this library. 
https://github.com/fossasia/pslab-firmware/blob/master/PSLab_Original/PSLAB_UART.c

**Comment by viveksb007** [comment]
Okay I would change and test it. And also in sequence of bytes when some are dropped then from there unpacking for ```int``` would be wrong. As byte of some other ```int``` would be unpacked with byte of some other ```int```.

**Comment by viveksb007** [comment]
@jithinbp Now after correcting bit unpacking I am getting this.
![screenshot_2017-07-01-12-32-52-789_org fossasia pslab](https://user-images.githubusercontent.com/12713808/27759968-180ec996-5e5a-11e7-8297-e803572f8498.png)

I am doing setSine1(3000)
followed by captureTraces(1, 1000, 10, "CH1", trigger = false, CH123SA = 0)
delay
fetchTrace(1)
What do you think is problem here?

**Comment by jithinbp** [comment]
I think you are working in the wrong voltage range.  
check the setGain function. The programmable gain amplifiers are probably set to +/- 1V range or lower. Signal seems to be getting clipped
Troubleshooting steps
* Check the sine wave output with a separate oscilloscope if you have one. Note Maxima, minima, time period, and shape integrity
* Check Maxima minima of raw data. Since the sine waves are bipolar and readings are 10bit, result should be 512+x, 512-x . If that is not 0,1024 then there is no clipping issue due to PGA, and your problems lie elsewhere.
* Check Maxima minima of polynomial output. It's possible that the constant is not being applied since your plot is unipolar

**Comment by viveksb007** [comment]
Got it working. [Screencast](https://goo.gl/photos/xyc6qWC7tyytF9QM9).
Does slider of **W1** on Hardware overrides frequency of W1 channel?
Could you check the screencast and tell how are things now?
Flow is still same 
setSine1(3000)
followed by captureTraces(1, 1000, 10, "CH1", trigger = false, CH123SA = 0)
delay
fetchTrace(1)

There was some error in Polynomial Initialization and unpacking calibration data. Data is read from device from LSB, so here is should be decoded as Little-Endian.
Little Endian : (byte[0] | (byte[1]<<8))
Big Endian :  (byte[0]<<8) | (byte[1])
[Reference](https://stackoverflow.com/questions/5616052/how-can-i-convert-a-4-byte-array-to-an-integer)
Could you tell if I am going in right direction?

**Comment by jithinbp** [comment]
Cool. Slider on hardware is for amplitude control.

**Comment by CloudyPadmal** [comment]
Fixed in #1069
