### ISSUE TITLE
Applications Fragment UI

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#25]
![screen shot 2017-04-05 at 11 48 27 pm](https://cloud.githubusercontent.com/assets/26146675/24720346/83adf436-1a5a-11e7-9c91-28b94d2959a8.png)

This is a screenshot of the proposed design for Applications Fragment.

**Comment by viveksb007** [comment]
@akarshan96 great looks good to me.

**Comment by mariobehling** [comment]
Excellent.

**Comment by wavicles** [comment]
@akarshan96 Good work :+1:
