### ISSUE TITLE
UI for Control is buggy

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#251]
**Actual Behaviour**

Non-Uniform UI for Control Main

**Expected Behaviour**

Should be uniform for all screens.

**Steps to reproduce it**

Open Control Main

**LogCat for the issue**

NA

**Screenshots of the issue**

![screenshot_2017-06-29-22-46-44-474_org fossasia pslab](https://user-images.githubusercontent.com/12713808/27701244-df96dca8-5d1d-11e7-98b0-ba8e19a7afea.png)

![screenshot_2017-06-29-22-46-58-506_org fossasia pslab](https://user-images.githubusercontent.com/12713808/27701246-e2f255bc-5d1d-11e7-8604-23cceb3dad8f.png)

**Would you like to work on the issue?**

@asitava1998 @CloudyPadmal I think you guys should re-think about your approach to make UI for Control. No need to put everything in same line. You can put everything beautifully in Card-Type View with proper padding of individual elements. Like in arbitrary wavefrom generator in advance control there is no way to set frequency of only W1.

**Comment by asitava1998** [comment]
@viveksb007  @CloudyPadmal The first menu was not like that. Padmal, this happened after you created a separate UI for different screens, so please have a look at what went wrong there.
As of cards, I was thinking to do it like Science Journal did it.  Each separate feature gets a separate card.

**Comment by viveksb007** [comment]
I think its about time we start writing tests too. I don't know so I would have to learn it too.
And from now try to provide an apk for testing with PR and at least 2 devs should test that apk before the PR is merged.
And @CloudyPadmal Please have a look at the issue.

**Comment by asitava1998** [comment]
Yes. That would a good idea to write tests. 
Another thing we could do to know more about the UI is somehow learn how the open-event and phimpme guys did it. They have a good UI and maybe knowing how  it was developed may help a bit.

**Comment by CloudyPadmal** [comment]
Sure @viveksb007 and @asitava1998 ! I'll look into the UI issue in main control panel now! :+1:

**Comment by viveksb007** [comment]
@asitava1998 Their UI also improved over time. We should not condense a lot of view elements together as there are different dimensions in mobile screens. 
@CloudyPadmal Thanks
