### ISSUE TITLE
Multimeter: LA3 and LA4 display wrong frequency values

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2522]
**Actual Behaviour**

The frequency measurements of LA3 and LA4 are not correct in the Multimeter.

**Expected Behaviour**

The Multimeter always displays the correct value for the frequency on all channels.

1. Connect Sine Wave 1 to LA3 or LA4
2. Connect PSLAb to phone
3. Open app (if it has not opened automatically
4. Select Wave Generator
5. Set frequency for Sine Wave 1
6. Change to Multimeter
7. Select LA3 or LA4

**Would you like to work on the issue?**

Maybe

**Additional information**
 I tested with PSLab v5 with firmware version 3.0.2.

**Comment by AsCress** [comment]
@marcnause Could please share screenshots showing what exactly the wrong values of the frequency that you are getting on channels LA3 and LA4 ?

**Comment by marcnause** [comment]
I set the frequency of `Sine Wave 1` to 1000 Hz and connected it to `LA1` first, then to `LA2`, then to `LA3`, and then to `LA4`. Below are the screenshots of the measurements. (PSLab v5, firmware 3.0.2)

<img src="https://github.com/user-attachments/assets/4fc0fc8d-2733-4ec1-aff6-f1d75b90bc58" height=512 />

<img src="https://github.com/user-attachments/assets/1029552b-b785-484a-a6fc-7eb244c80bba" height=512 />

<img src="https://github.com/user-attachments/assets/c6e86464-98a3-440f-be2e-98ac5e795496" height=512 />

<img src="https://github.com/user-attachments/assets/755ae16b-70a5-4b8e-a338-0c3a2ad86d16" height=512 />
