### ISSUE TITLE
Power Source: output of PV1 and PV2 are not changed if set in app

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2525]
**Actual Behaviour**

PV1 and PV2 always stay at the initial value, even if the value is set in the Power Source screen 

**Expected Behaviour**

PV1 and PV2 always output the voltage which is set in the Power Source screen

**Steps to reproduce it**

1. Connect PV1 (or PV2) to CH1
2. Connect PSLab to phone
3. Open app (if it has not opened automatically
4. Go to Power Source
5. Set value of PV1 (or PV2) a value different from the initial value
6. Go to Multimeter
7. Switch to CH1

I also measured with a hardware multimeter and git the same values.

**Additional information**
I tested with PSLab v5 with firmware version 3.0.2.

**Comment by AsCress** [comment]
@marcnause Could you please share the log files when you are trying to set the _Power Source_ values ?

**Comment by marcnause** [comment]
This is the log file: [logcat.txt](https://github.com/user-attachments/files/16576161/logcat.txt)

I flashed the v3.0.2 firmware build from https://github.com/fossasia/pslab-firmware/releases before testing again, but the result was the same as described previously.

**Comment by AsCress** [comment]
@marcnause Thank you very much for providing the logs. I'll test this feature thoroughly and fix this soon in a PR.
