### ISSUE TITLE
Power Supply: Set values have a relatively high offset

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2549]
**Actual Behaviour**

Setting the values of any of the instruments in the Power Supply screen results in values being set which differ from what the user requested. For PV1 I measured an error of up to 0.15 V (for 1.6V on PV1) with a PSLab v5 board. I also set values for PV1 with the Python library and the maximum error was 0.016 V (see attached Libre Office Calc file [Multimeter-2024-08-26 22-30-59-Pass.ods](https://github.com/user-attachments/files/17005830/Multimeter-2024-08-26.22-30-59-Pass.ods)).

Possibly the problem is worse with the v5 board. I did not have the time for extensive testing with the v6 board, but it seems like the error is smaller (0.03 V for 1.6 V on PV1).

**Expected Behaviour**

Setting PV1, PV2 and PV3  in the app should result in an output which has an error which is not significantly higher than setting the value with the Python library.

**Steps to reproduce it**

1. Connect PV1 to CH1
2. Go to Power Supply
3. Set value for PV1
4. Go to Multimeter
5. Measure voltage at CH1
6. Go to 2. and try for different values

**Would you like to work on the issue?**

I already played around a little bit, but to no avail. The next thing I'd try would be to compare the bytes being sent by the app and the Python library for certain voltages.

If anybody would like to have a look, that would be great. I don't know if I'll find enough time for this issue soon.

**Comment by AsCress** [comment]
Thanks @marcnause for the testing and the data. Apparently, there's something fishy in the app causing this. :thinking: Let me have a look.
