### ISSUE TITLE
I would like to purchase your Google Play Console account

### ISSUE THREAD

**Issue by huangzhewei** [fossasia/pslab-android#2553]
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by AsCress** [comment]
Hmmm.... A very interesting "issue" indeed.

**Comment by huangzhewei** [comment]
So are you willing?

**Comment by AsCress** [comment]
By "interesting", I meant one of a kind issue.
As for your question on the Google Play Console account, no thanks !
