### ISSUE TITLE
Scan for sensors always returns list of all sensors

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2595]
**Actual Behaviour**

Scan for sensors always returns list of all sensors, even if no sensor or no PSLab boars is connected.

**Expected Behaviour**

Scan for sensors only returns sensors which are connected to PSLab.

**Steps to reproduce it**

1. Open app
2. Tap "Sensors"
3. Tap "AUTOSCAN"

**Screenshots of the issue**

<img src="https://github.com/user-attachments/assets/03d948dd-b57e-4482-88ac-609efbac1eab" width=400 />

**Would you like to work on the issue?**

No, @AsCress volunteered to take care of this issue. 😉

**Comment by AsCress** [comment]
@marcnause The issue seems to be in the firmware and not in the Android app or the python library (I guess).
I created an issue ticket in the firmware repository (https://github.com/fossasia/pslab-firmware/issues/182).

**Comment by marcnause** [comment]
OK, I will close this issue since it is not caused by the app. Thank you for investigating and for creating the ticket in the firmware repository.
