### ISSUE TITLE
Implement functionalities in Oscilloscope UI

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#260]
**Actual Behaviour**

Some functionalities haven't been implemented in Oscilloscope UI yet

**Expected Behaviour**

Implement the following in Oscilloscope UI

- [x] Timebase 
- [x] Trigger
- [x] Curve Fittings
- [x] Fourier Transform

**Steps to reproduce it**

> None

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
@akarshan96 If this issue is solved. Please close it and open other issue relevant to what's remaining.
