### ISSUE TITLE
port sciencelab.py and expose functionality through ScienceLab class

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#27]

**Comment by akarshan96** [comment]
@viveksb007 let's divide this too.

**Comment by viveksb007** [comment]
@akarshan96 its a single class. I have written most part of it.
You can work on UI part.

**Comment by akarshan96** [comment]
@viveksb007 Okay, I will do it but if you want me to port digital section or analog section in sciencelab.py do tell.

**Comment by viveksb007** [comment]
@mariobehling Please reopen this issue.
I wrote partly fixed in my PR.
