### ISSUE TITLE
Add Toolbar in LogicalAnalyzerActivity

### ISSUE THREAD

**Issue by nikit19** [fossasia/pslab-android#272]
**Actual Behaviour**

There is no toolbar in LogicalAnalyzerActivity

**Expected Behaviour**

A toolbar with a back button and name of the activity should be present

**Steps to reproduce it**

Select the Applications fragment and click on Logical Analyzer.

**LogCat for the issue**

.

**Screenshots of the issue**

Before
![screenshot_20170704-130201](https://user-images.githubusercontent.com/20878145/27820173-20db0f2c-60bb-11e7-994a-9bc6627fd27e.png)

After
![screenshot_20170704-130457](https://user-images.githubusercontent.com/20878145/27820191-32515a5e-60bb-11e7-978d-9606c8316cab.png)

**Would you like to work on the issue?**

Yes I would like to work on this issue.

**Comment by viveksb007** [comment]
Hi @nikit19,
Send a PR for same. Thanks

**Comment by viveksb007** [comment]
Fixed in #275
