### ISSUE TITLE
Create sensor specific UI - HMC5883L & MPU6050

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#279]
**Actual Behaviour**
No sensor specific UI till now. Only a common UI to get raw data.

**Expected Behaviour**
Each sensor should have its own UI for displaying data. 

- [x] Create mock-ups for UI.
- [x] Create the layout files.
- [x] Add functionality

**Steps to reproduce it**
Main Menu -> Applications -> Sensor Quickview

**LogCat for the issue**

None

**Screenshots of the issue**

None

**Would you like to work on the issue?**

Yes.

**Comment by asitava1998** [comment]
The mock-ups for the UIs are [here](https://app.moqups.com/asitavasarkar/Wwr6F3xmaB/view/page/a0def9742).

**Comment by akarshan96** [comment]
@asitava1998 great work 👍

**Comment by CloudyPadmal** [comment]
Nice work @asitava1998 ! :+1:

**Comment by asitava1998** [comment]
@akarshan96 @CloudyPadmal @viveksb007 @jithinbp 
This is what the layout files roughly look like.
<img src = "https://user-images.githubusercontent.com/19410364/28005726-cdc933d2-6569-11e7-9f94-b3e1ba361afd.png" height = "640" width = "360">
<img src = "https://user-images.githubusercontent.com/19410364/28005727-d0dc2778-6569-11e7-9521-22f6dc6a40ea.png" height = "640" width = "360">

The fragment files are also done and changes in layout files can be made to make it look better in subsequent issues.

What should be the transition from Sensor QuickView menu to each of the fragment? Vivek had suggested that we list all the connected sensors in a ListView and on clicking any one of the items we will move to the fragment of that particular sensor. Any other ideas regarding the same or the ListView is final? I have to make changes accordingly.

**Comment by akarshan96** [comment]
@asitava1998 layout looks good to me. You can also try this [link](https://github.com/cachapa/ExpandableLayout), see if this solves the purpose, look for "Accordion" expansion.

**Comment by viveksb007** [comment]
Looks great.
Graph under Plot Section could be made collapseable.

**Comment by asitava1998** [comment]
@akarshan96 @viveksb007 What about the transition from activity to each fragment? When `AutoScan` is clicked, the sensors available are displayed, so should they be arranged in a listview, accordion etc. and on clicking we move to the selected fragment?

**Comment by viveksb007** [comment]
ListView is okay for now. Rest if you have any better option in mind go ahead.

**Comment by CloudyPadmal** [comment]
So all the sensors are listed in a ListView and when clicked upon, each will open up a new fragment right?

**Comment by asitava1998** [comment]
@CloudyPadmal That's the initial thought. If you have a better idea, let me know.

**Comment by viveksb007** [comment]
Fixed in #295
