### ISSUE TITLE
App crash on setting Voltage/Current  from Control Main

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#286]
**Actual Behaviour**

When **SET** button is pressed and device is connected, App crashes. 

**Expected Behaviour**

App shouldn't crash instead whatever voltage/current is specified in EditText should be set. 

**Steps to reproduce it**

Connect Device and try to set Voltage/Current. 

**LogCat for the issue**

NA, Activity is restarted so error Logs aren't captured.

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
@asitava1998 Did you tested PVX, PCS with device after adding setVoltage / setCurrent calls ?

**Comment by asitava1998** [comment]
No, I hadn't tested it. I left it commented but few days back someone (can't remember who did) uncommented and slightly modified some of the code in Control Main, so didn't test it.

**Comment by viveksb007** [comment]
No problem. I would debug it. But from next time review PR carefully and raise question if you find something that can potentially result in app crash.
