### ISSUE TITLE
Home Fragment UI

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#30]
![screen shot 2017-04-06 at 11 16 41 pm](https://cloud.githubusercontent.com/assets/26146675/24770803/dd83f3b0-1b28-11e7-8e9f-6bf25376822e.png)

This is a proposed design for Home Fragment UI. The following things will be implemented
- Pinch Zoom
- Improvement in the quality of the image of the PIN Diagram and the description of the PINs.

**Comment by asitava1998** [comment]
Add support for a retry/refresh button in case of the app fails to recognize the device or the device is connected after opening the app when device not found is displayed.

**Comment by viveksb007** [comment]
@asitava1998 Please open a new issue for this. And tell us if you would like to work on it.
