### ISSUE TITLE
Buttons in 'Sensor QuickView' do not implement selectors

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#302]
**Actual Behaviour**

Buttons in `Sensor QuickView` do not implement selectors.

**Expected Behaviour**

Buttons should have an effect on clicking to show that the button is pressed.

**Steps to reproduce it**

1. Open app
2. Go to `Applications`
3. Choose `Sensor QuickView`
4. Click the buttons and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![screen](https://user-images.githubusercontent.com/14261304/28120875-ebf480f8-674b-11e7-8a7d-5217831f0cf8.png)

**Would you like to work on the issue?**

Yes

**Comment by asitava1998** [comment]
Don't do it for the `Get raw` button though, it is being removed anyway.

**Comment by CloudyPadmal** [comment]
Sure @asitava1998 ! :+1:
