### ISSUE TITLE
Autogenerate app in apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#31]
Please create an apk branch and autogenerate the app here on each build. Please ensure the previous apks are not saved in the history to ensure the repository is not getting super big.

Follow the way it is done for open event android and ask in the open event android channel for help, if needed.

**Comment by mariobehling** [comment]
Issue not solved yet.

**Comment by viveksb007** [comment]
@mariobehling could you add Authentication token as Environment Variable "GITHUB_API_KEY".
There is authentication problem as can be seen from travis log
![screenshot from 2017-04-08 17-38-17](https://cloud.githubusercontent.com/assets/12713808/24828784/031b0b94-1c83-11e7-8bc7-95a99563b8c1.png)

We need Authentication token as GITHUB_API_KEY as can be seen here 
![screenshot from 2017-04-08 17-41-24](https://cloud.githubusercontent.com/assets/12713808/24828789/24044b0e-1c83-11e7-8b0b-805b87bfedcb.png)

This should solve the problem.

**Comment by mariobehling** [comment]
![screenshot from 2017-04-08 14-45-24](https://cloud.githubusercontent.com/assets/1583873/24829002/1ead6bb0-1c40-11e7-855b-595f8a0413c5.png)

Actually you also need a key for the deployment of the branch. 

Please set this up and share the keys with me in private mail.

Cheers.

**Comment by viveksb007** [comment]
@mariobehling could you add fossasia github token to travis build settings, my keys won't work as i don't have push access to fossasia's github repo and also change username from wavicles to fossasia in https://github.com/fossasia/pslab-android/blob/master/upload-apk.sh#L13.

Phimpme Android also has fossasia's token in their script as can be seen here.
https://github.com/fossasia/phimpme-android/blob/development/upload-apk.sh#L13

Thanks

**Comment by viveksb007** [comment]
@mariobehling  I think we can close this issue as apk in generated in apk branch on any commit to master branch.
