### ISSUE TITLE
Add more functionality to Sensor fragments

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#339]
**Actual Behaviour**

Currently, Sensor fragments don't have all the functionalities.

**Expected Behaviour**

Sensor fragments should have

- [ ] Pause/record button
- [ ] Time gap between each data point option
- [ ] No. of data points to be recorded option

**Steps to reproduce it**

Menu Drawer -> Applications -> Sensor QuickView -> HMC5883L 

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

**Comment by akarshan96** [comment]
@jithinbp @asitava1998 @viveksb007 @CloudyPadmal, I am sharing a mockup for control bar in Sensor activity. I have added 

1. a common play and pause button. 
2. a seek-bar to determine the time gap between each data point capture.
3. an edit-text box in which no. of samples to be captured can be entered.
4. a checkbox when checked will capture data indefinitely. This will disable the edit-text box.

Please review it and give suggestions.

![screen shot 2017-07-23 at 8 52 06 pm](https://user-images.githubusercontent.com/26146675/28500980-fe326f44-6fef-11e7-9f79-1d177b306b25.png)

**Comment by viveksb007** [comment]
@akarshan96 Looks great. Instead of using TextView and EditText for taking Number of samples use ```TextInputEditText``` wrapped inside ```TextInputLayout```. Refer [this](https://github.com/fossasia/pslab-android/blob/master/app/src/main/res/layout/diode_configure_dialog.xml#L17).

**Comment by viveksb007** [comment]
@akarshan96 Please update the Issue description about what has been achieved and if anything is remaining, please open a sub-issue.
