### ISSUE TITLE
Improve Sensor UI and Remove Inconsistencies

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#371]
**Actual Behaviour**
The current layout in sensor files are uniform but has some limitations like inconsistent text sizes, inadequate widths for some elements etc.

**Expected Behaviour**
The layout for all the sensor files should be uniform and should be identical for all screen sizes

**Steps to reproduce it**
Main Menu -> Applications -> Sensor Quickview -> AutoScan + Select Sensor 

**LogCat for the issue**
`Example`
<img src="https://user-images.githubusercontent.com/19410364/28451177-575f974c-6e09-11e7-96a2-0f84c42e779a.png" height="640" width="360">
<img src="https://user-images.githubusercontent.com/19410364/28451198-86700e0e-6e09-11e7-8ed7-d2648f383d29.png" height="640" width="360">

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

**Comment by viveksb007** [comment]
Fixed in #377
