### ISSUE TITLE
Modify the Sensor Activity Layout

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#379]
**Actual Behaviour**
The present layout is non-intuitive and just contains an `AutoScan` button, a Textbox and of whitespace as the ListView is displayed when sensors are detected.

**Expected Behaviour**
* In addition to `AutoScan`, a feature to automatically detect any connected sensors when Sensor QuickView is opened.
* Modify the style of text displayed in the textbox.

**Steps to reproduce it**
Main Menu -> Applications -> Sensor QuickView

**LogCat for the issue**
None

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/19410364/28672034-26ac3c2a-72fc-11e7-9881-afc20e969a04.png" height="640" width="360">

**Would you like to work on the issue?**
Yes

**Comment by viveksb007** [comment]
Fixed in #389
