### ISSUE TITLE
Implement Wave generator functionality using AudioJack

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#416]
**Actual Behaviour**

No Wave can be generated using Audio Jack.

**Expected Behaviour**

Implement Wave Generation Functionality using Audio Jack. More details in this [doc](https://docs.google.com/document/d/1plDelUJ1EwQj5P7ZP0R61cQawPIn-qdFZlBynvKM4wM/edit?usp=sharing).

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
#1165
