### ISSUE TITLE
Implement Half Wave Rectifier Experiment

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#446]
**Actual Behaviour**

Half Wave Rectifier Experiment is not yet implemented.

**Expected Behaviour**

Half Wave Rectifier Experiment needs to be implemented

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Select `Electronics Experiments`
4. Select `Diode IV Characteristics`
5. Select `Half Wave Rectifier`

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

**Comment by akarshan96** [comment]
@viveksb007 @asitava1998 @CloudyPadmal for implementing Half Wave Rectifier Experiment, I have reused Oscilloscope Activity. Sharing the screenshot. Please give suggestions on this.
![screenshot_1502159911](https://user-images.githubusercontent.com/26146675/29055039-ad9aa8e2-7c17-11e7-8fed-786b3d02b684.png)

**Comment by CloudyPadmal** [comment]
This will be great! :+1:

**Comment by viveksb007** [comment]
Looks good.
We don't need right Y-axis.

**Comment by jithinbp** [comment]
@viveksb007 There will be two plots (CH1 : complete wave,  CH2 : rectified ) . If you remove the right axis, the left axis label should not be simply 'CH1 (V)' .

We can also simplify this experiment by removing timebase and frequency configuration options. Simply use a fixed frequency, and display it prominently at the bottom. It's just a suggestion. For beginners, too much flexibility can be confusing.

**Comment by akarshan96** [comment]
@jithinbp made the suggested changes. Sharing the screenshots. @viveksb007 @asitava1998 @CloudyPadmal please give your reviews too.

![screenshot_2017-08-08-20-31-43-088_org fossasia pslab](https://user-images.githubusercontent.com/26146675/29078894-43328bfc-7c79-11e7-92c2-140e0b555eb3.png)

**Comment by akarshan96** [comment]
I have made the suggested changes. @jithinbp @viveksb007 @asitava1998 @CloudyPadmal please review it.
![screen shot 2017-08-08 at 9 17 43 pm](https://user-images.githubusercontent.com/26146675/29081037-146c8fa6-7c7f-11e7-9d9b-3f2ed2acb440.png)

**Comment by jithinbp** [comment]
Is there some issue with CH2 on your device? It shouldn't be at ~6V unless you've connected something to it. Can you use a diode from the accessory kit to make a screenshot of the halfwave experiment?
