### ISSUE TITLE
Implement Inverting Op-Amp Experiment

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#450]
**Actual Behaviour**
Inverting Op-Amp (Operational Amplifier) experiment is not yet implemented

**Expected Behaviour**
Inverting Op-Amp experiment needs to be implemented

**Steps to reproduce it**
1. Open app
2. Go to `Saved Experiments`
3. Select `Electronics Experiments`
4. Select `OpAmp circuits`
5. Select `Inverting Op-Amp`

**LogCat for the issue**
> None

**Screenshots of the issue**
> None

**Would you like to work on the issue?**
Yes

**Comment by viveksb007** [comment]
Fixed in #506
