### ISSUE TITLE
Add build instructions to compile and download standalone APK files

### ISSUE THREAD

**Issue by jithinbp** [fossasia/pslab-android#46]
The source has been tested with Android Studio 2.3.1 with Gradle 3.2, and builds without errors once a few dependencies have been synced. However, automatic Download & execution failed. 
Device: Xiaomi Redmi 3S + , Android Version 6.0.1 MMB29M, MIUI : Global 8.2 |Stable

![as_err1](https://cloud.githubusercontent.com/assets/6078658/25040636/487efe30-2128-11e7-8382-1adba7291ff1.png)

Console Output
```
04/14 15:38:33: Launching app
$ adb install-multiple -r /home/jithin/ACTIVE_PROJECTS/PSLab/pslab-android/app/build/outputs/apk/app-debug.apk /home/jithin/ACTIVE_PROJECTS/PSLab/pslab-android/app/build/intermediates/split-apk/debug/slices/slice_4.apk ... [Truncated]  ... slice_3.apk 
$ adb shell pm uninstall org.fossasia.pslab
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APKs
```
The uninstall process causes it to fail , but the Apk can be installed via adb separately. Using the 'build apk' command creates app-debug.apk , so please add instructions on building a standalone Apk
$ adb install -r app-debug.apk

This App will wait for the debugger to attach ( Can be launched separately via Android Studio), and then displays the Home page.

I will try to test on a few other Android devices to check if the uninstallation failure is not an MIUI specific issue.

**Comment by viveksb007** [comment]
@jithinbp you might have upgraded gradle version to 2.3.0.
Change project level gradle version in build.gradle file to 2.2.3 and this should be solved.
