### ISSUE TITLE
Implement Diode IV Characteristic Experiment

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#495]
**Actual Behaviour**

Diode IV Characteristic Experiment is not yet implemented.

**Expected Behaviour**

Diode IV Characteristic Experiment needs to be implemented

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Select `Electronics Experiments`
4. Select `Diode Circuits`
5. Select `Diode IV Characteristic`

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
Fixed in #507
