### ISSUE TITLE
N-FET Transfer Characteristics experiment missing

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#497]
**Actual Behaviour**

Experiment setup in `N-FET Transfer Characteristics` experiment doesn't work

**Expected Behaviour**

Experiment setup should display it as it was already implemented

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Select `Electronics Experiments` --> `BJTs and FETs`
4. Click on `N-FET Transfer Characteristics` and observe its experiment setup

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
Fixed in #505
