### ISSUE TITLE
Use string resources for halfwave rectifier experiment call

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#498]
**Actual Behaviour**

`PerformExperimentAdapter` uses hardcoded string in method call

**Expected Behaviour**

Need to use string resources instead

**Steps to reproduce it**

[PerformExperimentsAdapter](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java#L92)

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
Fixed in #504
