### ISSUE TITLE
faulty polynomial implementation in DACChannel.java

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#51]
In DACChannel.java coefficients for 0 & 1 are put [see here](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/communication/peripherals/DACChannel.java#L29)
And in MCP4728 coefficient for 2 is queried [see here](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/communication/peripherals/MCP4728.java#L63), as its put in a map, it would return null and null in mathematical operation would raise error.

**Comment by akarshan96** [comment]
@viveksb007 thanks. I got that, going to resolve it.

**Comment by keshcode** [comment]
i would like work on this issue

**Comment by viveksb007** [comment]
@keshcode thanks for showing interest in this project.
Feel free to suggest or implement ways in which we can implement polynomial efficiently in java ( numpy.poly1d() in python ).
You can discuss your approach at our gitter channel https://gitter.im/fossasia/pslab
The python communication library is at https://github.com/fossasia/pslab-python

**Comment by akarshan96** [comment]
@viveksb007 I have solved the issue but when I am making a pr, the previous commits which are already merged are also being displayed there. I have tried solutions mentioned on the net but still facing this issue. Should I still make a pr ?

**Comment by viveksb007** [comment]
Its most probably because wavicles might have rebased the commits.
As the changes are quite less, you can edit that on github only. would save duplicate commit.

**Comment by akarshan96** [comment]
@viveksb007 Thanks.
