### ISSUE TITLE
Implement a uniform button in saved experiments

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#521]
**Actual Behaviour**

The application uses a selector for its button background in control UI, Oscilloscope and Data sensor logger. But in saved experiment, stock button is used which is gray in color

**Expected Behaviour**

App needs to implement a uniform button everywhere in the application

**Steps to reproduce it**

Observe experiments related buttons in `Saved Experiments`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

| Other Screen | Saved Experiments |
| ---- | ---- |
| ![control](https://user-images.githubusercontent.com/14261304/29319664-5732ab6c-8207-11e7-8c1c-9f497e5fa1e3.png) | ![experiment](https://user-images.githubusercontent.com/14261304/29319696-6be03d0e-8207-11e7-8c38-226f546c4133.png) |

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
@CloudyPadmal stock button looks better in my opinion.
Making all buttons ```RED``` doesn't make the app look good.

**Comment by CloudyPadmal** [comment]
Hi @viveksb007 ! My suggestion is to implement the same theme through out the app. What do you think? :)

**Comment by vikasmahato** [comment]
@CloudyPadmal   @viveksb007 Can I work on this one??

**Comment by CloudyPadmal** [comment]
Sure! :+1:

**Comment by sharmamohit123** [comment]
@CloudyPadmal  I also want to work on this issue.

**Comment by CloudyPadmal** [comment]
Sure go ahead @sharmamohit123 ! 👍

**Comment by CloudyPadmal** [comment]
Fixed in #714
