### ISSUE TITLE
Implement Phase Shift Oscillator

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#527]
**Actual Behaviour**

Phase Shift Oscillator Experiment is not yet implemented.

**Expected Behaviour**

Phase Shift Oscillator Experiment needs to be implemented

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Select `Electronics Experiments`
4. Select `Oscillators`
5. Select `Phase Shift Oscillator`

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
Fixed in #532
