### ISSUE TITLE
export logged sensor data in a text file

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#534]
**Actual Behaviour**

currently we can export logged data.

**Expected Behaviour**

App should export logged data to share text file, etc.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Hi @viveksb007 ! Can the app log data in .csv format too?

**Comment by viveksb007** [comment]
We can export data however we want, just need to add support for it. `.csv` sounds good, would add support for it after exporting in raw `.txt` format.

**Comment by CloudyPadmal** [comment]
Exactly! I was going to propose `.csv` because that is useful in many other applications such as matlab...
