### ISSUE TITLE
Improve UI and implement it according to material design specificatons

### ISSUE THREAD

**Issue by vikasmahato** [fossasia/pslab-android#551]
Currently the UI of the applications is very rudimentary and there is a scope for a better UI. This will improve user experience.

**Comment by vikasmahato** [comment]
Can I work on this??

**Comment by viveksb007** [comment]
@vikasmahato sure go ahead.
Put screenshots of any improvements you made and better if you could put it on gitter channel for community to approve and review.
Thanks

**Comment by Avjeet** [comment]
I want to work on this.

**Comment by CloudyPadmal** [comment]
Experiments have been moved to pslab-experiments
