### ISSUE TITLE
Implement Amplitude Modulation Experiment

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#578]
**Actual Behaviour**

Amplitude Modulation Experiment is not yet implemented.

**Expected Behaviour**

Amplitude Modulation Experiment needs to be implemented

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Select `Communication`
5. Select `Amplitude Modulation`

**LogCat for the issue**

> None

**Screenshots of the issue**

> None

**Would you like to work on the issue?**

Yes

**Comment by NamanRawat1** [comment]
Can I work on this?

**Comment by CloudyPadmal** [comment]
Experiments have been transferred to pslab-experiments
