### ISSUE TITLE
demonstrate experiments with PSLab hardware device

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#586]
**Actual Behaviour**

Experiments are implemented, but there are no demos on how we should perform the experiment. There are experiment docs with schematics and basic theory.

**Expected Behaviour**

There should be some video demonstration of experiments and a brief description in text that how experiments can be performed, similar to help files in PSLab Desktop App. List of experiments for which demo should be there 
- [ ] N-FET related  experiments
- [ ] BJT related experiments
- [ ] Diode related  experiments
- [ ] Half-Wave and Full Wave rectifier
- [ ] Op-Amp related  experiments
- [ ] Ramp Generator
- [ ] Oscillator related experiments
- [ ] Ohm's law experiment
- [ ] RLC response
- [ ] RC phase shift 
- [ ] LR phase shift
- [ ] Capacitive and Inductive reactance
- [ ] Random Sampling
- [ ] Pendulum related experiments
- [ ] Measure voltages
- [ ] Lemon Cell
- [ ] AC generator
- [ ] Resistance Measurement
- [ ] Human Body Resistance
- [ ] Electromagnetic Induction
- [ ] Resistance of water
- [ ] Frequency of sound
- [ ] Capacitance Measurement
- [ ] Capacitor Discharge
- [ ] Light Dependent Resistor
- [ ] Ultrasonic Range Finder

**Comment by asitava1998** [comment]
About the written part, I think we should make a common template and write the experiment description and procedure according to it.

**Comment by mariobehling** [comment]
Moving this here https://github.com/fossasia/pslab-experiments/issues/24
