### ISSUE TITLE
Implement Curve fitting in Oscilloscope

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#613]
**Actual Behaviour**

Curve fitting is not implemented in Oscilloscope yet.

**Expected Behaviour**

Curve fitting should be implemented in Oscilloscope yet.

**Steps to reproduce it**

Applications -> Oscilloscope

**LogCat for the issue**

None

**Screenshots of the issue**

None

**Would you like to work on the issue?**

Yes

**Comment by Vikum94** [comment]
@akarshan96 I would like to work on this issue. Are you still working on it?

**Comment by CloudyPadmal** [comment]
@Vikum94 you can continue!

**Comment by akarshan96** [comment]
@Vikum94 let me give you a brief about what I had done but wasn't successful. For Sine Fit function in [AnalyticsClass.java](https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/org/fossasia/pslab/communication/AnalyticsClass.java#L120) needs to be used. This function will return Amplitude, Frequency, Offset and Phase, these parameters then put into **Amplitude * sin(Frequency * time + Phase) + Offset** . But when I was trying it with the dataset which I received from the PSLab device itself I was getting inaccurate results. You give it a try too, let me also look into this issue again.
Maybe [this](https://github.com/akarshan96/pslab-android/commit/b70b61b3d88aaf480ebfb0e7ca3389512b8cb803#diff-000cee686dfe0defeb32ee0728dfbe95R503) will help you 
Cheers.

**Comment by CloudyPadmal** [comment]
Thank you @akarshan96 for the heads up! :)

**Comment by Vikum94** [comment]
Thank you very much! @akarshan96 Will see what I can do.
