### ISSUE TITLE
update app screenshots in the readme

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#624]
**Actual Behaviour**

currently app screenshots in readme are old.

**Expected Behaviour**

App screenshots in readme should be updated.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Comment by nikit19** [comment]
I would like to work on this issue if nobody is working on it

**Comment by viveksb007** [comment]
@nikit19 sure go ahead :+1:
