### ISSUE TITLE
No action bar in "About Us" activity

### ISSUE THREAD

**Issue by NamanRawat1** [fossasia/pslab-android#630]
**Actual Behaviour**
No action bar in About Us activity.
**Expected Behaviour**
There must be action bar in this activity like others activity with label About Us.

**Steps to reproduce it**
1.Open navigation Bar
2.Go to about us.

**Screenshots of the issue*
![about us](https://user-images.githubusercontent.com/21363531/30507844-e2acb04e-9aa7-11e7-9d44-eff0f82c3999.jpg)

**Would you like to work on the issue?**
YES.

**Comment by NamanRawat1** [comment]
Can I work on this?

**Comment by CloudyPadmal** [comment]
Sure!! You may!! :)

**Comment by viveksb007** [comment]
I don't think it needs an `ActionBar` with `About Us` written on it. Its pretty obvious when user clicked from `Nav Drawer`. Plus App don't have `ActionBar` in `About Us` Page.

**Comment by NamanRawat1** [comment]
ok and also there is no navigation bar in this activity due to which user has to press back button to reach other activity.Is there a need for navigation view in this activity?

**Comment by viveksb007** [comment]
@NamanRawat1 its an Activity. It can't have incorporate NavigationView of the MainActivity unless you replicate complete view of Main Activity. So I think we can go with `ActionBar` approach to take user to `MainActivity`. Please add an ActionBar with title `About PSLab`.
Thanks.

**Comment by NamanRawat1** [comment]
All views of about us activity is from a string file. When I create a view for the toolbar in about us activity then two child element will clash. Is there any possible way to fix this problem? @viveksb007

**Comment by viveksb007** [comment]
One way can be that you create a Root Layout(LinearLayout) with (`Toolbar` and `LinearLayout`) as children and add `aboutPage` view in the LinearLayout.
Hope the solution is clear.

**Comment by viveksb007** [comment]
@NamanRawat1 Any updates on solving the issue? Should I send a PR if its not solved by you yet?

**Comment by NamanRawat1** [comment]
just send pull request for it review it @viveksb007

**Comment by viveksb007** [comment]
Fixed in #646
