### ISSUE TITLE
Implement Measure Voltages Experiment

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#631]
**Actual Behaviour**

`Measure Voltages` experiment under saved experiments hasn't been implemented yet

**Expected Behaviour**

The experiment needs to be implemented

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Browse to `School Level` and try `Measure Voltages` experiment

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

If a new developer wants to take on this issue, can proceed with it! Otherwise I'll resolve this! :)

**Comment by NamanRawat1** [comment]
Will I make a try on this?

**Comment by CloudyPadmal** [comment]
Yea sure! :D

**Comment by NamanRawat1** [comment]
![measuringvoltage](https://user-images.githubusercontent.com/21363531/30521992-be7e4256-9be6-11e7-8858-b805158b871f.jpg)









How can i resolve this?

**Comment by asitava1998** [comment]
@NamanRawat1  The doc is in markdown format. So, you need to use the `ExperimentDocMdFragment` so that this file is rendered by MarkdownView

**Comment by NamanRawat1** [comment]
I already return ExperimentDocMdFragment in PerformExperimentAdapter.java. But it's not working.Can I post the code of this java file in the comment?

**Comment by asitava1998** [comment]
@NamanRawat1  Push the code in your fork of this repository and give us the link of the same. We can suggest the changes there.

**Comment by NamanRawat1** [comment]
https://github.com/NamanRawat1/pslab-android/commit/8964f0a0ef115b249706e5d5a2933830abc5d9fc

**Comment by NamanRawat1** [comment]
![voltage](https://user-images.githubusercontent.com/21363531/30529845-5fe4bada-9c5f-11e7-9123-71d62fee0fef.jpg)


Its working now can I send a pull request

**Comment by asitava1998** [comment]
@NamanRawat1 Sure. Go ahead 👍

**Comment by asitava1998** [comment]
Fixed in PR #633
