### ISSUE TITLE
Implement Resistance Measurement Experiment

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#632]
**Actual Behaviour**

`Resistance Measurement` experiment under saved experiments hasn't been implemented yet

**Expected Behaviour**

The experiment needs to be implemented

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Browse to `School Level` and try `Resistance Measurement` experiment

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

If a new developer wants to take on this issue, can proceed with it! Otherwise I'll resolve this! :)

**Comment by avish12** [comment]
shall I implement it?

**Comment by CloudyPadmal** [comment]
Definitely! :)

**Comment by avish12** [comment]
where can I find Experiment docs and Setup details?

**Comment by CloudyPadmal** [comment]
Hi @avish12 ! You can find the resources from following links;
- [Python Implementation](https://github.com/fossasia/pslab-desktop-apps/tree/development/psl_res/GUI)
- [Documentation](https://github.com/fossasia/pslab-desktop-apps/tree/development/docs/_apps)
- [Android folders](https://github.com/fossasia/pslab-android/tree/development/app/src/main/java/org/fossasia/pslab/experimentsetup)

Hope that helps! :)

**Comment by NamanRawat1** [comment]
Where is Measuring voltage experiment details in these document? I don't find it in documentation.

**Comment by asitava1998** [comment]
@avish12 You can also have a look at the older PRs for experiments. They would give you the best idea

**Comment by NamanRawat1** [comment]
@avish12  Are you working on this?

**Comment by shikhart98** [comment]
Can I work on it?

**Comment by asitava1998** [comment]
@avish12 @NamanRawat1 @shikhart98  Please resolve among yourselves who wants to work on this. Next time onwards if someone wants to work on an issue, assign yourself to that issue. The `assignees` section is at the top right. If the issue has been already assigned to someone, no one else can claim it.

**Comment by NamanRawat1** [comment]
The issue is first given to @avish12  if he will not work on it then I will take it. Is that fine? @shikhart98

**Comment by shikhart98** [comment]
Yea Sure!

**Comment by avish12** [comment]
@shikhart98 if you want, you can work on it.

**Comment by NamanRawat1** [comment]
@shikhart98 I already worked on the same type of issue you can work on it.

**Comment by shikhart98** [comment]
Okay thanks!

On Sep 25, 2017 9:52 PM, "Naman Rawat" <notifications@github.com> wrote:

@shikhart98 <https://github.com/shikhart98> I already worked on the same
type of issue you can work on it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/pslab-android/issues/632#issuecomment-331935101>,
or mute the thread

**Comment by shikhart98** [comment]
Sir can you please guide me with this issue. I'm a noob and new to open
source. I know JAVA and data structures/algos for now!

**Comment by NamanRawat1** [comment]
Can I work on this issue if you are not working on it?  @shikhart98

**Comment by sagarbaba** [comment]
I am working on this.

**Comment by harsh-2711** [comment]
I have made it.. soon starting a PR

**Comment by harsh-2711** [comment]
Also few others are completed by me. Will file PR by tomorrow

**Comment by sagarbaba** [comment]
Leave this one for me.

**Comment by harsh-2711** [comment]
Have u made the experiment for resistance measurement in python @sagarbaba

**Comment by sagarbaba** [comment]
its already there in desktop app,

**Comment by harsh-2711** [comment]
I mean have you implemented it in your PR. Or you have only made only the experiment setup tab

**Comment by harsh-2711** [comment]
I have made both and is completely ready. I am getting it reviewed

**Comment by CloudyPadmal** [comment]
Issues related to experiments will be considered once the Android app is functional
