### ISSUE TITLE
reformat experiment heading and sub-heading in md experiment docs

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#634]
**Actual Behaviour**

Currently Heading, Sub-heading, titles all are of same type.  

**Expected Behaviour**

There should be difference Font size of Title, Heading, Sub-heading, etc.  

**Steps to reproduce it**

Any experiment doc of MD files.

**LogCat for the issue**

NA

**Screenshots of the issue**

![](https://user-images.githubusercontent.com/21363531/30577353-45f9749a-9d2b-11e7-8e89-3b4bd503986b.jpg)

**Would you like to work on the issue?**

For new devs.

**Comment by NamanRawat1** [comment]
Can I work on this?

**Comment by viveksb007** [comment]
Sure go ahead :+1:

**Comment by viveksb007** [comment]
@NamanRawat1 any updates on the issue?

**Comment by NamanRawat1** [comment]
when changing headings from h2 to h1 font size in main.css no change occurs.Trying to fix it.

**Comment by viveksb007** [comment]
Now `md` files are rendered, so make change in `md` files, it would reflect in webView. We are actually shifting `html` files to `md` files, once thats completed, all `html` files would be removed.
