### ISSUE TITLE
Report issues website opens in browser

### ISSUE THREAD

**Issue by nikit19** [fossasia/pslab-android#641]
**Actual Behaviour**

When we click on report issues it opens up in browser which is slow.

**Expected Behaviour**

We should use custom tabs to open the website so that it happens quickly.

**Steps to reproduce it**

Open the app and click on Report issues from the drawer.

**Would you like to work on the issue?**

Yes!

**Comment by CloudyPadmal** [comment]
Hi @nikit19 ! Can you elaborate more on the fix you're suggesting?

**Comment by nikit19** [comment]
Hi @CloudyPadmal  If we use Chrome custom tabs the website could open much  faster. What do you think about it? https://developer.chrome.com/multidevice/android/customtabs

**Comment by nikit19** [comment]
@CloudyPadmal It would look like this
![screenshot_20170928-162833](https://user-images.githubusercontent.com/20878145/30963284-85ac52ec-a46a-11e7-94be-0e5eda4cd50f.png)

**Comment by CloudyPadmal** [comment]
Great! :D You can send a PR when done! :+1:
