### ISSUE TITLE
The logo is not visible/clear  with dark themed phones

### ISSUE THREAD

**Issue by Arshilgenius** [fossasia/pslab-android#645]
**Actual Behaviour**

The logo is not visible  because it's completely black and it should be changed to some other colour.

**Screenshots of the issue**

<img src= https://user-images.githubusercontent.com/21264401/30983790-1278a502-a4a9-11e7-90d2-5300fa967b5a.jpeg width="300" height="500">

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
@Arshilgenius Please refer Issue https://github.com/fossasia/pslab-artwork/issues/1

**Comment by Arshilgenius** [comment]
@viveksb007  okay, should i close this issue?

**Comment by viveksb007** [comment]
Nope you can leave it open. Once you create an Icon. Please post on our [gitter](https://gitter.im/fossasia/pslab) channel for review by community. And then you can send a PR here.
