### ISSUE TITLE
nav_header_main is not centre aligned

### ISSUE THREAD

**Issue by nikit19** [fossasia/pslab-android#648]
**Actual Behaviour**

Currently nav_header_main is not centre aligned which doesn't look good.

**Expected Behaviour**
nav_header_main should be centre aligned

**Steps to reproduce it**

Open the app and look at the navigation drawer

**Screenshots of the issue**

**Before**
![screenshot_20170929-163011](https://user-images.githubusercontent.com/20878145/31013421-a8ef6a5e-a533-11e7-88fc-cb8cd3cb66cc.png)

**After**
![screenshot_20170929-162703](https://user-images.githubusercontent.com/20878145/31013432-b4e532bc-a533-11e7-9fb8-00518f8e7782.png)

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Hi @nikit19 ! Current implementation follows [material guidelines](https://material.io/guidelines/patterns/navigation-drawer.html#)! I don't think this is necessary!

**Comment by nikit19** [comment]
@CloudyPadmal  okay I'll close the issue
