### ISSUE TITLE
Add links for demo video in readme

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#650]
**Actual Behaviour**

No link for demo video of Android App with PSLab device.

**Expected Behaviour**

We should add YouTube video demos links which were created during gsoc, so new devs could understand device better. 

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
@CloudyPadmal @asitava1998 @akarshan96 what do you guys think?

**Comment by akarshan96** [comment]
@viveksb007 sure we can do this 👍
