### ISSUE TITLE
OscilloscopeActivity doesn't rotate on screen rotation

### ISSUE THREAD

**Issue by nikit19** [fossasia/pslab-android#652]
**Actual Behaviour**

OscilloscopeActivity remains fixed on screen rotation

**Expected Behaviour**

It should remain in landscape mode but allow the user to rotatate the screen if the user desires to do so

**Steps to reproduce it**

Open the app. Select applications and click on Oscilloscope

**Would you like to work on the issue?**

Yes

**Comment by akarshan96** [comment]
@nikit19 we have decided to keep Oscilloscope in Landscape mode only. This ensures maximum area to graphs.
Cheers

**Comment by nikit19** [comment]
@akarshan96  yes it should be in landscape mode. But what I meant is it should allow rotation in landscape mode.  What do you think ?

**Comment by CloudyPadmal** [comment]
Hi @nikit19 ! That would be fine I guess; rotating only in landscape modes. Send a PR when ready! :+1:
