### ISSUE TITLE
Alert dialog before closing the app 

### ISSUE THREAD

**Issue by NamanRawat1** [fossasia/pslab-android#655]
**Actual Behaviour**
App showing Toast message of "Press again to close app" before closing app

**Expected Behaviour**
App show alert dialog showing "Do you want to close the app" when pressing back button on home page.

**Steps to reproduce it**
1.Go to home page
2.Press back button of device

**Would you like to work on the issue?**
Yes

**Comment by viveksb007** [comment]
@NamanRawat1 this is not much of an issue. Its just another way of doing what app actually does.
There are other important issue. Please address them.
Cheers
