### ISSUE TITLE
Create the Transients RLC Experiment

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#657]
**Actual Behaviour**
The `Transients RLC Experiment` has not been created so far

**Expected Behaviour**
Create the `Transients RLC Experiment`

**Steps to reproduce it**
`Main Menu` -> `Saved Experiments` -> `Electrical Experiments` -> `Transients RLC Experiment`

**LogCat for the issue**
None

**Screenshots of the issue**
None

**Would you like to work on the issue?**
Yes. In case a Codeheat developer wants to work on it, leave a comment here.

**Comment by NamanRawat1** [comment]
Can I work on it?

**Comment by asitava1998** [comment]
@NamanRawat1  Yes sure. Do you have the PSLab Device? If not , then I will update this thread with some resources for your help.

**Comment by NamanRawat1** [comment]
No I don't have PSLab devices @asitava1998

**Comment by asitava1998** [comment]
![screenshot from 2017-10-09 14-35-56](https://user-images.githubusercontent.com/19410364/31325345-ad235164-acd9-11e7-8f53-5d02a97bad28.png)
![screenshot from 2017-10-09 14-36-55](https://user-images.githubusercontent.com/19410364/31325349-b87e7764-acd9-11e7-9dda-0939903bf9e2.png)
As you can see there are elements like a plotting region, a spinner to adjust the x axis scale, buttons to set the offset and curve fitting.
This experiment is complicated and see if you can manage without the device. Personally I would recommend you to start with something easier like the `RC Integrals, Derivatives Experiment` in issue #659

**Comment by NamanRawat1** [comment]
ok i will work on issue #659 first. @asitava1998

**Comment by CloudyPadmal** [comment]
Issues related to experiments will be considered once the Android app is functional
