### ISSUE TITLE
Create LCR Steady State Experiment

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#658]
**Actual Behaviour**
The `LCR Steady State` Experiment has not been created so far

**Expected Behaviour**
The `LCR Steady State` Experiment needs to be created

**Steps to reproduce it**
`Main menu` -> `Saved Experiments` -> `Electrical Experiments` -> `LCR Steady State`

**LogCat for the issue**
None

**Screenshots of the issue**
None

**Would you like to work on the issue?**

**Comment by srv-twry** [comment]
@asitava1998 Can i work on it ?

**Comment by asitava1998** [comment]
@srv-twry Please go ahead. :+1:

**Comment by abhinavraj23** [comment]
@asitava1998 I want to work on it

**Comment by CloudyPadmal** [comment]
Issues related to experiments will be considered once the Android app is functional
