### ISSUE TITLE
Create RC Integrals, Derivatives Experiment

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#659]
**Actual Behaviour**
The `RC Integrals, Derivatives` Experiment has not been created so far.

**Expected Behaviour**
Create the `RC Integrals, Derivatives` Experiment

**Steps to reproduce it**
`Main Menu` -> `Saved Experiments` -> `Electrical Experiments` -> `RC Integrals, Derivatives`

**LogCat for the issue**
None

**Screenshots of the issue**
None

**Would you like to work on the issue?**

**Comment by NamanRawat1** [comment]
Check the code at -https://github.com/NamanRawat1/pslab-android/commit/e199a93887da4d24471dab9109e462865f0d0065

Showing unexpected output-
![screenshot_2017-10-24-00-07-38-430_org fossasia pslab](https://user-images.githubusercontent.com/21363531/31906882-e4a40864-b84f-11e7-8573-f02bf4ed599a.jpg)
@asitava1998

**Comment by NamanRawat1** [comment]
Add .md extension and tried with some other file still the same output @asitava1998

**Comment by asitava1998** [comment]
@NamanRawat1  I left at a comment in your code for the change to get the code running. Fix it soon.

**Comment by NamanRawat1** [comment]
https://github.com/NamanRawat1/pslab-android/commit/81dd0f74bb5f14e2e31b0e1cd19647456908e87a
Change the .md file name still the same output 
@asitava1998

**Comment by asitava1998** [comment]
@NamanRawat1  It is not about the filename. The experiment's name is `RC Integrals, Derivatives` , but you wrote it as `RC Integral` . That's why the file isn't rendered correctly.

**Comment by CloudyPadmal** [comment]
Fixed in #678
