### ISSUE TITLE
Create Voltage controlled Low Pass Filter Experiment

### ISSUE THREAD

**Issue by asitava1998** [fossasia/pslab-android#660]
**Actual Behaviour**
The `Voltage controlled Low Pass Filter` Experiment has not been created so far.

**Expected Behaviour**
Create the `Voltage controlled Low Pass Filter` experiment.

**Steps to reproduce it**
`Main Menu` -> `Saved Experiments` -> `Electrical Experiments` -> `Voltage Controlled Low Pass Filter`

**LogCat for the issue**
None

**Screenshots of the issue**
None

**Would you like to work on the issue?**

**Comment by divyabaid16** [comment]
I would like to work on this issue.

**Comment by CloudyPadmal** [comment]
@divyabaid16 Sure! Please send us a PR once you are done! 👍

**Comment by CloudyPadmal** [comment]
Issues related to experiments will be considered once the Android app is functional
