### ISSUE TITLE
Not saved the changes of main control in Control Application

### ISSUE THREAD

**Issue by NamanRawat1** [fossasia/pslab-android#661]
**Actual Behaviour**
When increment or decrement the PV values and set it and then go to read section then these values of PV are not saved.

**Expected Behaviour**
When going from main control.to other sections, the changes made in main control should be saved

**Steps to reproduce it**

![whatsapp video 2017-10-06 at 22 51 26](https://user-images.githubusercontent.com/21363531/31294176-8811a904-aaf7-11e7-882a-63809234c6ef.gif)

**Would you like to work on the issue?**
yes.

**Comment by sd1998** [comment]
@NamanRawat1  are you still working on the issue?

**Comment by NamanRawat1** [comment]
@sd1998  Yes

**Comment by abhinavraj23** [comment]
I want to work on this issue
