### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#663]
**Actual Behaviour**

Travis build failing.

**Expected Behaviour**

Travis build should not fail.

**LogCat for the issue**

https://travis-ci.org/fossasia/pslab-android/builds/286811099

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Hi @viveksb007 ! So should we upgrade SDK from 25 to 26?
