### ISSUE TITLE
Memory leaks in the app.

### ISSUE THREAD

**Issue by m-murad** [fossasia/pslab-android#664]
**Actual Behaviour**

There are some memory leaks in the app.

**Expected Behaviour**

These leaks need to be identified and fixed. Identifying the leaks can be done by adding LeakCanary to the app.

**Screenshots of the issue**
![whatsapp image 2017-10-14 at 1 19 47 am](https://user-images.githubusercontent.com/17262180/31563774-17ae5446-b07e-11e7-84c4-3ba8fd88cae7.jpeg)

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

I'm sending a PR to fix this.

**Comment by asitava1998** [comment]
Fixed in PR #665
