### ISSUE TITLE
Conversion of speed of sound experiment to Docmd fragment

### ISSUE THREAD

**Issue by NamanRawat1** [fossasia/pslab-android#675]
**Actual Behaviour**
The experiment is running using HTML fragment and showing some fluctuations.
Screenshot-
![screenshot_2017-10-26-17-15-48-302_org fossasia pslab](https://user-images.githubusercontent.com/21363531/32051343-df2ba77e-ba71-11e7-831b-c12ed12aebd4.jpg)

**Expected Behaviour**
Experiment show in standard format of .md used in all other experiments 

**Steps to reproduce it**
saved experiment->physics experiment->speed of sound

Let us know if this issue should be assigned to you 
Yes

**Comment by Avjeet** [comment]
I want to work in this issue can i have more details..

**Comment by abhinavraj23** [comment]
I also want to work in this issue

**Comment by asitava1998** [comment]
Fixed in PR #733
