### ISSUE TITLE
Remove play button from experiments screen

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#679]
**Actual Behaviour**

The play button in saved experiments is not useful and it is redundant.

**Expected Behaviour**

The button needs to be removed from the code as well as the layout

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![Screen with Play button](https://user-images.githubusercontent.com/14261304/33440709-a7d8fb98-d62b-11e7-9249-ac5977251297.png)

**Would you like to work on the issue?**

This could be a task for GCI '17

**Comment by srv-twry** [comment]
@CloudyPadmal can i take it as my first issue ? I'm not a participant of GCI'17 though.

**Comment by CloudyPadmal** [comment]
Sure sure!!! Go ahead :) Send us a pull request!
