### ISSUE TITLE
Create a new launcher icon

### ISSUE THREAD

**Issue by nikit19** [fossasia/pslab-android#683]
**Actual Behaviour**

The current launcher icon can be improved

**Expected Behaviour**

A new launcher icon should be made using any open source software.

**Would you like to work on the issue?**

This issue can be claimed by GCI participants.

**Comment by divyabaid16** [comment]
I would like to work on this issue @nikit19

**Comment by CloudyPadmal** [comment]
Sure @divyabaid16 ! 👍

**Comment by abhinavraj23** [comment]
I would also like to work on this issue @nikit19
