### ISSUE TITLE
Optimization of UI for better response in larger screens

### ISSUE THREAD

**Issue by Rimjhim28** [fossasia/pslab-android#684]
**Actual Behaviour**

Currently, the UI for all activities are just streched out for larger screens.

**Expected Behaviour**

A better option would be to optimize the UI to respond better for devices with larger screens and landscape layouts specifically according to material design guidelines such as, an open navigation drawer for tablet view, having more number of items populated on screen when on larger devices, etc.

**Steps to reproduce it**

Redefining of layouts for various screen widths as specified by material design guidelines.

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

![screenshot_1514053265](https://user-images.githubusercontent.com/26908195/34321728-43227710-e83c-11e7-8a49-93660c9d76d5.png)

![screenshot_1514053271](https://user-images.githubusercontent.com/26908195/34321729-452187fe-e83c-11e7-8540-1db86b75ef8b.png)

![screenshot_1514053294](https://user-images.githubusercontent.com/26908195/34321731-4792e190-e83c-11e7-8203-40ac5f831670.png)

![screenshot_1514053317](https://user-images.githubusercontent.com/26908195/34321732-4acf4f60-e83c-11e7-9a95-d5dc0347e49e.png)

![screenshot_1514053323](https://user-images.githubusercontent.com/26908195/34321734-4dafed02-e83c-11e7-9fe5-261de35189cb.png)

![screenshot_1514053337](https://user-images.githubusercontent.com/26908195/34321736-56e14844-e83c-11e7-862b-6bb803422465.png)

The views can be redefined to have a more centrally aligned text view with larger font sizes.
More options could be included instead of having extra large streched out views.

**Would you like to work on the issue?**

YES, I would like to work on the issue

**Comment by Rimjhim28** [comment]
@CloudyPadmal @nikit19 Is this issue valid enough to be worked on?

**Comment by CloudyPadmal** [comment]
@Rimjhim28 sure! Go ahead and send a PR! 👍
