### ISSUE TITLE
Usage of string resources instead of Hardcoded string

### ISSUE THREAD

**Issue by Rimjhim28** [fossasia/pslab-android#686]
**Actual Behaviour**

Though some hardcoded strings were removed through PR #674 , there are many other hardcoded strings throughout project that could be replaced with the usage of string resources.

**Expected Behaviour**

Usage of string resources for android:text to include any string

**Steps to reproduce it**

Using string resources to replace the hadcoded string.

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Screenshot of Lint output to indicate the usage of hardcoded string throughout the project:

![lint_output](https://user-images.githubusercontent.com/26908195/34341920-e1e5020a-e9c7-11e7-828d-f41ae08a9837.png)

**Would you like to work on the issue?**

YES, I would like to work on the issue.

**Comment by Rimjhim28** [comment]
@CloudyPadmal Is this issue valid enough to be worked on?

**Comment by CloudyPadmal** [comment]
Sure! Go ahead! :+1:
