### ISSUE TITLE
Adding full screen views for images in saved experiments

### ISSUE THREAD

**Issue by Rimjhim28** [fossasia/pslab-android#687]
**Actual Behaviour**

The various images and screenshots provided in saved experiments are non clickable and may become quite difficult to view on devices with small screen widths

**Expected Behaviour**

A better option would be to make the images clickable such that the user could be directed to full screen view for the images.

**Steps to reproduce it**

Not applicable

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

![screenshot_1514655762](https://user-images.githubusercontent.com/26908195/34456206-edd53556-edb6-11e7-8423-8301e78161e2.png)

**Would you like to work on the issue?**

YES, I would like to work on the issue.

**Comment by Rimjhim28** [comment]
@CloudyPadmal @mariobehling Can this be done on the project?

**Comment by CloudyPadmal** [comment]
@Rimjhim28 Do you mean when clicking on an image will render it in a different view where we can zoom in and out the image to view it? Please note that the `.md` files are rendered using `br.tiagohm.markdownview` so just see if you can get clickable events!

**Comment by CloudyPadmal** [comment]
@Rimjhim28 Do you mean when clicking on an image will render it in a different view where we can zoom in and out the image to view it? Please note that the `.md` files are rendered using `br.tiagohm.markdownview` so just see if you can get clickable events!

**Comment by Rimjhim28** [comment]
@CloudyPadmal I mean to add a full screen view for images by adding image buttons ro simply buttons with alpha set 0 to make them invisible. Click would direct to a new activity with full view of the image, that is , an activity just with an image view. No, just a full screen view without any zoom in and out feature.
If you assign me here, I will work on this and update you soon.

**Comment by viveksb007** [comment]
@Rimjhim28 any updates on it?

**Comment by Rimjhim28** [comment]
@viveksb007 @CloudyPadmal sorry for the delay.
Can you please help here on how this should be done?
I think we can add a button with no visibility such that clicking on images would also respond and clicking on buttons and then the user can be directed to a different activity with full screen view of the screenshot.

**Comment by CloudyPadmal** [comment]
There's a fix by @ThisIsNSH made in #793 where he zooms the content on the page itself.

**Comment by CloudyPadmal** [comment]
Experiments have been transferred to pslab-experiments
