### ISSUE TITLE
Usage if dimens.xml instead to hardcode values

### ISSUE THREAD

**Issue by Rimjhim28** [fossasia/pslab-android#688]
**Actual Behaviour**

There is usage of hardcoded values throughtout the xml files of the project for layout widths,heights and margins, text sizes and elevation.
It would be better if those values could be used through dimens.xml to provide a better option for reusability and rectification.

**Expected Behaviour**

Usage of dimensions through dimens.xml.

**Steps to reproduce it**

Not applicable

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

YES, I would like to be assigned for the issue.

**Comment by Rimjhim28** [comment]
@CloudyPadmal Is this issue valid enough to worked on?

**Comment by CloudyPadmal** [comment]
Yes please work on! :+1:
