### ISSUE TITLE
Replacing nested layouts with constraint layouts

### ISSUE THREAD

**Issue by Rimjhim28** [fossasia/pslab-android#691]
**Actual Behaviour**

Currently, the layouts used in the app have nested Relative and Linear layouts.
The layouts can be redefined to use Constraint Layouts to better app performance.

**Expected Behaviour**

Usage of Constraint Layouts in xml files.

**Steps to reproduce it**

Not applicable.

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

YES, I would like to work on this issue

**Comment by Rimjhim28** [comment]
@CloudyPadmal Can this be done for the layouts?

**Comment by CloudyPadmal** [comment]
@Rimjhim28 Yes please work on! 👍
