### ISSUE TITLE
Inclusion of warning dialogs of Applications

### ISSUE THREAD

**Issue by Rimjhim28** [fossasia/pslab-android#692]
**Actual Behaviour**

Currently  the segments defined under applications do not have warning dialogs, expect Oscilloscope.
When back button is pressed from oscilloscope, the user is first presented with a warning dialog whether he wants to close oscilloscope or not.
A similar warning dialog could be implemented for:
1.Control
2.Logical Analyzer
3.Data Sensor Logger
4.Sensor QuickView
5. Wave Generator, to implement uniformity in the app.

**Expected Behaviour**

Warning dialog appearing in all the Applications

**Steps to reproduce it**

Navigation Menu -> Applications -> Oscilloscope -> Back Button (A warning dialog appears)
Navigation Menu -> Applications -> Control -> Back button (The activity is exited directly without any warning)

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

The current warning dialog for Oscilloscope:
![screenshot_2018-01-05-12-48-08-980_org fossasia pslab 1](https://user-images.githubusercontent.com/26908195/34599245-20a18dae-f217-11e7-8598-357b57a5b84a.png)

I intend to include similar warning dialog for all other applications.

**Would you like to work on the issue?**

YES, I would like to work on this issue.

**Comment by Rimjhim28** [comment]
@CloudyPadmal Can this be done?

**Comment by CloudyPadmal** [comment]
@Rimjhim28 Yes please go on! 👍
