### ISSUE TITLE
Figures missing in many saved experiments 

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#712]
**Actual Behaviour**

In many saved experiments it has been mentioned "as shown in the figure" but the figure is missing

**Expected Behaviour**

The figures should appear

**Screenshots of the issue**

![screenshot_20180210-010555](https://user-images.githubusercontent.com/32960257/36061631-9d7f1b3e-0e82-11e8-9e51-7e3c6b9e1147.png)

**Would you like to work on the issue?**

Yes

**Comment by sharmamohit123** [comment]
I would like to work on this issue.

**Comment by sharmamohit123** [comment]
@abhinavraj23 Is it okay if I use png format image instead of svg format.

**Comment by abhinavraj23** [comment]
@sharmamohit123 I am already working in this issue, but we can divide the task you can do for the electronics experiment  and I will be doing it for the electrical experiments. Hope it is okay with you!!!

**Comment by abhinavraj23** [comment]
@sharmamohit123 prefer svg format.

**Comment by CloudyPadmal** [comment]
Yes please use svg format for images.

**Comment by Vipul999ujawane** [comment]
I'm working on the electronics experiments.
