### ISSUE TITLE
Application UI improvement

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#717]
**Actual Behaviour**

The icons are too big because of which all the icons can't be shown properly inside the screen

**Expected Behaviour**

the size of the icons should be small 

**Steps to reproduce it**

adapters->application adapter

**LogCat for the issue**

no logcat

**Screenshots of the issue**

![device-2018-02-17-175621](https://user-images.githubusercontent.com/20573611/36340904-0c1b3e40-140c-11e8-9a1d-4ffa03ee6fe3.png)

**Would you like to work on the issue?**
Yes
I would like to work on this issue.

**Comment by harsh-2711** [comment]
Is this still open? Because the view used is Scroll View and so no need of modifying the card views

**Comment by Avjeet** [comment]
actually I m trying to create a grid view as recycler view is not required.I will make a PR for that in a day or two.

**Comment by Avjeet** [comment]
Actually it looks very better if all the items view in in one page . I will make a PR for it in a day or two.

**Comment by cweitat** [comment]
Please close this issue if there's nothing more to edit

**Comment by CloudyPadmal** [comment]
Yes @cweitat ! Now this one is fixed.
