### ISSUE TITLE
The figure at transistor CB experiment is very small as compared to other experiment.

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#722]
**Actual Behaviour**

The figure at transistor CB experiment of electronics experiment section is very small as compared to other experiments and is not clear.

**Expected Behaviour**

The figure should be bigger and clear.

**Would you like to work on the issue?**

Yes

**Comment by Vipul999ujawane** [comment]
I'm working on all the Electronics experiments

**Comment by CloudyPadmal** [comment]
Fixed in #739
