### ISSUE TITLE
bug in oscilloscope activity

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#724]
**Actual Behaviour**

On selecting the "enable xy plot" there is a null pointer exception 

**Expected Behaviour**

it should show the xy axis in the graph and no null pointer exception 

**Steps to reproduce it**
activity->oscilloscope activity

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

![capture](https://user-images.githubusercontent.com/20573611/36434153-5c9766da-1684-11e8-9e09-d43931477bda.PNG)

**Would you like to work on the issue?**
yes

**Comment by Avjeet** [comment]
i have resolved the issue mentors plz review my previous PR #713 so that I can submit new one.

**Comment by viveksb007** [comment]
Fixed in #728
