### ISSUE TITLE
bug in sensor data logger activity

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#725]
**Actual Behaviour**

Null pointer exception on clicking the floating button in data sensor logger activity

**Expected Behaviour**

No null pointer exception should be there

**Steps to reproduce it**

activity->data sensor logger activity

**LogCat for the issue**

![capture](https://user-images.githubusercontent.com/20573611/36435310-554a7de2-1687-11e8-9975-3b26f7ba8be8.PNG)

**Would you like to work on the issue?**

Yes

**Comment by abhinavraj23** [comment]
I want to work on this issue @Avjeet

**Comment by Avjeet** [comment]
@abhinavraj i hv already resolved it.. Waiting for my previous to get reviewed

**Comment by viveksb007** [comment]
Fixed in #728
