### ISSUE TITLE
Inverting Op-Amp and Non-Inverting Op-Amp Not showing up

### ISSUE THREAD

**Issue by Vipul999ujawane** [fossasia/pslab-android#727]
**Actual Behaviour**
A blank screen comes up.

**Expected Behaviour**

Experiment should come up

![screenshot_20180222-195256](https://user-images.githubusercontent.com/20845040/36543602-334aead6-180a-11e8-891e-a865024bb0e0.jpg)

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

Yes

**Comment by harsh-2711** [comment]
Can I work on this issue?

**Comment by Vipul999ujawane** [comment]
@harsh-2711 Sorry bro, but I've pretty much completed the work on this issue.

**Comment by CloudyPadmal** [comment]
Fixed in #739
