### ISSUE TITLE
Update PR Template

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#730]
**Actual Behaviour**

Current PR template doesn't have an entry to submit an APK for testing.

**Expected Behaviour**

Functionalities can be checked easily with the APK. PR template needs to ask for that when a PR is being made.

**Steps to reproduce it**

Refer to PR_TEMPLATE

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes.

**Comment by iamareebjamal** [comment]
Instead of asking APKs, shouldn't the APKs built by Travis be used?
