### ISSUE TITLE
Bug in the Control Advanced fragment

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#736]
**Actual Behaviour**

 The value of all the  edittext in arbitrary waveform generator  is being set to zero on pressing the set button.

**Expected Behaviour**

It should not set the value to zero.

**Steps to reproduce it**

activity->control activity->control advanced fragment

**Screenshots of the issue**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20573611/36640424-5df6b814-1a44-11e8-8fca-16a2daaa0511.gif)

**Would you like to work on the issue?**
Yes

**Comment by Avjeet** [comment]
@CloudyPadmal @viveksb007 @akarshan96 It is due to the phase editext is throwing number format exception as it is expecting a value in integer and the editext has float,mentors plz guide what value is required by the phase (float or integer ) so that I can make the changes accordingly.

**Comment by CloudyPadmal** [comment]
Resolved in #748
