### ISSUE TITLE
Animation not working properly

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#738]
**Actual Behaviour**

When going from one page to another, the texts overlap on each other due to bad timings of animation.

**Expected Behaviour**

First, the text of current page should fade and then the text of new page should come up.

**Steps to reproduce it**

1. Go to applications from side menu

2. Switch to Saved Experiments tab from the side menu

**LogCat for the issue**

No LogCat

**Screenshots of the issue**

![screenshot_20180227-131047 1](https://user-images.githubusercontent.com/32356267/36716538-9df41a9c-1bc0-11e8-8d8d-f93fd923223a.jpg)

**Would you like to work on the issue?**

Yes

**Comment by ThisIsNSH** [comment]
Please close this issue... As it is resolved.

**Comment by akarshan96** [comment]
Fixed in #749
