### ISSUE TITLE
Enhance "Report Issue"

### ISSUE THREAD

**Issue by ThisIsNSH** [fossasia/pslab-android#752]
**Actual Behaviour**
When Report Issue is clicked then the new issue webpage appears on a web browser not on the app. Due to this the user sees the previous activity which he was on for a second and then the webpage starts loading.

**Expected Behaviour**
Users should be allowed to report issues within the app. 

**Steps to reproduce it**
Remove customTabService in activity->MainActivity.java and add new activity for reporting issues.

**LogCat for the issue**
None

**Video of the issue**
![20180308_160053_edited](https://user-images.githubusercontent.com/32385519/37147823-3bcb64f8-22ee-11e8-851a-7afc6072dffc.gif)

**Would you like to work on the issue?**
Yes

**Comment by ThisIsNSH** [comment]
@CloudyPadmal please assign me this.

**Comment by CloudyPadmal** [comment]
Current issue reporting implementation is good enough to handle the task
