### ISSUE TITLE
Details of the Save Circuit getting vanished after pressing utilities Inside Experiment Document

### ISSUE THREAD

**Issue by Dhiraj240** [fossasia/pslab-android#755]
**Actual Behaviour**

![ohmsnormal perfect](https://user-images.githubusercontent.com/29758643/37248396-5990040c-24f7-11e8-8e9b-6121a7130fb3.png)
![experiments](https://user-images.githubusercontent.com/29758643/37248398-652d074c-24f7-11e8-8689-6612a9786297.png)
![homeagain](https://user-images.githubusercontent.com/29758643/37248399-6bd5c2a0-24f7-11e8-88b5-910e641580c2.png)

**Expected Behaviour**

After pressing  experiments when we return back to home it shows **PSlab help file**.
Instead it should revert back the same details after pressing the home.
Also some screenshots are not present which can be added by me.

**Steps to reproduce it**

Home task is getting cleared after pressing utilities and can be restored  by manipulating the Intent as i feel that correct launch behavior has to be created.This happened when someone has put a sorting technique inside the body of Experiment Document.. 

**Would you like to work on the issue?**
Yes

**Comment by Dhiraj240** [comment]
@CloudyPadmal  Can i work on this project ?

**Comment by akarshan96** [comment]
@Dhiraj240 sure you can

**Comment by Dhiraj240** [comment]
Thank you,will update as soon as possible.

**Comment by CloudyPadmal** [comment]
Experiments have been transferred to pslab-experiments
