### ISSUE TITLE
Enhance OpAmp - Colpitts Oscillator Experiment

### ISSUE THREAD

**Issue by ThisIsNSH** [fossasia/pslab-android#762]
**Actual Behaviour**

The current markdown has only two lines and no schematic.

**Expected Behaviour**

The markdown should have information related to experiment and a schematic.

**Steps to reproduce it**

Create new svg schematic and new information.

**LogCat for the issue**

None

**Would you like to work on the issue?**

Yes.

**Comment by ThisIsNSH** [comment]
I have worked on this issue and submitted a PR #761 . Please Review.

**Comment by CloudyPadmal** [comment]
Fixed in #761
