### ISSUE TITLE
Add Different language support

### ISSUE THREAD

**Issue by ThisIsNSH** [fossasia/pslab-android#776]
**Actual Behaviour**
Currently the app only has English language. Chinese is one of the most spoken language in the world. Not only Chinese but other languages should be added to increase the usability of the app. 

**Expected Behavior**
Users should be able to view app in other languages too.

**Steps to reproduce it**
Start with creating string.xml in chinese and then move on to other languages

**Would you like to work on the issue?**
yes

**Comment by CloudyPadmal** [comment]
We can consider about language support in a latter phase
