### ISSUE TITLE
Make the schematics and screenshots zoomable

### ISSUE THREAD

**Issue by ThisIsNSH** [fossasia/pslab-android#778]
**Actual Behaviour**

Currently the app does not allow user to click on the image (schematics & screenshot) and zoom it.

**Expected Behaviour**

User should be able to zoom the image he wishes to see.

**Steps to reproduce it**

Every markdown is to be changed where the image code is written. There will be a image source but on clicking it, user will be able to see the image in full size ( mainly on an external source i.e. web browser)

**LogCat for the issue**

None

**Screenshots of the issue**

None.

**Would you like to work on the issue?**

Yes

**Comment by ThisIsNSH** [comment]
@CloudyPadmal @akarshan96 @viveksb007 please check if work is to done on this issue?

**Comment by mariobehling** [comment]
Features should work offline. Image should be zoomable inside the app.

**Comment by ThisIsNSH** [comment]
Definitely.. I will work on this and get back.
