### ISSUE TITLE
implement readLine function in CommunicationHandler.java

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#79]
Implement readLine function in CommunicationHandler.java, so that we can read a line i.e String terminated by '\n' and we don't know length of string beforehand.

Possible approach- read single byte in a loop and check for '\n', when found return the byte array formed before encountering '\n'. Tried but error in reading single byte from bulkTransfer. May be due to high BaudRate of 1Mbps.

For now it would only be used to read version String of device.

**Comment by CloudyPadmal** [comment]
PSLab version string will be of fixed length. There is no need to have an implementation to read different character sizes.
