### ISSUE TITLE
Change access to private instead of public

### ISSUE THREAD

**Issue by Rimjhim28** [fossasia/pslab-android#804]
**Actual Behaviour**

There is a warning "Access can be changed to private"

**Expected Behaviour**

Most of the classes and methods are declared public which gives a warning in Android Studio but instead they can be made package-private. This will help counter two problems -
a) Easier to debug that class or method
b) Would help to reduce the unnecessary Coupling.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Would you like to work on the issue?**

Yes.

**Comment by Rimjhim28** [comment]
@CloudyPadmal I am busy with my GSoC project in Systers org.
If anyone intends to work on this issue, he can go ahead.

**Comment by CloudyPadmal** [comment]
Sure @Rimjhim28 ! :+1:
