### ISSUE TITLE
Enhance Schematic Zoom functionality

### ISSUE THREAD

**Issue by ThisIsNSH** [fossasia/pslab-android#808]
**Actual Behaviour**
Currently #793 only implements zoom functionality in Markdowns with 
* Top Markdown
* One Image
* Bottom markdown

**Expected Behaviour**
There are different layouts in markdown. So there should be more than one ExperimentDocMdFragment class for these layouts.  

**Would you like to work on the issue?**
Yes

**Comment by CloudyPadmal** [comment]
Issues related to experiments will be addressed once the app is stable
