### ISSUE TITLE
Connverting the entire code base to kotlin

### ISSUE THREAD

**Issue by uemarica** [fossasia/pslab-android#814]
**Actual Behaviour**

The app crashes sometimes.

**Expected Behaviour**

Using kotlin there are no null pointer exceptions which might be main reason why the app crashes.

**Steps to reproduce it**

Convert the entire code-base from java to kotlin.

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
This is not needed at the moment to transform a whole new app to Kotlin. So I'm closing this issue.
