### ISSUE TITLE
The codebase is not commented properly.

### ISSUE THREAD

**Issue by uemarica** [fossasia/pslab-android#817]
**Actual Behaviour**

The present codebase is not documented properly which might be time taking for a new developer. 

**Expected Behaviour**

Documenting(adding comments) to the codebase.

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@uemarica how is the progress of this issue? Are you working on it?

**Comment by mariobehling** [comment]
This description is too generic. Documentation needs to be part of every issue. Therefore closing it.
