### ISSUE TITLE
No documentation for stepper moter experiment 

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#820]
**Actual Behaviour**

The documentation for the stepper motor experiment is absent although the experiment setup is implemented.

**Expected Behaviour**

The documention should be there.

**Steps to reproduce it**

Make the experiment documents.

**LogCat for the issue**

Not applicable.

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Follow up in the experiments repo, please.
