### ISSUE TITLE
Adding links for device description and help&support on home screen.

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#827]
**Actual Behaviour**

Currently home screen is showing only device attached status.

**Expected Behaviour**

Home Screen should also contain links to device description and button for help & support on the home screen .

**Steps to reproduce it**
Fragments->HomeFragment

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/20573611/39660204-52b5e760-5057-11e8-94d1-4a7db4ddc279.png)

**Would you like to work on the issue?**

Yes

**Comment by Avjeet** [comment]
In this link of "What is PS Lab ?" we can provide them with all the information about the device like its features and where can u buy one etc.
Also this will take up extra space on the home screen and make it look better.

**Comment by CloudyPadmal** [comment]
Hello @Avjeet ! Instead of this screen, we'll take the current `Applications` part to the home page. So it's one less click~ :)

**Comment by Avjeet** [comment]
yeah but then where will we show the usb attach status ?? @CloudyPadmal

**Comment by CloudyPadmal** [comment]
@Avjeet I've added a mockup in [Invision](https://projects.invisionapp.com/boards/9A3LPR0RZ6G/) and invited you to the group. There we can finalize UIs before implementing them!

**Comment by Avjeet** [comment]
@CloudyPadmal can we implement it like this- show this home fragment only when the device is not connected as an empty activity .
When the device is connected this empty activity will simply  be replaced by the recycler view .

**Comment by CloudyPadmal** [comment]
@Avjeet Ah you mean "Device not connected" view when it is not connected and only when connected user can access the features?

**Comment by Avjeet** [comment]
Yeah, the PSLAB tools contained in recycler view will only be available when device is connected  . Rest of the app can still be accessed without the device.

**Comment by CloudyPadmal** [comment]
Sounds good! :+1:

**Comment by cweitat** [comment]
#932
