### ISSUE TITLE
Designing of Applications not good

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#832]
**Actual Behaviour**

The designing of applications section is not very user friendly.

**Expected Behaviour**

It should have great UI.

**Steps to reproduce it**

Go to Applications section from navigation menu.

**LogCat for the issue**

Not Applicable

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
This issue is too generic and does not really have a scope. It also does not provide any info on what is not good or how to improve it. Avoid such generic issues "something is not good". Provide specifics and info on how to improve something specific.
