### ISSUE TITLE
Improve the layout of the saved experiment activity

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#849]
**Actual Behaviour**

The layout of the saved experiment activity is too basic

**Expected Behaviour**

The layout should have icons which makes it look more interactive

**Screenshot of the issue**
![image](https://user-images.githubusercontent.com/20573611/39881004-1ca2c2e8-549d-11e8-9093-c4939ec8feca.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
no need.
