### ISSUE TITLE
Control Main activity should have reset button

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#850]
**Actual Behaviour**

There is no button to reset the the value and the seek bar to default.

**Expected Behaviour**

There should be reset button so the user don't have to seek the bar manually .
The  extra box at the right side can be replaced by a reset button.

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.
![image](https://user-images.githubusercontent.com/20573611/39881173-c05d32a6-549d-11e8-8c8f-cd71e06f4f09.png)

**Would you like to work on the issue?**

Yes

**Comment by Avjeet** [comment]
I have designed a layout, mentors plz comment @mariobehling @CloudyPadmal @akarshan96 

![image](https://user-images.githubusercontent.com/20573611/39881211-e6295096-549d-11e8-8a4b-5e218a602efd.png)

**Comment by CloudyPadmal** [comment]
This will be implemented in the updated power source UI
