### ISSUE TITLE
Problem with Oscilloscope Activity

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#856]
**Actual Behaviour**

The orientation of the screen remains in landscape mode(although oscilloscope activity is closed) after opening oscilloscope activity

**Expected Behaviour**

The screen orientation should change back to portrait after closing of oscilloscope activity

**Steps to reproduce it**

Go to oscilloscope activity under Applications tab and then press back to exit

**Screenshots of the issue**

![20180511_142536](https://user-images.githubusercontent.com/32356267/39919904-bafdf206-5532-11e8-980d-39e19ad3d32f.gif)

Here the mobile is always in portrait mode whereas the layouts turns to landscape mode after opening oscilloscope activity. After again pressing back after changing to any other tab, the orientation returns back to normal

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
I cannot recreate this issue. In my device the screen comes back to portrait mode. Do  others get this issue?

**Comment by Avjeet** [comment]
Even in my device it comes back to portrait normally!!
@harsh-2711 you should try to run in some other device.

**Comment by harsh-2711** [comment]
My device is One Plus 5T. I also tried on vivo v7. Same problem exists. Don't know why it's not happening with you?

**Comment by abhinavraj23** [comment]
Well also in my device it comes back normally to portrait !!

**Comment by harsh-2711** [comment]
Can't we add this single line of code so that devices that faces problem will get solved and there will be no change on the devices that doesn't face this issue ? (Because both of my devices faced same issue)

**Comment by CloudyPadmal** [comment]
@harsh-2711 yes let's do that! :+1:

**Comment by Vikum94** [comment]
Yes. When you turn on Screen rotation, this happens.

**Comment by harsh-2711** [comment]
So please merge this PR
