### ISSUE TITLE
Experiment Doc. of Voltage controlled Low Pass filter Experiment

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#858]
**Actual Behaviour**
The font is not proper and even the image is not linked properly.

**Expected Behaviour**
The font must be proper along with the image file.

**Steps to reproduce it**
1. Open Saved Experiments
2. Open Electrical Experiment
3. Open voltage controlled Low Pass Filter 

**LogCat for the issue**

Not required

**Screenshots of the issue**
![screenshot_2018-05-11-17-10-40-858_org fossasia pslab](https://user-images.githubusercontent.com/34381723/39922943-47a938da-553f-11e8-988b-52af0bfa08c4.png)

**Would you like to work on the issue?**

Yes.

**Comment by harsh-2711** [comment]
It's perfectly fine for me.

![screenshot_20180511-173055](https://user-images.githubusercontent.com/32356267/39923451-3d45430a-5541-11e8-9d0d-56b41d727407.jpg)

What about others ?

**Comment by abhinavraj23** [comment]
@yatri1609 this issue is already resolved by me in the pr #844 . Please pull the latest changes in your system :+1:
