### ISSUE TITLE
Enable scrollability in Exp. Setup of Servo Motors in Landscape mode

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#859]
**Actual Behaviour**

The buttons are not seen in landscape mode.

**Expected Behaviour**

The buttons must be accessible in both the modes.

**Steps to reproduce it**

1. Open Saved Experiment
2. Goto Add-On Module 
3. Open various utilities
4. Open Servo Motor

**LogCat for the issue**
Not required 

**Screenshots of the issue**
![screenshot_2018-05-11-18-17-47-198_org fossasia pslab](https://user-images.githubusercontent.com/34381723/39925068-e52d1696-5547-11e8-8946-58af05b5127c.png)
![screenshot_2018-05-11-18-17-53-127_org fossasia pslab](https://user-images.githubusercontent.com/34381723/39925069-e58d05c4-5547-11e8-935a-8d2e9d46eb11.png)

**Would you like to work on the issue?**
Yes

**Comment by harsh-2711** [comment]
The view is indeed scrollable and is working for me
![20180511_202111](https://user-images.githubusercontent.com/32356267/39930666-f0942c66-5558-11e8-8345-d4839faeb662.gif)

**Comment by CloudyPadmal** [comment]
@harsh-2711 your screen seems bigger, so the buttons are visible. Mine it's stuck at Servo 4 without showing buttons. @yatri1609 please restrict the layout to stay in portrait mode. I think that will make the fix any easier?

**Comment by CloudyPadmal** [comment]
@yatri1609 for each PR, have a different branch. Now it's combined with the earlier PR. Please cherry-pick that commit to a new branch and make a new PR!

**Comment by CloudyPadmal** [comment]
Issues related to experiments will be considered once the Android app is functional
