### ISSUE TITLE
Minor changes in Schematics needed

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#864]
**Actual Behaviour**

There are some errors in following schematics -
1. Measure voltage experiment - 4th and 5th schematics have overlapping text
2. Monostable multivibrator - Text of resistance RL2 is not according to standards
3. Inverting Op-Amp - Ri and Rf are duplicated
4. Non-Inverting Op-Amp - Again Ri and Rf are duplicated
5. Wein Bridge Oscillator - The text written in 19.8K resistor (i.e. 19.8K) is somewhat difficult to read
6. Astable multivibrator - The text around the transistors are very near to each other and so gives bad user experience
7. Diode IV Characteristics - The head is far away from actual schematic
8. Full Wave Rectifier - Again head is far away from actual schematic
9. N-FET Output/Transfer Characteristics - The color used for resistor is not aprropriate
10. Precision Rectifier - The pin of V- uses extra wire although it can be connect directly and also the head is very far away from schematic
11. Ramp Generator - It should be 0.1 and not .1 according to standards
12. Zener IV Characteristics - The text Zener(3.3V) is almost overlapping with schematic

**Expected Behaviour**

The errors shouldn't be there

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
When describing the behavior of the issue, be a little bit specific. "Some errors" means what?

**Comment by harsh-2711** [comment]
@CloudyPadmal  I have described the issues. Please have a look

**Comment by mariobehling** [comment]
Please fix if needed in the experiments repo.
