### ISSUE TITLE
The report issue activity should have an auto github issue maker.

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#866]
**Actual Behaviour**

Currently the report issue section of the app takes us to the github page where we have to manually make an issue.

**Expected Behaviour** 

There should be a feature where the user reports the issue in the app itself and the issue is directly created in github.

**Steps to reproduce it**

Use the github issue API(REST API v3) to implement an auto issue maker.

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable.

**Would you like to work on the issue?**

Yes.

**Comment by mariobehling** [comment]
Low priority for now. We need to focus on the app features itself. It is good enough for now.
