### ISSUE TITLE
Minor changes in experiment docs needed

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#868]
**Actual Behaviour**

There are some errors in the documentation of some experiments. They are -
1. N-FET Transfer characteristics - The heading is not well defined
2. BJT Output Characteristics - The heading should define the name of the experiment and not the component which it is using
3. BJT Input Characteristics - Heading schematics should be given before the schematics diagram
4. Semi-Conductor Diode - The heading should be semi-conductor diode instead of diode
5. Inverting Op-Amp - Heading should be Inverting Op-Amp rather than Inverting and schematics label should be there
6. Non Inverting Op-Amp - Same changes needed as that of Inverting Op-Amp
7. Phase Shift Oscillator - The text style of heading of this experiment is not proper
8. Monostable Multivibrator - The text transistor: shoulf be reoved from heading as the head should match with other experiments (eg. Astable Multivibrator) and schematics label missing
9. RC Phase shift - Head should be R-C phase shift rather than CR phase shift. Missing schematics label
10. RC Integrals, Derivatives - Text style of C-R Derivatives should match with R-C Integration. Also it should be R-C Derivatives instead of C-R Derivatives
11. Lemon Cell Experiment - Schematics label missing
12. Servo Motors - Some headings are missing like working and actual representation
13. Diode Clamping - Schematic label missing
14. Half Wave Rectifier - Schematic label missing
15. Ramp Generator - Schematic and Screenshot both labels are missing
16. Wien Bridge Oscillator - Schematic label missing
17. Capacitive Reactance and Inductive Reactance - Schematics label  missing
18. LR Phase Shift - Schematic label missing
19. Precision Rectifier - Schematics label missing
20. Speed of Sound - Schematics label missing
21. Ultrasonic Range Finder - Schematics label missing
22. Voltage Controlled Low Pass Filter - Schematics label missing

**Expected Behaviour**

This errors shouldn't be there

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please fix this in the experiments repository.
