### ISSUE TITLE
Oscilloscope communication errors for pin SI1, SI2

### ISSUE THREAD

**Issue by Vikum94** [fossasia/pslab-android#873]
**Actual Behaviour**

The SI1 and SI2 is always a square wave

**Expected Behaviour**

Should be a sine wave which responds to the set frequency value at control activity.

**Steps to reproduce it**

Connect SI1 pin to CH1 and SI2 to CH2. Check the Oscilloscope by enabling CH1 and CH2 at Channel parameters. Change the value of Wave 1 and Wave 2 from Control Main fragment and see. Nothing will change

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![screenshot_2018-05-12-20-59-03](https://user-images.githubusercontent.com/17523141/39963161-a43e13c0-5681-11e8-817d-752bba06959e.png)

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Hi @Vikum94 ! For me I'm getting a Sine wave. By any chance have you selected square wave output instead of sine?

**Comment by Vikum94** [comment]
Do you mean from Control Advanced fragment?

**Comment by CloudyPadmal** [comment]
Yes!

**Comment by Vikum94** [comment]
I am using the sine wave.
