### ISSUE TITLE
Oscilloscope cannot handle simultaneous inputs from SQ1 and MIC 

### ISSUE THREAD

**Issue by Vikum94** [fossasia/pslab-android#874]
**Actual Behaviour**

When try to plot both SQ1 wave from CH1 and Built in microphone, the oscilloscope plot blinks. Cannot handle both the input at once

**Expected Behaviour**

Both waves should be in plotted in oscilloscope having a smooth refresh rate.  

**Steps to reproduce it**

Connect SQ1 with CH1 and enable it. Use built in microphone in from oscilloscope. Select both to plot and enable disable either one and see the changes.

**LogCat for the issue**

> None

**Screenshots of the issue**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17523141/39963226-9c3a63b6-5683-11e8-86f1-b129491af864.gif)

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
I see lot of leak warnings are there. Do you experience difficulty in running the app in debug mode as that memory monitoring app freezes the app regularly?

**Comment by Vikum94** [comment]
No it does not freeze regularly. May be once after app starts. Then it doesn't happen. Notifications are previous leak warnings. I didn't clear them.

**Comment by CloudyPadmal** [comment]
Ok great! :+1:

**Comment by cweitat** [comment]
What's the status of this?

**Comment by cweitat** [comment]
@harsh-2711 @Avjeet @abhinavraj23 @CloudyPadmal due to unavailability of Vikum, who wants to continue this?

**Comment by CloudyPadmal** [comment]
@abhinavraj23 can you take this up?

**Comment by abhinavraj23** [comment]
Okay @CloudyPadmal i will work on the issue :+1:
