### ISSUE TITLE
Rename illogical headers

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#876]
**Actual Behaviour**

`Saved experiments` doesn't make sense as they are not user saved experiments.

**Expected Behaviour**

Similar headings need to be changed

**Steps to reproduce it**

1. Look at the application headers

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

-

**Comment by harsh-2711** [comment]
@CloudyPadmal  Can I take up this issue?

**Comment by CloudyPadmal** [comment]
Yes you can carry on!
