### ISSUE TITLE
UI of instrument section needs improvement

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#877]
**Actual Behaviour**

UI of the instrument section part is not up to the mark

**Expected Behaviour**

The UI of the instrument section should have CardViews to represent each instrument.

**Steps to reproduce it**

Change the UI in the code.

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Provide details and explain what needs to be changed and how, please.

**Comment by Avjeet** [comment]
A layout similar to this has to be produced 

![](https://files.gitter.im/fossasia/pslab/iAkE/UIpic.png)

**Comment by yatri1609** [comment]
@Avjeet and @abhinavraj23  Can I also contribute to this with both of you if both of you are working together? We can divide the work accordingly!

**Comment by abhinavraj23** [comment]
@yatri1609 Already me,  @harsh-2711 and @Avjeet are working in it, and it is almost done.

**Comment by abhinavraj23** [comment]
@mariobehling @CloudyPadmal @akarshan96  Please review this layout, I will change the layout colour with PSLab colours :+1:
