### ISSUE TITLE
Create the wave generator module 

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#878]
**Actual Behaviour**

Currently on clicking the wave generator activity it is showing just a blank screen

**Expected Behaviour**

On clicking wave generator it should open a activity with functionality to generate sine wave , square wave,triangular wave ,saw tooth and should be able to change its duty cycle , phase , amplitude.

**Steps to reproduce it**
Fragment ->Wavegen Fragment

**Would you like to work on the issue?**

Yes

**Comment by Avjeet** [comment]
I have created a Layout for the wavegen activity

![image](https://user-images.githubusercontent.com/20573611/40061863-88c03d92-5877-11e8-8567-78550609f0ea.png)

**Comment by CloudyPadmal** [comment]
Here we need to add some stuff;
---
### Sine Wave
  - There are two pins and we can set two frequencies to those two with a phase difference which also we can set

### Square Wave
  - Similarly we have 4 pins with 4 different settings

### Saw Tooth Wave
  - This is actually a `Triangular Wave` with similar settings to `Sine Wave`

**Comment by Avjeet** [comment]
I have thought of creating a view pager with two tabs :- 
1.)**Wave Generator** - For producing sine/square waves using **w1,w2**
2.)**Configure PWM** - For producing PWM outputs using **sq1,sq2,sq3,sq4**

Here the mockups I have created:-
![wave1](https://user-images.githubusercontent.com/20573611/40137647-85ae8a72-5968-11e8-8464-5cf3462851e3.PNG)
![wave2](https://user-images.githubusercontent.com/20573611/40137648-85de09be-5968-11e8-8832-dd2cc27c69f6.PNG)

**Comment by mariobehling** [comment]
Please provide screenshots of existing devices that offer this functionality. How does the UI look like on these? Please follow the standard views of those devices.

**Comment by Avjeet** [comment]
@mariobehling This is the existing Ui of the device in android app providing same UI 
![screenshot_2018-05-17-09-46-36-549_org fossasia pslab](https://user-images.githubusercontent.com/20573611/40168091-47af6926-59e0-11e8-9d5e-518c63e38ec2.png)

**Comment by Avjeet** [comment]
As WaveForm Generator and Configure Pwm are two different things but both of them produce signals, so I thought to separate them in two tabs but put them inside single "Wave Generator Device Activity" as shown by the layouts above this

**Comment by mariobehling** [comment]
> Please provide screenshots of existing devices that offer this functionality. How does the UI look like on these? Please follow the standard views of those devices.

What UI do existing devices on the market use. Provide links and details. How is the UI of hardware and digital devices providing the same functionality? What are professionals using? Provide photos, screenshots etc. and follow industry players and existing designs in the implementation.

**Comment by Avjeet** [comment]
@mariobehling ok got it, I will update my UIs according to the Function Generators in the market and the Desktop Repo.

**Comment by Avjeet** [comment]
Here are the screenshots of the physical function generator provided by HP
![wavegenerator_device](https://user-images.githubusercontent.com/20573611/40271476-6eb9a4a0-5bbb-11e8-9dc8-c8e097792153.PNG)

and this is the screenshot of another app providing the wave generator 
![wave](https://user-images.githubusercontent.com/20573611/40271485-9065cd40-5bbb-11e8-88ae-60cbdc416983.PNG)
I am creating a layout similar this with a screen.

**Comment by Avjeet** [comment]
I have created a mockup of the screen: -
![waveland](https://user-images.githubusercontent.com/20573611/40277442-a7c3945a-5c3c-11e8-9a5a-2549f12511c4.PNG)

**Comment by Avjeet** [comment]
It is not required

**Comment by CloudyPadmal** [comment]
Hello @Avjeet ! We can enlarge the view by following modifications;

1. We don't provide modulation in wave generator, so `Modulation` part can be removed. There is a separate experiment for modulation. So we can just omit it from this one.
2. Only (Triangular), (Sine) and (Square) waves. No offset or amplitude control from app.
3. Apart from the dial, it would be better to have a two up and down buttons as in the HP version to adjust smaller frequency values.

Do all those make sense?

The colors need to be same as the application theme.

**Comment by Vikum94** [comment]
Overall the UI looks good but,
1. Red color text does not suit for the black background I think. In the reference figure, they have a good color scheme. You can adjust them to suit our theme. 
2. The subgroup saying Channel is not actually the channel. Channel is where you read the input. You have to change it into maybe Wave. It is the pin where the wave is generated.

**Comment by Avjeet** [comment]
@mariobehling @CloudyPadmal @Vikum94 @akarshan96 I have edited the layout of the wave generator 
![image](https://user-images.githubusercontent.com/20573611/40575398-0e61f4c6-6102-11e8-9978-46abdf7c5cd4.png)

**Comment by Vikum94** [comment]
Functionality wise all ok according to previous discussions. The selected buttons are not highlighted well. Would it be possible to use green color to show the selected buttons @CloudyPadmal Can the theme have that color? 
Still we cannot adjust the amplitude using the application. So is it necessary here @CloudyPadmal May be we will need it in future?

**Comment by Avjeet** [comment]
@Vikum94  there is no need to show selected button as monitor can handle can handle that.

**Comment by CloudyPadmal** [comment]
Wave Generator module is now Implemented
