### ISSUE TITLE
Redesign Oscilloscope UI

### ISSUE THREAD

**Issue by Vikum94** [fossasia/pslab-android#880]
**Actual Behaviour**

Oscilloscope layout contains a left pane with buttons.

**Expected Behaviour**

The buttons should separate from each other and have more meaning and interactivity. The selected setting should be highlighted.  

**Steps to reproduce it**

Choose Oscilloscope in Instruments

**LogCat for the issue**

> None

**Screenshots of the issue**

![screenshot_2018-05-17-07-11-21](https://user-images.githubusercontent.com/17523141/40152421-cdf577e8-59a2-11e8-90f3-bd3af0463e1e.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please describe more in detail, what the buttons should do exactly. "More meaning and interactivity" does not really tell us what you plan to show here.

**Comment by Vikum94** [comment]
The buttons to select and change different parameters in the oscilloscope are shown in the right pane.

- There is no clear boundary between buttons. 
- When clicked, buttons do not show which one is currently selected.

**Comment by Vikum94** [comment]
Proposed UI - When selected, the button highlights it's background.

![oscilloscope](https://user-images.githubusercontent.com/17523141/40212576-3be34d0e-5a6e-11e8-9dd0-82ab5693fba5.png)
