### ISSUE TITLE
Get rid of annoying "Are you sure you want to close" messages when pressing back button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#881]
When the user wants to exit from an instrument there is a message "are you sure you want to close...". Please take out this message from all screens and activities.

**Comment by abhinavraj23** [comment]
@mariobehling I think this issue is already resolved in the PR #787

**Comment by harsh-2711** [comment]
@mariobehling  Can you please tell me where are you facing this issue?

**Comment by CloudyPadmal** [comment]
This is fixed and the latest version is not available in Google Play! :+1:
