### ISSUE TITLE
Format Logic Analyzer Designing

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#889]
**Actual Behaviour**

The designing and also the features of logic analyzer are limited

**Expected Behaviour**

It should contain all latest features and should have good designing

**Steps to reproduce it**

Go to Logic Analyzer in Instruments section

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Thank you. Please add references and links. Please always provide sources. Also provide info on devices that provide the features, e.g. photos of devices and their UI.

**Comment by harsh-2711** [comment]
Options seen on the sidebar in the given layout can be removed while execution and can be used during configuration as it is in present app. Also a bottom time slider can be added as proposed in previous layout.

The remote shown at the bottom can be neglected as it was used for data storage that was generated
![screenshot from 2018-05-21 20-28-58](https://user-images.githubusercontent.com/32356267/40314592-8e9ca6a6-5d36-11e8-855b-fdb5f59d70a0.png)

Here we can provide four channels to switch
![screenshot from 2018-05-21 20-29-10](https://user-images.githubusercontent.com/32356267/40314593-8ef1a1d8-5d36-11e8-9f6c-d4a93142807c.png)
![screenshot from 2018-05-21 20-29-16](https://user-images.githubusercontent.com/32356267/40314594-8f1e179a-5d36-11e8-973d-f9e68c64d530.png)
![screenshot from 2018-05-21 20-29-44](https://user-images.githubusercontent.com/32356267/40314599-8fc0258a-5d36-11e8-9d1c-3a44c2a59742.png)
This part is implemented but the cursor doesn't shows data at which it is pointed. 

Here is the reference [link](http://redpitaya.readthedocs.io/en/latest/appsFeatures/apps-featured/logic/logic.html)

Is this layout for android app suitable ?

**Comment by CloudyPadmal** [comment]
How can we select which channels to display and which mode (Falling Edge, Rising Edge, Normal Pulse)?

**Comment by CloudyPadmal** [comment]
Yes looks fine! Please update with a mockup!
