### ISSUE TITLE
Fix the issues making Codacy fail

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#892]
**Actual Behaviour**

There are some errors in code such as scoping, variable declaration which causes Codacy tests fail

**Expected Behaviour**

Codacy is there to test the structural accuracy of code and the tests need to be passed

**Steps to reproduce it**

Check the Codacy report of PSLab Android

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

**Comment by woshikie** [comment]
Codacy issue has been resolved
