### ISSUE TITLE
SHT21 : Temperature and Humidity Meter UI Improvement

### ISSUE THREAD

**Issue by yatri1609** [fossasia/pslab-android#893]
**Actual Behaviour**
Right now only the Temperature and Humidity are recorded and plotted on the graph. I would like to add maximum and minimum for the same and also enable units change from Celsius to Fahrenheit and vice versa. 
Including some UI improvements. 

**Expected Behaviour**
![screenshot-2018-5-21 mextech m288cthw digital thermo hygrometer with indoor outdoor temperature amazon in industrial scient](https://user-images.githubusercontent.com/34381723/40312711-4674587e-5d31-11e8-9233-faf04ea0fdf8.png)
This is the kind of Thermo Hygrometers available in the market. So I would like to develop similar UI kind of UI with buttons for changing a the units and implementing maximum and minimum. 
I would be uploading the new UI soon.

**Steps to reproduce it**
Check layout [file] (https://github.com/fossasia/pslab-android/blob/development/app/src/main/res/layout/sensor_sht21.xml) 

**LogCat for the issue**
Not applicable

**Screenshots of the issue**
![screenshot from 2018-05-21 20-04-42](https://user-images.githubusercontent.com/34381723/40313103-5c034cf8-5d32-11e8-9b30-c818f62d093b.png)
![screenshot from 2018-05-21 20-05-20](https://user-images.githubusercontent.com/34381723/40313105-5c449f5a-5d32-11e8-9511-737fdab527f1.png)

**Would you like to work on the issue?**
Yes

**Comment by yatri1609** [comment]
![screenshot from 2018-05-22 12-10-28](https://user-images.githubusercontent.com/34381723/40346087-4e16ed34-5db9-11e8-909b-a1288a1fc9b7.png)
![screenshot from 2018-05-22 12-10-54](https://user-images.githubusercontent.com/34381723/40346088-4e72ac32-5db9-11e8-9b17-d707c9ea5357.png)

This is what I'm planning to do both for Humidity and Temperature. Please review it and tell me if any add-ons or changes are needed.

**Comment by Vikum94** [comment]
You can research more and post some more pictures. There are lot of mobile applications developed to measure temperature and humidity using a sensor. You can adjust your UI accordingly.

[Check this](https://www.amazon.com/Thermometer-Hygrometer-Temperature-Humidity-Smartphone/dp/B019178SY2)

![image](https://user-images.githubusercontent.com/17523141/40348897-98318fe2-5dc2-11e8-96c6-eb8b37c64762.png)

**Comment by yatri1609** [comment]
![sht21 svg](https://user-images.githubusercontent.com/34381723/40546590-4171ac2c-604d-11e8-8de9-f7c3d59cb6a4.png)
 What do you think about this?

**Comment by CloudyPadmal** [comment]
@yatri1609 how is the progress? Can we add both humidity and temperature data in the same window without using two tabs just like in the app suggested by @Vikum94 ?

**Comment by yatri1609** [comment]
@CloudyPadmal Ya I think we can do that and then down we can show buttons which will open up graphs or we can make the icons clickable.

**Comment by yatri1609** [comment]
@CloudyPadmal  Do we need to implement the color as per the the temperature and humidity or just put the icons and a mark on the scale?

**Comment by CloudyPadmal** [comment]
Design with the app theme would be great!

**Comment by cweitat** [comment]
Can I know why is it difficult to implement? What problems did you faced? If you faced problems displaying 2 data in one graph, do ask any one who did oscilloscope to assist. 
Some graphics like the thermometer and the water droplet sign can be excluded. Both temp and humidity should be in the same chart with different line colours. 
Temperature font size doesn't need to be so big. Have a look at Lux Meter. That font size is good enough. I'm sure you can handle the design.

**Comment by yatri1609** [comment]
@cweitat Ohk the difficulty was in implementing the thermometer and the water droplet so ya I guess other than that I would be able to handle it now. I'll submit a mockup for the same soon

**Comment by cweitat** [comment]
@yatri1609 what's the progress for this?

**Comment by yatri1609** [comment]
I guess Harsh was also implementing the temperature and humidity sensor according to the updated sensor list. I have worked half way through this from my part.

**Comment by yatri1609** [comment]
@cweitat I'll submit suggested layout by tomorrow

**Comment by yatri1609** [comment]
@cweitat I guess the temperature and humidity sensor is now DHT11 #1172 rather than SHT21 so I'm not working on this.

**Comment by cweitat** [comment]
@yatri1609 Are you working on it halfway already? it is okay to implement other sensors also. Doesn't necessarily need to be DHT11. The more sensors the device can work with the better

**Comment by yatri1609** [comment]
@cweitat ohk I'll continue with this but it will be better to have a same UI for both as both measures temperature and humidity.

**Comment by yatri1609** [comment]
@cweitat I'm almost done with the UI which will be similar to the Lux meter and Barometer with just single graph showing both the data in it.

**Comment by cweitat** [comment]
@yatri1609 do you have screenshots? so of course the ideal situation is that the device is able to automatically detect DHT11  or SHT21

**Comment by yatri1609** [comment]
<img src = "https://user-images.githubusercontent.com/34381723/43903463-21bf175e-9c0a-11e8-9d79-147234d043eb.png" width = 300>
Is this kind of layout fine, with 2 meters showing temperature and humidity both? And then chart to show the graphs? @cweitat @CloudyPadmal

**Comment by cweitat** [comment]
Please check out #1349

**Comment by yatri1609** [comment]
@cweitat What do you think about this ? I had already suggested earlier 
<img src = "https://user-images.githubusercontent.com/34381723/40346087-4e16ed34-5db9-11e8-909b-a1288a1fc9b7.png" width = 300>

**Comment by cweitat** [comment]
@yatri1609 Don't need the section boxes. The previous design is good enough. Let's finalise the standard design to use first before proceeding

**Comment by yatri1609** [comment]
@cweitat Yes sure, I'm currently stopping my working on this.

**Comment by CloudyPadmal** [comment]
There is a UI available with mentioned min max values with value changes
