### ISSUE TITLE
Oscilloscope guide and documentation

### ISSUE THREAD

**Issue by Vikum94** [fossasia/pslab-android#898]
**Actual Behaviour**

No existing guide on how to use the Oscilloscope instrument. 

**Expected Behaviour**

Need a clear documentation on how to use the Oscilloscope at the [pslab-android/Docs](https://github.com/fossasia/pslab-android/tree/development/docs)

**Steps to reproduce it**

> Not applicable

**LogCat for the issue**

> Not applicable

**Screenshots of the issue**

> Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Added in #899
