### ISSUE TITLE
Consider reducing UI tests

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/pslab-android#902]
There are only 2 UI tests in the app right now. It means that the test coverage in UI tests is small. Hence, the huge disadvantage of about 10 minute build time and waiting for emulator outweighs the advantage of having such small set of tests.

Either UI tests should cover lot of cases (not recommended as unit tests should handle most of this) or UI tests should be disabled and replaced with counter unit tests which will run in milliseconds rather than 20 minutes

One of the test is acually a dummy test.
Right now navigation of app is tested via UI tests. I would say that this is not such an important test but can be easily replicated in the abstracted unit test. If not, I recommend roboelectric to do the same test on JVM. Although not as fast as a unit test, it will run in 1-2 seconds as compared to current situation.

This can be taken up after crucial bug fixes and features but will significantly improve the build time and hence development iterations

**Comment by CloudyPadmal** [comment]
Agreed @iamareebjamal ! :+1: Current UI tests do check only if the starting views are up. This can be tested by other means.

**Comment by iamareebjamal** [comment]
@CloudyPadmal Where are we on this front?

**Comment by iamareebjamal** [comment]
This is still not resolved
