### ISSUE TITLE
modify polynomial processing functions in AnalogChannel

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#91]
modify polynomial processing functions in AnalogInputSource to handle arguments as single value and array both.
Source File [link](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java)

New Polynomial Implementation should be taken into consideration i.e Polynomial object provided by apache common math library and necessary changes should be made.
About Apache Common Math Polynomial https://github.com/fossasia/pslab-android/issues/71

**Comment by akarshan96** [comment]
@viveksb007 I have modified entire repo implementing with the new Polynomial approach using Apache Maths Commons. That includes AnalogInputSource.java. Should I make a pull request or drop the commits as I see you already working on it?

**Comment by viveksb007** [comment]
Make a PR. 
And have you modified functions accordingly to find value of polynomial at different data points?

**Comment by akarshan96** [comment]
@viveksb007 I have made the changes in the functions too, let me make a PR and you can review and point if something I missed.
