### ISSUE TITLE
Changing "Applications" list with cardviews

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#92]
The current _Applications_ view consists of a list view with basic list items. It doesn't have much of a description on what each item would do.

| Current View | 
| ------------- | 
| ![device-2017-05-06-174450](https://cloud.githubusercontent.com/assets/14261304/25772214/a157b108-3255-11e7-8fcc-16e06d32c84f.png) |

This view can be enhanced with the help of a list view with card items or a grid view as follows!

| Card Views | Grid Views |
| ---------------| -------------- |
| ![image](https://cloud.githubusercontent.com/assets/14261304/25772333/09c6ac06-3258-11e7-9299-c314a271848c.png) | ![image](https://cloud.githubusercontent.com/assets/14261304/25772297/51d1293c-3257-11e7-8fc2-d523a5ba6d8f.png) |

If this feature is okay to implement, I can get to work on it! :)

**Comment by viveksb007** [comment]
Could you tell a bit about what description you want to show?
I think the name are self explanatory.
Could you look into when the application fragment is rendered for first time, the transition isn't so smooth?
If you are facing the same problem.

**Comment by CloudyPadmal** [comment]
Yes @viveksb007 it lags a bit! I can work on it!! :+1:

**Comment by asitava1998** [comment]
I think you should implement the GridViewLayout. It would be more compact as scrolling through the layout is less and there is no need of descriptions as Vivek mentioned.

**Comment by CloudyPadmal** [comment]
@asitava1998 I'll implement a GridView and send a PR! :) Currently I'm trying to fix the lag happening when _Applications_ view is opened for the first time!

**Comment by akarshan96** [comment]
What I am thinking is to have both listview and gridview. Provide a user button that would convert the list to grid and vice versa. The button will make one view visible while another invisible. What say ?

**Comment by CloudyPadmal** [comment]
That would be cool right? :D May be in settings we can provide an option to select which view user needs!

**Comment by CloudyPadmal** [comment]
How's this UI? :) 

![device-2017-05-08-005526](https://cloud.githubusercontent.com/assets/14261304/25784360/01b509e6-335b-11e7-8106-6420fdbe2fb9.png)

**Comment by asitava1998** [comment]
Looks neat to me.

**Comment by CloudyPadmal** [comment]
Thank you @asitava1998 !! Made the titles Bold!

![device-2017-05-08-005954](https://cloud.githubusercontent.com/assets/14261304/25784395/999e97c2-335b-11e7-9828-ca11cc5e7d68.png)

**Comment by akarshan96** [comment]
@CloudyPadmal Looks great. One suggestion, we can add round corners to each tile. What say?

**Comment by jithinbp** [comment]
I think we need a thorough discussion on the UI . Can we all spend some
time on some online collaborative UI editor?

I feel the controls/advanced controls section should be accessible in the
form of a slide-out drawer regardless of what experiment is running. That
way it's more like having separate instruments at hand .

Of course, one may have control-widgets pertinent to each experiment in its
own layout also, but the rest should also stay within reach

**Comment by asitava1998** [comment]
@jithin That would be better as so far not all of us have been involved in giving suggestions about the UI. Mario suggested the use of [Invision](https://www.invisionapp.com), we can try this one as it supports collaboration or any other that others might suggest.

**Comment by CloudyPadmal** [comment]
@akarshan96 that would be nice right? I'll add!! @jithinbp that's a good idea! I agree! :+1: Let's try Invision !!
