### ISSUE TITLE
Implement power source instrument

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#927]
**Actual Behaviour**

Power source instrument feature is not available in the app

**Expected Behaviour**

In the `Power Source` tab, the feature needs to be implemented. Starting from basic UI design

**Steps to reproduce it**

Check `Power Source` in `Instruments` view

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Assigned to @abhinavraj23

**Comment by harsh-2711** [comment]
@CloudyPadmal @abhinavraj23  Can I work on this as I have completed my milestone and @abhinavraj23  is working on Google forms issue and multimeter issue

**Comment by CloudyPadmal** [comment]
@harsh-2711 it's just the UI right? Now you can start with the actual coding part to make logic analyzer functional.

**Comment by harsh-2711** [comment]
Ok:1:

**Comment by abhinavraj23** [comment]
@CloudyPadmal We can implement power source using knob as well (in case of most actual cases)? Also In the pslab-destop-apps it is implemented in the same manner. Please comment
