### ISSUE TITLE
Create a controlling panel UI for wave generator activity

### ISSUE THREAD

**Issue by Avjeet** [fossasia/pslab-android#929]
**Actual Behaviour**

There is no panel for wave generator activity for controlling characteristics of waves.

**Expected Behaviour**

There should be a panel with all the controls, buttons, seek bars to control the output of the wave.

**Steps to reproduce it**

Wavegenerator Activity->create a controlling panel

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@Avjeet will this issue address more UI addition or actual functionality?

**Comment by Avjeet** [comment]
No, this issue is only for control UI, when the UI is accepted I will implement their functionality in next PR.

**Comment by CloudyPadmal** [comment]
Please implement the complete UI in one issue. It doesn't make sense to open many issues to implement different parts of the same screen!
