### ISSUE TITLE
Voltage dropdown pops up when opening oscilloscope 

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#931]
**Actual Behaviour**
The voltage dropdown to select CH1 pops up automatically when opening oscilloscope 

**Expected Behaviour**
Dropdown should be kept closed till user press on it

**Steps to reproduce it**
Open oscilloscope and you will see it

**Screenshots of the issue**
![photo_2018-05-28_14-22-57](https://user-images.githubusercontent.com/11439477/40610707-0f36f676-62a6-11e8-8290-276956c92f4c.jpg)

**Would you like to work on the issue?**
@abhinavraj23 or @Vikum94

**Comment by cweitat** [comment]
#816

**Comment by cweitat** [comment]
reference #816

**Comment by Vikum94** [comment]
@cweitat @CloudyPadmal This does not happen with either the application in pslab-android/development or in Play store. Can you please check again.

**Comment by cweitat** [comment]
https://drive.google.com/open?id=11uOxHarBdiVYPYUkR2eHzxpX7FJ5nLw2
Have a look at the attached video

**Comment by cweitat** [comment]
dropdown doesn't appears on Android 8
issue open to more feedback from other users

**Comment by cweitat** [comment]
This doesn't happen to another Android 7.0 phone tested. Probably just my phone.
So this issue can either leave it open to or @Vikum94 @CloudyPadmal can close it.

**Comment by CloudyPadmal** [comment]
Yea @cweitat it doesn't looks like a reproducible issue. Let's close it then :)

**Comment by cweitat** [comment]
Saw another device that has this issue today: Samsung S7 Edge
