### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [fossasia/pslab-android#939]
Sorry for not having the template,
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by cweitat** [comment]
Hi @jbeguna04 
You can post a few designs over public chat for discussion and for us to take a look instead of here! 
Link to our public chat: https://gitter.im/fossasia/pslab
