### ISSUE TITLE
Implement PV sources in Power Source Instrument

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#953]
**Actual Behaviour**

Current Power Source instrument is just boilerplate code.

**Expected Behaviour**

Programmable Voltage Sources need to be implemented and tested.

**Steps to reproduce it**

1. Open app
2. Go to `Power Sources`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

**Comment by abhinavraj23** [comment]
@CloudyPadmal I have completed my milestone task, so now if you want then both of us can work on the implementation of power source.

**Comment by CloudyPadmal** [comment]
@abhinavraj23 Let's finish one instrument fully and then move onto the other one. Now that you have completed the UI, you can open up new issues and start working on coding implementation and test it with the device.
