### ISSUE TITLE
Remove the control section codes

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#965]
**Actual Behaviour**

Now the control section is now split into power source,multimeter and wave generator but still its code is there.

**Expected Behaviour**

The control section code should be removed.

**Steps to reproduce it**

Delete it from code-base.

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Unnecessary at the moment
