### ISSUE TITLE
Unhandled threads in sensors fragment

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#969]
**Actual Behaviour**

When any sensor is opened from the given list, then on pressing back button crashes the app

**Expected Behaviour**

The app shouldn't crash, rather main fragment main fragment of sensor activity should pop up

**Steps to reproduce it**

Go to sensors and use any sensor from the list and then press back key

**LogCat for the issue**

Not available

**Screenshots of the issue**

![20180605_050028](https://user-images.githubusercontent.com/32356267/40946868-78c25cb6-687d-11e8-85cc-2ed5669611d4.gif)

**Would you like to work on the issue?**

Yes

NOTE: The toast message only shows the number of running threads while app crashed

**Comment by harsh-2711** [comment]
@CloudyPadmal  Can I convert the sensors fragment to there respective activity as it will solve this and the subsequent issues that are opened by me. It will be easier to handle threads and layouts for activity rather than overlapping fragments. Also the sensordock used is always cut out because the layouts aren't designed properly. So should I proceed with this idea or do you have any other better solution?

**Comment by CloudyPadmal** [comment]
Yes that would be better! :+1:
