### ISSUE TITLE
List of sensors not handled properly in different orientations

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#970]
**Actual Behaviour**

The list of senors changes on changing the orientation

**Expected Behaviour**

The list should remain same in both the cases

**Steps to reproduce it**

Go to sensors and change the orientation

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

![20180605_050843](https://user-images.githubusercontent.com/32356267/40947090-896711e6-687e-11e8-8e2d-489371c12a1b.gif)

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@harsh-2711 we are implementing sensors as separate instruments. So don't put too much effort on tasks like these as this fix will not be used.
