### ISSUE TITLE
Multimeter shows various values for a single resistance

### ISSUE THREAD

**Issue by abhinavraj23** [fossasia/pslab-android#976]
**Actual Behaviour**

Multimeter shows various values for a single resistance  when clicked multiple time(as every resistance has some tolerance level)

**Expected Behaviour**

It should show a single value which should be average of 10 values taken.

**Steps to reproduce it**

Run an iterative loop 10 times and calculate the average.

**LogCat for the issue**

Not Applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@abhinavraj23 what if user changes the resistor during the loop?

**Comment by abhinavraj23** [comment]
@CloudyPadmal I was thinking about that, but I have observed that in 10 observations the average becomes constant and thus we have to limit the loop till 10, which according to me will not take that time so as the user changes the resistor, what do you think about it, we can also keep a toast telling the user to keep the resister intact for few minutes. Please comment
