### ISSUE TITLE
Improvements on Power Source Tile

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#998]
**Actual Behaviour**

Tile image for power source looks big and mis-aligned

**Expected Behaviour**

Tile image needs to be aligned properly with correct margins around them, even in portrait mode.

**Steps to reproduce it**

1. Open app
2. Scroll down instruments list for `Power Source`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![screenshot_2018-06-08-18-41-06](https://user-images.githubusercontent.com/14261304/41159911-bcdc058e-6b4b-11e8-896a-3194316bd335.png)

**Would you like to work on the issue?**

Yes

**Comment by cweitat** [comment]
Multimeter and logical analyzer does not looks good as well. 

![photo_2018-06-13_03-28-59](https://user-images.githubusercontent.com/11439477/41312538-e169dd74-6eb9-11e8-83b3-2167f770f2c6.jpg)

This problem affects based on devices' resolution. On high res devices, the some icons look normal.

**Comment by CloudyPadmal** [comment]
Yes @cweitat ! The reason is the whole card is made as an image. So it doesn't stretch out properly in different screens. Let me have a fix for this one! :+1:
