### ISSUE TITLE
Add device connection menu items to power source

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#999]
**Actual Behaviour**

In the top action bar, device connectivity menu items are not made available

**Expected Behaviour**

Similar to `Instruments` page, top action bar requires the menu items in `Power Source`

**Steps to reproduce it**

1. Open app
2. Go to `Power Source` and observe the action bar

**LogCat for the issue**

> Not available

**Screenshots of the issue**

![device-2018-06-08-181541](https://user-images.githubusercontent.com/14261304/41160074-216dd022-6b4c-11e8-8283-c3996025e384.png)

**Would you like to work on the issue?**

Yes

**Comment by cweitat** [comment]
@CloudyPadmal currently the compass on the instruments page has nothing yet. Can we have a toast when a user press on it to show text like "Still in development. Please check next time."? Otherwise user may think that it is the app/phone not working. Thanks

**Comment by CloudyPadmal** [comment]
Yes @cweitat ! I'll make that change and send a PR in a while! :+1:

**Comment by neel1998** [comment]
@CloudyPadmal  @mariobehling  @cweitat  The compass instruments screen has now been implemented. So there is no need for the toast. I think this issue can be closed
